.travis.yml, tests/ir/CMakeLists.txt
This syncs the names with master.
=> [ltsmaster] Rename test suite llvm-ir-testsuite to lit-tests.

driver/main.cpp
According to https://dlang.org/spec/version.html there is no `MIPS` global identifier, noticed that LDC was setting it but not setting the `MIPS32` one mentioned on the spec. When I did the `uClibc` port I used the spec, so obviously it didn't worked.
This patch adds it to the mips/mipsel architecture selection. 
Using this config `ldc2 -mtriple=mipsel-unknown-linux-uclibc -mcpu=mips32 -gcc=mipsel-openwrt-linux-uclibc-gcc  -release -Os -betterC` I tested a simple `hello world` in `betterC` variant on my shiny new `LinkIt Smart 7688 Duo`, it worked! pretty impressive 👍
=> Add mising MIPS32 global identifier

tests/semantic/asm_datadefinition_diag.d, tests/semantic/dcompute.d, tests/semantic/dcompute_asm.d
This should fix these tests for e.g. arm platforms, see failure on armv7 platform : http://buildbot.ldc-developers.org/builders/armv7neon_builder/builds/289/steps/testlit/logs/stdio
=> Lit tests that use DMD-style asm should explicitly target a supporting target (X86)

gen/asmstmt.cpp
Inspired by the initially surprising error message reported on ARM:
`......./semantic/asm_datadefinition_diag.d(10): Error: inline asm is not supported for the "armv7a" architecture`
Shall I enhance the first error message with a hint towards `ldc.llvmasm.__asm`?
`"DMD-style inline asm is not supported for the \"%s\" architecture. Instead, use ldc.llvmasm.__asm."
=> Clarify that error messages relate only to DMD-style asm.

gen/abi-x86.cpp, gen/asm-x86.h, gen/naked.cpp, tests/codegen/hashed_mangling.d
DMD 2.079 introduces this breaking ABI change. Just like on 32-bit OSX, the mangled names of D symbols now include the platform-specific underscore prefix.
=> [2.079] Win32: Add extra underscore for mangled names of D symbols

gen/runtime.cpp, gen/runtime.h, gen/trycatchfinally.cpp
This fixes the 32-bit std.file unittests on Linux with enabled optimizations.
The remaining LDC-specific ARM EABI wrapper (`_d_eh_resume_unwind()`) is implemented in assembly (ldc/eh_asm.S), preserving registers apparently.
=> [2.079] Call _Unwind_Resume() directly (except for ARM EABI)

tests/ir/attributes.d
On PPC, the i32 ABI is `signext i32`.
See failure: http://buildbot.ldc-developers.org/builders/powerosl_builder/builds/1081/steps/testlit/logs/stdio
To be cherry-pick onto `master` once merged.
@redstar
=> Fix attributes.d test for PPC.

tests/semantic/target_traits.d
Explicit targeting of x86 was forgotten in this test.
See for a failure on PPC: http://buildbot.ldc-developers.org/builders/powerosl_builder/builds/1080/steps/testlit/logs/stdio
=> Fix semantic/target_traits.d test on non-X86 platforms.

tests/ir/asm_output.d
See failure on PPC: http://buildbot.ldc-developers.org/builders/powerosl_builder/builds/1081/steps/testlit/logs/stdio
To be cherry-picked onto `master` once merged.
@redstar
=> Try to test asm output in another way for more platform independence

driver/codegenerator.cpp, driver/linker-msvc.cpp, gen/arrays.cpp, gen/classes.cpp, gen/declarations.cpp, gen/functions.cpp, gen/llvmhelpers.cpp, gen/moduleinfo.cpp, gen/modules.cpp, gen/passes/GarbageCollect2Stack.cpp, gen/passes/SimplifyDRuntimeCalls.cpp, gen/rttibuilder.cpp, gen/rttibuilder.h, gen/runtime.cpp, gen/runtime.h, gen/statements.cpp, gen/tocall.cpp, gen/toir.cpp, gen/tollvm.cpp, gen/trycatchfinally.cpp, gen/typinf.cpp, ir/irclass.cpp
Thereby deferring requirements wrt. object.d declarations (Object, Throwable, TypeInfo, TypeInfo_Class, TypeInfo_Struct...) and paving the way for a minimal druntime.
This also greatly reduces the `-vv` output for tiny code samples, e.g., reduced test cases.
=> [2.079] Support minimal runtime

ir/irclass.cpp, tests/codegen/variadic_thunk_gh2613.d
=> Make interface thunks forward variadic args

gen/asm-x86.h, tests/codegen/dmd_inline_asm_fp_types.d
Don't map `Extended_Ptr` to `Double_Ptr` for MSVC targets with 64-bit reals.
Instead, map reals to `Double_Ptr` directly, thereby still allowing to work with 80-bit extended precision values via `extended ptr`.
=> MSVC: Fix `extended ptr` semantics in DMD-style inline asm

.circleci/config.yml, driver/toobj.cpp, runtime/CMakeLists.txt, runtime/jit-rt/DefineBuildJitRT.cmake
This allows additional bitcode libs to be generated simultaneously with the normal druntime/Phobos libs (i.e., single compilation) by including something like `-DBUILD_LTO_LIBS=ON -DD_FLAGS="-w;-flto=thin"` in the CMake command line (additional D_FLAGS entry here to include the ThinLTO module summaries in the bitcode files; not needed for FullLTO).
This then allows linking against the LTO default libs via `ldc2 -flto=<thin|full> ... -defaultlib=phobos2-ldc-lto,druntime-ldc-lto`; unfortunately, I couldn't test this yet, as my LLVM 6 Linux build has a 0-byte LLVMgold.so...
=> Ship with LTO default libs on Linux & macOS

tests/codegen/array_equals_memcmp_dyn.d
The frontend now does most of the dyn-dyn comparison optimization (turning it into a druntime template function call).
Caused a failure on PPC: http://buildbot.ldc-developers.org/builders/powerosl_builder/builds/1080/steps/check/logs/stdio
=> Fix array_equals_memcmp_dyn test.

runtime/CMakeLists.txt
Allow building shared library on freebsd/dragonflybsd (ltsmaster) using:
```
cmake BUILD_SHARED_LIB=ON -DLLVM_CONFIG=[path-to-llvm]/llvm-config ..
```
=> [Trivial / ltsmaster] Allow shared library on freebsd/dragonflybsd

driver/main.cpp, driver/targetmachine.cpp, driver/targetmachine.h, gen/dcompute/targetCUDA.cpp, tests/driver/float_abi.d
Matching the `D_HardFloat` [semantics](https://dlang.org/spec/version.html#predefined-versions):
> The target hardware has a floating point unit
=> Predefine version D_HardFloat instead of D_SoftFloat for -float-abi=softfp

driver/targetmachine.cpp
* Add support for 64-bit DWARF.
* Add support for DWARF v4.
* Fix alignment issues on non-x86 architectures (DWARF data is packed).
* Fix backtrace on Ubuntu 18.04 (DSO-relative DWARF addresses vs. absolute addresses returned by `backtrace()`) => probably fixes https://issues.dlang.org/show_bug.cgi?id=18068.
Testing here how `codegen/exception_stack_trace.d` looks like with Ubuntu 14.04; should go upstream when finished.
=> druntime: Fix rt.backtrace.dwarf

.circleci/config.yml
Obsolete since dub v1.7, see https://github.com/ldc-developers/ldc-scripts/pull/7.
=> CircleCI: Exclude obsolete dub settings file from package

.travis.yml
... instead of allowing both jobs to fail.
=> Travis Linux: Remove dmd-testsuite test failing with shared libs

.travis.yml, tests/codegen/dcompute_cl_addrspaces.d
See issue #2709.
It's been a very long while that this issue is preventing green on osx llvm6 travis CI. So let's just disable the test, with the knowledge that Spir-V functionality is broken.
=> Disable spir-v test, such that CI is green again.

tests/CMakeLists.txt, tests/lit.site.cfg.in
Hack with manual LLVMConfig inclusion is already used in jit cmake so it shouldnt break more things.
=> Expose host architecture for lit tests

dmd/expression.d
These sporadic segfaults have been plaguing AppVeyor lately, especially when building dub. Upstream pull: https://github.com/dlang/dmd/pull/8294
=> Fix typo in dmd.expression apparently causing sporadic frontend crashes

tests/dynamiccompile/asm_output.d, tests/dynamiccompile/throw.d
* Disable jit exceptions test on ARM (I don't have hardware, nor time to debug it right now)
* Dump actual asm output to stdout in `asm_output` test (lit will only display it if test fail, what I can see now from test failure, it should be at least partially correct)
@JohanEngelen
=> #2687: ARMv7: dynamiccompile failures

gen/abi-win64.cpp
Return types have been checked for POD-ness already, but parameters haven't.
=> Win64: Fix extern(C++) ABI wrt. passing non-POD structs by value

gen/abi-win64.cpp, runtime/jit-rt/cpp-so/compile.cpp, tests/codegen/hashed_mangling.d, tests/codegen/vector_abi_x86.d
I.e., pass and return vectors in registers. With the default C calling convention (and the Win64 TargetABI not touching any vectors), vectors are returned in XMM0, but inefficiently passed as ref to hidden copy (automatically by LLVM and conforming to the regular Win64 platform ABI).
Microsoft's vector calling convention, introduced opt-in with VS 2013, additionally puts HFAs and HVAs (Homogeneous Float/Vector Aggregates) into registers, see https://blogs.msdn.microsoft.com/vcblog/2013/07/11/introducing-vector-calling-convention/.
=> Win64: Use LLVM's vector calling convention for extern(D)

gen/abi-aarch64.cpp, gen/abi-arm.cpp, gen/abi-generic.h, gen/abi-mips64.cpp, gen/abi-nvptx.cpp, gen/abi-ppc.cpp, gen/abi-ppc64le.cpp, gen/abi-spirv.cpp, gen/abi-win64.cpp, gen/abi-x86-64.cpp, gen/abi-x86.cpp, gen/abi.cpp, gen/abi.h, gen/dcompute/abi-rewrites.h, gen/dibuilder.cpp, gen/functions.cpp, gen/nested.cpp, gen/tocall.cpp, gen/toir.cpp, ir/irfunction.cpp, ir/irfuncty.cpp, ir/irfuncty.h, ir/irtypefunction.cpp, tests/codegen/indirect_byval_rewrite.d
Unoptimized old IR for the included lit-test:
```LL
define void @_D22indirect_byval_rewrite3barFZv() #0 comdat {
%bigLValue = alloca %indirect_byval_rewrite.Big, align 8 ; [#uses = 2, size/byte = 16]
%withPostblitLValue = alloca %indirect_byval_rewrite.WithPostblit, align 8 ; [#uses = 2, size/byte = 16]
%.ExplicitByvalRewrite_dump = alloca %indirect_byval_rewrite.Big, align 16 ; [#uses = 2, size/byte = 16]
%__copytmp3 = alloca %indirect_byval_rewrite.WithPostblit, align 8 ; [#uses = 3, size/byte = 16]
%.ExplicitByvalRewrite_dump1 = alloca %indirect_byval_rewrite.WithPostblit, align 16 ; [#uses = 2, size/byte = 16]
%.sret_tmp = alloca %indirect_byval_rewrite.Big, align 8 ; [#uses = 2, size/byte = 16]
%.ExplicitByvalRewrite_dump2 = alloca %indirect_byval_rewrite.Big, align 16 ; [#uses = 2, …
```
=> Some ABI refactoring, incl. efficiency improvements for IndirectByvalRewrite

appveyor.yml
To work around the `tests/driver/mscrtlib.d` failures, which are probably due to the new 'Spectre-mitigation' MS libs breaking the EH terminate hook in druntime.
=> AppVeyor: Temporarily revert to previous VS 2017 image for x64 job

gen/dynamiccompile.cpp, tests/dynamiccompile/simple.d
For some reason, this broke things only on win32.
=> Set proper calling convention and attributes to jit thunk call

gen/abi-aarch64.cpp, gen/abi-arm.cpp, gen/abi-mips64.cpp, gen/abi-nvptx.cpp, gen/abi-ppc.cpp, gen/abi-ppc64le.cpp, gen/abi-spirv.cpp, gen/abi-win64.cpp, gen/abi-x86-64.cpp, gen/abi-x86.cpp, gen/abi.cpp, gen/abi.h, gen/functions.cpp, gen/tocall.cpp
Fixing one aspect of issue #2702; not tackling the different destruction rules yet.
=> Use IndirectByvalRewrite for non-POD args and extern(C++) on Posix

dmd/semantic3.d, dmd/target.d, dmd/target.h, dmd/traits.d, gen/abi-aarch64.cpp, gen/abi-arm.cpp, gen/abi-mips64.cpp, gen/abi-nvptx.cpp, gen/abi-ppc.cpp, gen/abi-ppc64le.cpp, gen/abi-spirv.cpp, gen/abi-win64.cpp, gen/abi-x86-64.cpp, gen/abi-x86.cpp, gen/abi.cpp, gen/abi.h, gen/functions.cpp, gen/functions.h, gen/target.cpp, gen/tollvm.cpp
MSVC++ methods apparently return *all* structs via sret, even small PODs, see https://issues.dlang.org/show_bug.cgi?id=18928 and #1935.
The problem is that the ABI code operates with `TypeFunction`, which contains no information about enclosing aggregate nor whether it's a static function declaration (a class member function, behaving like other regular functions).
~~The very hacky attempt here is adding a new bool `ismethod` to TypeFunction, setting it at parse-time to whether it's declared in a non-static scope and later checking if it's additionally an aggregate member during type-semantic (at which point the `static` storage class appears to be masked out), setting it back to false if it isn't. But I'm not familiar with this front-end code at all, so may/hopefully have missed a …
=> MSVC: Port Rainer's upstream extern(C++) method ABI fixes

dmd/builtin.d, dmd/expressionsem.d, dmd/root/ctfloat.d, dmd/root/ctfloat.h, gen/functions.cpp, tests/fail_compilation/no_address_for_intrinsics.d
As `pragma(inline, true)` is currently ignored without explicitly enabled cross-module-inlining, LTO with LTO-default-libs was previously required to get rid of the druntime/Phobos calls and enable further optimizations.
=> Avoid LLVM intrinsic wrappers, prefer aliases

driver/archiver.cpp, runtime/CMakeLists.txt
Also cross-checked against LLVM 6.0.0 (no relevant changes though).
=> [macOS] CMake: Work around ranlib potentially corrupting static libs

.circleci/config.yml, CMakeLists.txt, appveyor.yml, driver/targetmachine.cpp
Incl. `__debug_line` Mach-O section hack.
=> Circle & AppVeyor: Upgrade to LDC-LLVM 6.0.1

gen/classes.cpp, gen/declarations.cpp, ir/irclass.cpp, tests/baremetal/classes.d
For `-betterC` and/or a minimal `object.d` without TypeInfo:
* Skip TypeInfo emission for classes and interfaces.
* Emit null as first vtable member.
Makes dmd-testsuite's `{compilable,runnable}/minimal2.d` work.
=> Add some support for classes without TypeInfos

appveyor.yml
=> druntime: Work around core.cpuid regression with LLVM 6 on Win32

driver/main.cpp
As that (+ `D_LP64` for wasm64) is what DMD does, according to Petar (https://github.com/ldc-developers/ldc/issues/2144#issuecomment-335181401).
=> Replace predefined versions WebAssembly{32,64} by general WebAssembly

.circleci/config.yml, CMakeLists.txt, runtime/CMakeLists.txt
This should allow [removing this line from CI, ie downloading the stdlib for no reason and wasting bandwidth](https://github.com/dlang/ci/pull/228/files#diff-e6bd4021b60e04e45022336bda968fdeR206), and could make building ldc easier for `betterC` users.
Tested on linux/x64 with Make and Ninja from a ldc git checkout without the submodules and with the ~`ldc2`~`all` target, ~other targets like `ldc-build-runtime` won't work~.
=> CMake: Don't include the runtime CMake config if no stdlib source available

gen/llvmhelpers.cpp, tests/compilable/gh2808.d
=> No context ptr for nested non-extern(D) functions

runtime/jit-rt/DefineBuildJitRT.cmake
Purely speculative - use CXX instead of C as linker language for the jit-rt DLL.
=> CMake: Fix issue #2784 (build as Xcode project)

gen/abi-aarch64.cpp, shippable.yml
C++ va_list is mangled as `std::__va_list` struct. According to clang IR, it's special in the sense of not ever being passed by value.
Let's do the same and pass a pointer while at the same time mangling the function as taking the arg by value.
=> AArch64: Fix C++ mangling of va_list & apply ltsmaster's IndirectByvalRewrite fix

dmd/root/array.h, driver/configfile.d, driver/configfile.h, driver/linker-gcc.cpp, driver/linker-msvc.cpp, ldc2.conf.in, ldc2_install.conf.in, ldc2_phobos.conf.in, runtime/CMakeLists.txt
And replace the default `-L-L<path>` LDC switches in the default config accordingly.
The first advantage is for cross-compilation, where additional sections should now mostly get away with overriding `lib-dirs` (and `rpath` if need be) only; not just to specify the directory containing cross-compiled druntime and Phobos, but also further dirs containing the C libs. No need to override a whole `[post-]switches` array anymore just to tweak the lib dirs.
The second advantage is that we can search these dirs for compiler-rt libs instead of being limited to `<bin dir>/../lib<LIB_SUFFIX specified in CMake command line>` or trying to guess distro-specific paths => easy-peasy for distros and users.
~~This isn't implemented yet.~~ **Edit**: It is now.
=> Config file: Add `lib-dirs` array

.circleci/config.yml, driver/ldmd.cpp, driver/toobj.cpp, driver/tool.cpp, gen/passes/GarbageCollect2Stack.cpp, gen/passes/SimplifyDRuntimeCalls.cpp, gen/passes/StripExternals.cpp, gen/tollvm.cpp, runtime/CMakeLists.txt, utils/not.cpp
Tested with current LLVM branch `release_70` on Ubuntu x86_64. Builds fine; default libs too except for an assertion when compiling druntime's `ldc.arrayinit` (not sure if that's related or simply untested by CI):
```
ldc2: /home/martin/llvm/include/llvm/Support/Casting.h:255: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = llvm::Function; Y = llvm::Constant; typename llvm::cast_retty<X, Y*>::ret_type = llvm::Function*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
#8 0x00005597f2cb2c5a (bin/ldc2+0x215fc5a)
#9 0x00005597f2cba9b7 llvm::IRBuilderBase::CreateMemCpy(llvm::Value*, unsigned int, llvm::Value*, unsigned int, llvm::Value*, bool, llvm::MDNode*, llvm::MDNode*, llvm::MDNode*, llvm::MDNode*) (bin/ldc2+0x21679b7)
#10 …
```
=> [ltsmaster] Backport LLVM 7 adaptations

gen/classes.cpp
~~dlang/dmd#8533 +~~ LDC-specific fix.
=> Posix: Fix C++ class construction with D `new`

.travis.yml, dmd/root/rmem.h
With August, they changed the default OSX image from xcode v8.3 to v9.4.1, and that's apparently when the druntime-test-shared failure was introduced for Travis OSX:
```
Testing finalize
/Users/travis/build/ldc-developers/ldc/runtime/druntime-test-shared/finalize
Illegal instruction: 4
```
CircleCI OSX is using xcode v9.2 without issues.
=> Travis OSX: Downgrade to xcode v9.2

dmd/root/port.d, dmd/root/port.h
Btw, DMD v2.082.0 final has been tagged (unchanged from RC1, i.e., master is up-to-date).
=> Remove obsolete LDC-specifc Port::stricmp()

ldc2.conf.in, ldc2_install.conf.in, ldc2_phobos.conf.in
And clear `-defaultlib` explicitly, as there's no druntime/Phobos for linking. The linker will thus complain about missing symbols instead of not finding the lib files when trying to link without `-betterC`, which should give a better overview of what's actually required.
=> Config file: Adapt wasm section to lib-dirs

shippable.yml
[Needs to be on the official repo for secure env variable...]
=> Shippable: Fix GitHub release name for tagged builds

dmd/template.h
Upstream, the print method has been removed already, so this is a temporary fix for LDC 1.12 only.
=> Fix hidden overloaded virtual function 'RootObject::print' warning (NFC)

appveyor.yml
ldc-jit.dll is already there. libcurl.dll was only copied to the bin dir, so that dub.exe, ldc-build-runtime.exe etc. work out of the box and user-built executables find it too if the LDC bin dir happens to be in PATH.
This leads to the multilib package now including a 32-bit libcurl.dll for the sake of completeness (in the lib32 dir).
=> AppVeyor: Include extra copy of libcurl.dll in lib directory

driver/main.cpp
When a reproducible build is wanted,
we should not add the build CPU type to man pages like ldmd2.1
See https://reproducible-builds.org/ for why this is matters.
The specification for SOURCE_DATE_EPOCH is at
https://reproducible-builds.org/specs/source-date-epoch/
and everyone doing reproducible builds, sets it.
=> Omit CPU type from man page

gen/toir.cpp, tests/codegen/gh2865.d, tests/compilable/gh2865.d
Functions, labels etc. aren't sized; respect that when coming across a `SymOffExp` (and checking whether we can elide a pointer cast to `i8*` for the GEP).
=> Fix issue #2865

driver/linker-gcc.cpp, gen/modules.cpp, tests/codegen/llvm_used_1.d
* The explicit reference to the ModuleInfo should be obsolete, it's added to the `llvm.used` array.
* Only keep a single pair of `ldc.dso_{c,d}tor` per DSO (pointing to a common `ldc.register_dso()` function) instead of a pair per linked-in D object file. This simplifies `ldc.register_dso()` and allows to get rid of the explicit ctor/dtor functions and the `ldc.dso_initialized` global.
=> Simplify DSO registration with druntime

gen/declarations.cpp, gen/dibuilder.cpp, gen/dibuilder.h, gen/functions.cpp, gen/modules.cpp, gen/statements.cpp, ir/iraggr.h, ir/irclass.cpp, ir/irmodule.h, ir/irtypeaggr.h, tests/debuginfo/args_cdb.d, tests/debuginfo/baseclass_cdb.d, tests/debuginfo/basictypes_cdb.d, tests/debuginfo/inputs/import_a.d, tests/debuginfo/inputs/import_b.d, tests/debuginfo/nested.d, tests/debuginfo/nested_gdb.d, tests/debuginfo/print_gdb.d, tests/debuginfo/strings_cdb.d, tests/lit.site.cfg.in
These commits bring LDC closer to GDC's DWARF output and Clang's IR output (regarding static variables and `this` parameters), and enables access to global/imported symbols and function calls (previously only non-member function calls worked, but only with the mangled name):
https://github.com/ldc-developers/ldc/blob/3d9aebc6677474261cc086dc8ee0bc154ce78a65/tests/debuginfo/print_gdb.d
Until recently I wrongly assumed that GDB's D support was incomplete and that calling functions with `print` or `call` wasn't implemented, then I tried GDC and it worked perfectly, @ibuclaw did an awesome job.
I don't know how this PR affects PDB/CodeView output. Last year symbol names got fully qualified: https://github.com/ldc-developers/ldc/pull/2362/commits/6e7249c5744c768bab9332505d6f6d7963ce3cb9 but …
=> Debug info improvements (for GDB): printing global and imported symbols, non-member and member function calls

appveyor.yml, driver/linker-msvc.cpp, driver/linker.cpp, driver/linker.h, packaging/README.txt, tests/lit.site.cfg.in
When experimenting with the MinGW-w64 based libs, there was a problem (well, one of many!) - an undefined reference to function `_(_)chkstk`, emitted by LLVM for stack probing (e.g., after an `alloca`) and not provided by MinGW-w64.
Initially, I used the symbol exported by ntdll.dll; normal user apps aren't supposed to depend on that system DLL though, and it also led to duplicate symbols for 32-bit code.
After some digging, I found that LLVM's builtins compiler-rt library contains 2 implementations (1 MS-compatible, 1 for MinGW/Cygwin, both with different names than the MS one). Our library didn't contain it though, so I digged deeper.
I found the culprit in the builtins CMake script; when using an MSVC toolchain, the builtins lib on Windows only contains very few C files and none of the …
=> Windows: Make LDC package fully self-sufficient (get rid of MSVC dependency)

tests/codegen/array_equals_memcmp.d
`memcmp` on small memory ranges is not optimized-out on `-O0` for AArch64, so turn optimization on. This fixes the test on AArch64.
=> Set -O3 in array_equals_memcmp assembly test

CMakeLists.txt, dmd/argtypes.d, dmd/argtypes_sysv_x64.d, dmd/dstruct.d, dmd/target.d, gen/abi-generic.h, gen/abi-x86-64.cpp, gen/target.cpp
The upstream implementation (`dmd/argtypes.d`) is... incomplete, to put it nicely; there's a number of DMD issues about it. I felt kinda bad when dropping our previous implementation (a few years ago), which was definitely more correct. This is an attempt to revive it, reimplemented from scratch using [this spec](https://www.uclibc.org/docs/psABI-x86_64.pdf), and tries to stay close to the algorithm laid out in the spec.
=> Implement SysV x64 ABI properly

driver/targetmachine.cpp
AArch64 only supports `.init_array`, for example. The reason this wasn't discovered earlier is that BFD and gold linkers automatically convert `.ctors` to `.init_array` as a performance optimization.
Based on clang code: https://github.com/llvm-mirror/clang/blob/5897428cd24e2deefbcc6f6744c0d7d233aa6747/lib/Driver/ToolChains/Gnu.cpp#L2598-L2620
https://github.com/ldc-developers/druntime/pull/146
=> [ltsmaster] Emit constructors as .init_array instead of .ctors when appropriate

driver/targetmachine.cpp, tests/codegen/ctor_initarray_gh2883.d
AArch64 only supports .init_array, for example. The reason this wasn't discovered
earlier is that BFD and gold linkers automatically convert .ctors to .init_array
as a performance optimization.
Cherry-pick from issue #2883
=> Cherry-pick: Emit constructors as .init_array instead of .ctors when appropriate (#2883)

dmd/cppmangle.d, dmd/target.d, driver/linker-gcc.cpp, gen/target.cpp
Android/x64 mostly works, but has some issues because of their unusual choice of having `long double` be a `__float128`, likely to match AArch64.
I'm getting this up early to get feedback. There's also two issues with Phobos I'll look into: [`std.math.copysign` won't compile with `llvm_copysign` on both x86 and x64](https://github.com/joakim-noah/termux-packages/blob/beta/packages/ldc-beta/ldc-phobos-x64.patch#L53) and many of the `std.variant` tests segfault on x64.
Otherwise, only a few tests fail, mostly the same ones as on AArch64 because of a couple trailing bits or missing IEEE Quadruple support:
```
diff --git a/std/complex.d b/std/complex.d
index eef57f864..8a90a98ce 100644
--- a/std/complex.d
+++ b/std/complex.d
@@ -939,7 +939,7 @@ deprecated
}
else
{
-        assert(z1.re == …
```
=> Various tweaks for Android, plus an Alpine fix

tests/codegen/inlineIR_math.d, tests/codegen/inline_ir.d, tests/codegen/inputs/input_discard_valuename.d
Inline IR is more generally applicable than SIMD, so it is out-of-place in `ldc.simd`. Because it is so similar in functionality to `__asm` and LLVM IR is called LLVM assembly, I think `__ir` fits better and should be in `ldc.llvmasm`. I've also added `*_trusted` variants similar to `__asm_trusted`.
For backwards compatibility, `ldc.simd.inlineIR` is still there (forwards to `ldc.llvmasm.__ir_trusted`.
=> Add __ir to ldc.llvmasm, to replace ldc.simd.inlineIR.

gen/dibuilder.cpp, tests/debuginfo/scopes_cdb.d
The test is Windows-only, but tests more than just compilability.
=> Fix issue #2937 (DI scope for types in static foreach in mixin templates)

CMakeLists.txt
See https://github.com/llvm-mirror/llvm/blob/b7c3be51e432282289d9ef2a350ad3e954032754/cmake/modules/HandleLLVMOptions.cmake#L222-L226
See https://github.com/avast-tl/retdec/pull/349/files
=> Fix linker warnings on macOS.

.travis.yml, CMakeLists.txt, driver/toobj.cpp, gen/functions.cpp, tests/codegen/dcompute_cl_addrspaces.d, tests/lit.site.cfg.in
For use with https://github.com/KhronosGroup/SPIRV-LLVM-Translator now that I finally managed to get around to wrangling CMake, after breaking my backend upgrading LLVM. 
I'll add a release for OSX soon for testing, but this is something we can potentially do for LDC releases when we ship with LLVM7.
=> Adapt to using SPIR-V support as an external library

dmd/cppmanglewin.d, tests/codegen/mangling_real_real.d
Cherry-pick from #2953 (Posix mangling fix already in 2.084 upstream => master):
Mangle as native Visual C++ long double. DMD has to special-case, as it's using 80-bit extended precision.
=> Fix C++ mangling of `real` for MSVC targets

gen/nested.cpp, tests/codegen/nested_gh2960.d
The context for instances of aggregates *not* nested in the current function, but some parent. Fixes #2960.
=> Fix context of some nested aggregates

.travis.yml
This only *appeared* to work, as long as the official prebuilt 7.0.1 archive wasn't available for download (I guess). The 'successful' [job](https://travis-ci.org/ldc-developers/ldc/jobs/471620842) in #2955 used a preinstalled LLVM 5.0.0 (`/usr/local/clang-5.0.0`).
=> Travis: Disable Linux LLVM 7.0.1 job (C++ compiler ABI mismatch?)

gen/functions.cpp
(I thought we used to get warnings for this on macOS, but no longer...?)
=> Fix glaring mistake in #2983

tests/codegen/attr_weak_external.d, tests/codegen/attr_weak_lto.d, tests/codegen/inputs/attr_weak_external_input.d
This is useful for optionally linking with libraries. (if not linked with the function, the function address is set to `null` by the linker).
I don't know whether it works on Windows. On macOS, it's somewhat problematic because it requires telling the linker to accept such undefined references. With ELF, it should work fine.
The difference between platforms make this less useful, but it is not much trouble to support the usecase.
=> @weak on definitions should not result in extern_weak linkage on declarations

gen/dvalue.cpp, gen/dvalue.h, tests/compilable/gh2996.d
As they may be extracted earlier in an unrelated basic block.
Fixes #2996.
=> DSliceValue: Don't cache *extracted* length & ptr

dmd/expression.d, dmd/expression.h, gen/irstate.cpp, gen/irstate.h, gen/toconstelem.cpp
Fixes #2990.
I don't have a reduced testcase.
=> Cache struct literal constants per compilation unit, not globally

gen/tocall.cpp, tests/compilable/gh2988.d
=> Account for front-end implicitly casting vector return values to static arrays

.travis.yml, dmd/mars.d, dmd/root/filename.d, dmd/root/rmem.d, dmd/root/rmem.h, driver/configfile.cpp, driver/configfile.d, driver/configfile.h, driver/main.cpp, driver/main.d, gen/asm-x86.h, ir/irfuncty.cpp, ir/irfuncty.h
This isn't looking too bad, although druntime cannot be compiled yet:
Phobos all-at-once compilation, Win64:
```
GC: used bytes = 1707268112
GC: used bytes = 570342720 [after collection]
```
`std.string` unittests:
```
GC: used bytes = 1651332656
GC: used bytes = 361209920
```
`std.algorithm.iteration` unittests:
```
GC: used bytes = 1496288448
GC: used bytes = 644807264
```
`std.regex.internal.tests` unittests:
```
GC: used bytes = 2079689120
GC: used bytes = 292884624
```
It doesn't reduce the peak memory requirements (well, maybe a little bit if LLVM allocates significant amounts during codegen), but reduces the time that memory is claimed, which should especially pay off with `-O`, as much more time will be spent in the LLVM optimizer. This might enable the usage of more CPU cores …
=> Optionally enable GC for front-end

gen/function-inlining.cpp, tests/codegen/inlining_imports_pragma.d, tests/codegen/inlining_stdlib.d
At -O0 already, tackling #2552.
`pragma(inline, true);` *statements* (now?) seem to require semantic analysis, so I adapted LDC-specifics in druntime/Phobos to decorate the function declaration directly - `tests/codegen/inlining_stdlib.d` failed without adaptation (to inline non-templated `core.bitop.bsf()`).
=> Re-enable cross-module-inlining for `pragma(inline, true)`

.travis.yml
The prebuilt 1.15.0-beta1 package (built on Ubuntu 16.04) doesn't work on Ubuntu 14.04, e.g.:
```
/usr/bin/ld.gold: error: /home/travis/dlang/ldc-1.15.0-beta1/bin/../lib/libphobos2-ldc.a(deflate.c.o): unsupported reloc 42 against global symbol _length_code
```
Considering Trusty reaches EOL next month, upgrade to Xenial.
=> Travis: Upgrade to Ubuntu 16.04

driver/linker-msvc.cpp
For `-betterC` convenience, as they are usually already pulled in by druntime. Resolves #3035.
=> MSVC: Add {oldnames,legacy_stdio_definitions}.lib to default C libs

.travis.yml
That job is frequently timing out. The implicit `-O0` for LDC's C++ parts (excl. LLVM) certainly don't help, and the coverage data hasn't been used for years (issue #1751).
=> Travis: Don't build with coverage instrumentation

driver/archiver.cpp
LDC currently silently ignores all passed lib files when linking for a static library, but dmd doesn't.
Current proposal makes LDC match DMD's behavior and link the libraries together.
=> Add lib files when linking for a static library

azure-pipelines.yml
By instructing the C(++) compiler not to emit relax relocations for the default libs, so that older binutils can be used to link against them.
Resolves #3020.
[I'll verify manually whether it actually works.]
=> Azure CI: Make prebuilt Linux package usable on Ubuntu 14.04 again

dmd/dsymbolsem.d, dmd/id.d, dmd/mtype.d, dmd/mtype.h, gen/declarations.cpp, gen/semantic-dcompute.cpp, tests/codegen/dcompute_cl_addrspaces.d, tests/codegen/dcompute_cu_addrspaces.d, tests/compilable/dcompute.d
This is not a perfect solution, as other modules might be relying on an emission (template culling...), but should work in most cases (and otherwise probably yields a linker error).
It'd have been a shame to ship with a totally broken dcompute for the first official LDC packages able to emit OpenCL (v1.15), so I reluctantly took matters in my own hands.
=> Don't emit object.RTInfo(Impl) instantiations in dcompute modules

driver/targetmachine.cpp
Looks like that regression has been fixed for LLVM 8.
=> Only default to SSSE3 (with -O) for LLVM 7.x

vcbuild/msvcEnv.bat
The installation path cannot be found in the registry anymore.
So try to detect it with the approach detailed in https://github.com/Microsoft/vswhere/wiki/Find-VC#batch.
=> Auto-detect Visual Studio 2019+

gen/arrays.cpp, tests/codegen/array_alloc_gh3041.d
For better optimizability, as the length information is lost when using the slice returned by the druntime hooks directly. Resolves #3041.
=> Propagate well-known length of newly allocated arrays

gen/abi-generic.h, gen/abi-ppc.cpp, gen/abi-ppc64le.cpp, gen/abi-x86-64.cpp, gen/abi-x86.cpp, gen/attributes.cpp, gen/attributes.h, gen/functions.cpp, gen/tocall.cpp, gen/tollvm.cpp, gen/tollvm.h, gen/uda.cpp, ir/irfuncty.cpp, ir/irfuncty.h, tests/codegen/attr_param.d
E.g., finally enabling `restrict` C(++) semantics.
=> Support generic ldc.attributes.llvmAttr UDAs for function parameters

gen/dynamiccompile.cpp, runtime/jit-rt/cpp-so/compile.cpp, runtime/jit-rt/cpp-so/jit_context.cpp, runtime/jit-rt/cpp-so/jit_context.h, tests/dynamiccompile/array.d
Compiler need to build a list of functions jit can call back to static code. This is done via analyzing jitted IR but some special functions require special handling as they are not present in IR but reference to them can still be generated.
=> Jit: better error handling and handle correctly __chkstk function

.azure-pipelines/posix.yml
Seems like MS chose a weird `umask 0000`...
=> Azure CI: Tweak ownership & permissions of tarballs

gen/naked.cpp
Using clang 8.0.0 as reference. This should silence the warnings in issue #3066, see https://reviews.llvm.org/rG1cea644114e367c7ed3a4ea3d2da571ec3ed56f7 (from 2015) for some context wrt. that.
=> Revise naked asm headers

runtime/CMakeLists.txt, tests/baremetal/wasm2.d
This fixes issue #3023 and restores the behavior of previous LLD versions (of exporting/not stripping all symbols with default/public visibility).
=> WebAssembly: Use --export-dynamic when linking with LLD 8+

gen/llvmhelpers.cpp, tests/fail_compilation/global_var_collision.d
=> Improve error msg on global var collision

dmd/expression.d, dmd/expression.h, driver/main.cpp, gen/target.cpp, tests/semantic/target_traits_dcompute.d
and __traits(getTargetInfo, "dcomputeFilePrefix”. Also fixes a segfault
when passing `-mdcompute-targets=whatever` and no compute modules were
passed to ldc. The test doubles for that fix as well.
From the correct branch this time!
=> add __traits(getTargetInfo, "dcomputeTargets")

.travis.yml, driver/codegenerator.cpp
This enables support for builing LDC with LLVM 3.5 again.
=> [ltsmaster] Fix building with LLVM 3.5.

gen/statements.cpp, tests/codegen/gh3094.d
Fixes #3094, a regression introduced in v1.16 due to AST changes.
=> Fix ICE when returning a void expression

gen/abi-win64.cpp, gen/abi-x86.cpp, gen/abi.cpp, gen/abi.h
Which have been superseded by magic enums (in `core.stdc.config`).
=> Refactoring: Free TargetABI from legacy magic C++ structs

README.md
Running 'choco ldc' gives me
```bash
$ choco ldc
Chocolatey v0.10.15
Could not find a command registered that meets 'ldc'.
Try choco -? for command reference/help.
```
It should be `choco install package-name`
=> update chocolatey install instructions

driver/linker-gcc.cpp
LLD supports plugin-style flags, but the plugin itself might not exist. (`getLTOGoldPluginPath` might fail)
(on FreeBSD, it exists in an LLVM-version-specific place like `/usr/local/llvm80/lib/LLVMgold.so`. that should probably be added as well, the plugin is just not required for LLD. LLD is the primary linker here, `/usr/bin/ld` is LLD on aarch64 and amd64.)
=> Do not require gold plugin when linking with LLD

driver/main.d
An issue since eliminating the previous D `main()` functions in LDC v1.15.
Should work according to https://forum.dlang.org/post/caqgnbgynlqdrnomtzfq@forum.dlang.org.
=> Speculatively fix linkability of LDC and LDMD on Android

.azure-pipelines/windows.yml
Now that Rainer figured out why anything newer than v7.48.0 wouldn't work (hanging `std.net.curl` unittests) in dlang/installer#399.
I built the binaries on my box using VS 2019 v16.2.2.
zlib v1.2.11 was built using `contrib/vstudio/vc14/zlibvc.sln` (static release lib incl. asm, which needs to be built separately, e.g., `cd contrib/masmx64 && bld_ml64.bat`). MSCRT was set to `/MT`.
libcurl was built with a command line like this in the `winbuild` dir:
> nmake /f Makefile.vc mode=dll VC=15 WITH_DEVEL=C:\LDC\curl-7.65.3\deps WITH_ZLIB=static GEN_PDB=no DEBUG=no MACHINE=x64 RTLIBCFG=static
The CFLAGS in `winbuild/MakefileBuild.vc` need to be extended by `/DDONT_USE_RECV_BEFORE_SEND_WORKAROUND` to fix the hanging tests.
=> Azure CI Windows: Upgrade bundled libcurl to v7.65.3

gen/declarations.cpp, gen/llvmhelpers.cpp, gen/llvmhelpers.h, gen/tollvm.cpp, gen/tollvm.h, gen/typinf.cpp, tests/codegen/export_aggregate_symbols.d, tests/codegen/export_marked_symbols1.d, tests/codegen/export_marked_symbols2.d, tests/codegen/export_marked_symbols_thin_lto.d
=> -fvisibility=hidden: Hide init symbols, TypeInfos and vtables too if the associated aggregate isn't exported

driver/linker-gcc.cpp, driver/targetmachine.cpp
(Requires #3105 for `isLldDefaultLinker`)
The ancient ld.bfd doesn't like this:
```
.dub/obj/dtest.o: In function `ldc.register_dso':
app.d:(.text.ldc.register_dso+0x1c): undefined reference to `__stop___minfo'
app.d:(.text.ldc.register_dso+0x28): undefined reference to `__start___minfo'
/usr/bin/ld.bfd: .dub/build/application-release-posix.freebsd-x86_64-ldc_2086-54657107D68790E5698D25167B20AC6A/dtest: hidden symbol `__start___minfo' isn't defined
/usr/bin/ld.bfd: final link failed: Nonrepresentable section on output
```
(miiight be the same bug that's mentioned in the context of PGO on Linux)
but other linkers are of course fine, so let's just enable it when we know BFD is not used. (Eventually it won't be used by default at all: as of FreeBSD 12, LLD is default on amd64 and aarch64 …
=>  Enable gc-sections on FreeBSD when not using old ld.bfd linker

gen/arrays.cpp, gen/binops.cpp, gen/classes.cpp, gen/complex.cpp, gen/functions.cpp, gen/llvmhelpers.cpp, gen/naked.cpp, gen/nested.cpp, gen/statements.cpp, gen/tocall.cpp, gen/toconstelem.cpp, gen/toir.cpp, gen/tollvm.cpp, gen/tollvm.h, ir/irclass.cpp, tests/codegen/inbounds.d
Issue: https://github.com/ldc-developers/ldc/issues/392
I don't get the reasoning behind how arrays are handled currently so I didn't change them.
For static arrays and constant index, the generated IR is the expected. i.e. if it's in bounds, then `GEP inbounds` is generated, otherwise compile-time error.
If though say we have a static array and the index is not known (in which case bounds-checking code is generated) e.g.
```
int foo(int[3] a, int i)
{
return a[i];
}
```
then `inbounds` is _not_ generated for the `bounds.ok` BB. I could "just" change that, but [in the code](https://github.com/baziotis/ldc/blob/73e6f4442744603c55128d8e5ab35667e3d52768/gen/toir.cpp#L1094), it seems as if someone has thought about it (i.e. there is not just a `true` or a `false`).
However, the way I think of …
=> Add inbounds where possible

CMakeLists.txt
This enables skipping the auto-detection of the gcc/clang flags used by the host D compiler for linking, by specifying the desired flags in the CMake command line. Simplifies the Termux package generation for Android. [Where we use `-DD_LINKER_ARGS='-fuse-ld=bfd;-Lldc-build-runtime.tmp/lib;-lphobos2-ldc;-ldruntime-ldc;-Wl,--gc-sections'`, to prepare for linking against the still-to-be-cross-compiled druntime/Phobos libs].
=> CMake: Enable manual D_LINKER_ARGS input (for cross-compilation)

driver/cl_options.cpp, driver/linker.cpp
So that nobody asks the #3168 question again.
=> Disambiguate that -link-defaultlib-shared can take a parameter

.travis.yml
It doesn't seem to slow down the runtime so let's enable the testing in more places.
=> [Travis] Enable runtime sanitizer testing for Linux LLVM 9 and macOS LLVM 8 CI testers

.azure-pipelines/posix.yml, ldc2.conf.in, ldc2_phobos.conf.in, runtime/CMakeLists.txt, tests/compilable/gh3194.d
=> Make gccbuiltins_*.di files available to non-installed compiler

.azure-pipelines/posix.yml, .circleci/config.yml, azure-pipelines.yml
As our previous macOS image has been phased out, and we'd have to downgrade to the `xcode-9.0.1` image if we wanted to stick with macOS 10.12. `xcode-11.1.0` is the newest image and comes with macOS 10.14, so we'll probably hit issue #3002.
https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions
=> CircleCI: Bump the macOS image as well as host LDC & LLVM versions

gen/abi-x86-64.cpp, gen/abi-x86.cpp, gen/toir.cpp, tests/codegen/in_place_construct_temporaries.d
Streamlining the D ABI with the C++ one and preventing extra blits for rvalue arguments. Non-POD arguments passed by value aren't blitted into the callee params stack any longer, but passed by reference, either directly (rvalue args) or as reference to a bitcopy on the caller stack (lvalue args).
This is also a prerequisite for a potential DIP1014 (opPostMove) implementation, as LLVM (via its `byval` attribute) has been performing the move/blit implicitly as part of the call, with no way for us to invoke the post-move hook afterwards in the callee with the address of the original argument.
=> Posix x86[_64]: Pass non-POD arguments indirectly by value, not just for extern(C++), and get rid of extra blits for temporaries

gen/toir.cpp
See https://issues.dlang.org/show_bug.cgi?id=20401; a testcase will be added with https://github.com/dlang/dmd/pull/10577.
It's a pretty serious issue (the previously returned reference in the testcase was a dangling reference to a local memcopy of the original value in memory), hence this early fix.
=> Fix DMD issue 20401

.azure-pipelines/windows.yml, CMakeLists.txt, azure-pipelines.yml
We use clang 9 as C++ compiler and the non-LTO'd bootstrap compiler is linked against matching LLVM 9, so everything's set up for LLVM 9 LTO already.
So when building the 2nd, final compiler:
* let clang compile the C++ parts of the ldc2 executable as LTO objects (the LDC parts, i.e., excluding LLVM libs)
* use the bootstrap LDC for archiving the static LDCShared library (as it only contains the C++ LTO objects)
* let the bootstrap compiler produce LTO objects only (for all D executables, not just ldc2)
* let the bootstrap compiler link all D executables with LTO, incl. LTO-able druntime & Phobos (via `lld-link` v9)
=> Azure CI Windows: Build LDC itself with LTO

.azure-pipelines/windows.yml
See https://github.com/ldc-developers/mingw-w64-libs/releases/tag/v7.0.0-rc.1. Fixes #3142 (tested manually) and #3212.
The druntime and Phobos test runners can still be linked and run successfully (manually, via `-link-internally -mscrtlib=vcruntime140 -L/LIBPATH:path\to\libs`), on both Win32 and Win64.
=> Windows: Upgrade bundled MinGW-based libs to v7.0.0 RC1

gen/abi-x86-64.cpp, tests/compilable/gh3250.d
=> Fix #3250: use `originalLType->isAggregateType()` in assertion

driver/codegenerator.cpp
I think we can remove the copy-relocation logic since https://github.com/ldc-developers/druntime/commit/9b97ede74f9b8840c77d7a35aaf573ace012c1d0 was comitted.
=> Remove _d_execBss{Beg,End}Addr, used for copy-relocation check

gen/irstate.h
Since C++11, [depr.impldec] says:
> The implicit definition of a copy constructor as defaulted is deprecated
> if the class has a user-declared copy assignment operator or a
> user-declared destructor.
clang 10 will have a warning -Wdeprecated-copy (included by -Wextra)
which flags the code.
=> irstate.h: fix -Wdeprecated-copy

gen/functions.cpp, tests/codegen/attr_targetoptions.d, tests/codegen/frame_pointer_x86.d
LLVM 8 ([D56351](http://reviews.llvm.org/D56351)) introduced "frame-pointer" which was intended to replace
"no-frame-pointer-elim"/"no-frame-pointer-elim-non-leaf".
-----
In the LLVM monorepo, run `git show origin/release/8.x:llvm/lib/CodeGen/TargetOptionsImpl.cpp` to see the effect of `"frame-pointer"`.
=> Use function attribute "frame-pointer" instead of "no-frame-pointer-elim"/"no-frame-pointer-elim-non-leaf"

gen/dibuilder.cpp
------
#3257 added the argument to the wrong place. https://reviews.llvm.org/D71818 added `bool isDefined`.
=> dibuilder: fix createGlobalVariableExpression call for LLVM 10

dmd/dsymbolsem.d, driver/codegenerator.cpp, gen/declarations.cpp, gen/irstate.cpp, gen/irstate.h, gen/naked.cpp, tests/codegen/linker_directives_linux.d, tests/codegen/linker_directives_mac.d, tests/codegen/linker_directives_win.d
Resolves #3245 by adding `pragma(lib, <name>)` library names to `llvm.dependent-libraries` for ELF object files.
For Mach-O, embed appropriate linker options for `pragma(lib)` and support generic `pragma(linkerDirective, <flag>, ...)` as well.
=> Embed linker directives in ELF and Mach-O object files

driver/linker-msvc.cpp
Fixes an annoyance reported in #3281, affecting non-LLD-enabled builds as well as linker invocations involving LTO.
=> Fix default cross-linker for MSVC targets on non-Windows hosts

cmake/Modules/FindLLVM.cmake
Debian moved to minor-versioness llvm-config-7 instead of llvm-config-7.0, same for 8 and 9 (and in the future 10)
This fixes the build when a non-default llvm-config is used to build
=> Update FindLLVM.cmake to cope with new llvm-config names

.azure-pipelines/posix.yml, .azure-pipelines/windows.yml, .travis.yml, driver/main.cpp, driver/targetmachine.cpp, shippable.yml, tests/d2/CMakeLists.txt
On my machine with 4 cores, this reduces the total dmd-testsuite runtime by 20% for a release build with enabled assertions.
=> dmd-testsuite: Tweak d_do_test runner to skip some uninteresting permutations & switch from Makefile to run.d

driver/main.cpp, gen/abi-aarch64.cpp, gen/modules.cpp, gen/target.cpp, ir/irtype.cpp
I've only tested this on a 64 bit iPhone running iOS 12. 32 bit is obsolete and I don't have access to the other platforms. All unit tests in druntime pass and most in Phobos.
I'm not sure about the correct workflow here but I created PRs for the druntime and Phobos changes to upstream those. I assume those will get pulled in next time LDC updates to the latest frontend version.
There are one or two changes in druntime that should not be upstreamed. How should those be handled?
druntime PR: https://github.com/dlang/druntime/pull/2910.
Phobos PR: https://github.com/dlang/phobos/pull/7355.
=> Add support for iOS, tvOS and watchOS

.azure-pipelines/windows.yml
They now support wide C `wmain` and `wWinMain` entry points, see dlang/installer#427.
=> Windows: Bump bundled MinGW-based libs to v7.0.0 final

dmd/dimport.d, dmd/dmodule.d, dmd/expressionsem.d, dmd/module.h
=> Merge upstream stable (e274c8cbcc)

ir/irclass.cpp, shippable.yml, tests/codegen/sret_thunk_gh3329.d
This apparently isn't required for x86, but makes all the difference for AArch64 and fixes #3329. I hope for other archs too!
=> Fix tail calls in thunks by applying the callee function attributes to the call instruction

LICENSE
LLVM 9 or later is released under the terms of the Apache License v2.0 with LLVM exceptions.  This patch updates the `LICENSE` file to reflect this change.  Full texts are included for both new and legacy licenses, matching what is found in the upstream LLVM `LICENSE` file.
=> Update LLVM license to Apache 2.0

gen/modules.cpp, tests/baremetal/lit.local.cfg, tests/codegen/wasi.d, tests/lit.site.cfg.in
As LLD [**edit**: 9+] supports the magic `__{start,stop}___minfo` linker symbols for wasm targets.
=> WebAssembly: Switch from legacy linked-list ModuleInfo registry to __minfo section

.azure-pipelines/posix.yml, driver/codegenerator.cpp
This should resolve #3350 and also gets rid of the previous Android-specific requirement wrt. having a D main *and* making sure that object file is the first one fed to the linker.
=> Revamp rt.sections_android, getting rid of some magic symbols

.azure-pipelines/windows.yml
Build steps:
- Static zlib reused from previous 7.65.3 build, see #3135.
Includes and libs copied to `C:\LDC\curl-7.69.1\deps[_x86]`.
- Patch winbuild\MakefileBuild.vc:
- Extend CFLAGS by `/DDONT_USE_RECV_BEFORE_SEND_WORKAROUND`.
- Extend CFLAGS_LIBCURL_STATIC by `/GS- /Zl` (for MinGW-based libs compatibility...).
- Build DLL + import lib + .exp file:
`nmake /f Makefile.vc mode=dll VC=15 WITH_DEVEL=C:\LDC\curl-7.69.1\deps[_x86] WITH_ZLIB=static GEN_PDB=no DEBUG=no MACHINE=x{64,86} RTLIBCFG=static`
- Build static lib:
`nmake /f Makefile.vc mode=static VC=15 WITH_DEVEL=C:\LDC\curl-7.69.1\deps[_x86] WITH_ZLIB=static GEN_PDB=no DEBUG=no MACHINE=x{64,86} RTLIBCFG=static`
- Strip `lib` prefix from `libcurl*.{lib,exp}` filenames.
=> Azure Windows: Upgrade bundled libcurl to v7.69.1 & include static lib + .exp file

driver/linker-gcc.cpp, driver/tool.cpp, tests/linking/linker_empty.d
This is needed for example when you want to use `lld` but `-fuse-ld=lld` is not supported by the C compiler yet. Manually symlinking `ld` to `ld.lld` and passing `-linker=` to LDC will work with this patch.
=> Give user possibility to avoid passing -fuse-ld to cc with `--linker=`.

.azure-pipelines/posix.yml
We only support static druntime & Phobos on Android for now (also limited by our TLS emulation). When building shared libs and linking the default libs statically, the public druntime/Phobos symbols aren't stripped by the linker (in contrast to building an executable), leading to large .so libs.
I've experimented with a `std.stdio`-hello-world for Android/AArch64. When using hidden visibility for the default libs, the .so size shrinks from 6.83 MB to 1.57 MB (-77%).
=> Azure Android: Build druntime & Phobos with -fvisibility=hidden, for reduced user .so size

gen/cl_helpers.h, gen/dibuilder.cpp, gen/dibuilder.h, tests/debuginfo/msvc_no_colinfo.d
Fixing #3102; see https://reviews.llvm.org/D23720.
=> Don't emit any column infos for CodeView by default, like clang

dmd/statementsem.d, dmd/target.d, dmd/target.h, driver/main.cpp, gen/target.cpp, tests/codegen/unknown_critical_section_size.d
Instead, error out whenever requested by an expression-less `synchronized` statement, including source LoC to track it down.
This is safer, especially since the previous initial warning may likely be suppressed, and makes this host-agnostic.
Also suppress previous warnings about unknown empty and `none` OS, treating these like `unknown`.
This is a follow-up on https://forum.dlang.org/post/agupeguvxftrucpjvpho@forum.dlang.org.
=> Do not fallback to host for critical section size of unknown targets

gen/arrays.cpp, tests/codegen/array_equals_memcmp_dyn.d
Fixes #3400. The frontend pre-casts the static array operand to the slice type for cases like `bool[4] == bool[]`, but that's not possible in case the static array is non-mutable but the slice type is mutable.
So check the element types for equivalence, not the array types, as static arrays and slices are NOT equivalent.
=> Try to use memcmp for (in)equality of non-mutable static arrays and mutable slices

utils/gen_gccbuiltins.cpp
Among which:
```D
pragma(LDC_intrinsic, "llvm.x86.avx512.pshuf.b.512")
byte64 __builtin_ia32_pshufb512(byte64, byte64) pure @safe;
```
and thus fixing #3405.
=>  gccbuiltins: Lift 256-bit vector limit, adding 174 builtins for x86 with LLVM 10

gen/abi-aarch64.cpp, gen/abi-generic.h, gen/abi-x86-64.cpp, gen/abi-x86.cpp, gen/abi.cpp, gen/abi.h, gen/asmstmt.cpp, gen/dcompute/abi-rewrites.h, gen/functions.cpp, gen/nested.cpp, shippable.yml
Cleaned-up version of #3393, rebased onto the upstreamed stuff.
=> Fix AArch64 ABI, based on front-end toArgTypes machinery

runtime/CMakeLists.txt
As it's useless for LDC *and* seems to trigger LLVM bugs for ARM soft-float targets, according to https://forum.dlang.org/post/ihddbsxxctlicxirwtjt@forum.dlang.org.
=> CMake: Exclude rt.memset from druntime

driver/main.cpp, gen/llvmhelpers.cpp, tests/codegen/avr.d
The AVR target on LLVM and AVR-GCC does not have support for TLS, so
it is necessary to emit global variables as NotThreadLocal.
Based on PR #3295
=> AVR: Add predefined version AVR and emit TLS globals as regular ones

gen/statements.cpp, tests/codegen/return_statement.d
Our version of https://issues.dlang.org/show_bug.cgi?id=20809.
=> Fix return statements: Don't access memory from destructed temporaries

runtime/CMakeLists.txt
This is sort of a reboot of #2556. @thewilsonator: The generated files are .di headers, do those really need any special dcompute handling?
=> gccbuiltins: Add AMD GCN and Nvidia PTX

gen/functions.cpp, gen/moduleinfo.cpp, gen/pgo_ASTbased.cpp, gen/rttibuilder.cpp, gen/tollvm.cpp, gen/tollvm.h, gen/typinf.cpp, ir/irclass.cpp, tests/PGO/irbased_indirect_calls.d, tests/codegen/attr_weak.d, tests/codegen/attributes.d, tests/codegen/inputs/attr_weak_input.d
The test adaptations are mostly a revert of 3893840f.
`@weak` global variables are still left out but could be emulated exactly the same way.
=> Emulate @weak functions on Windows and don't emit COMDATs for ELF anymore

gen/asm-gcc.cpp, gen/llvmhelpers.h, gen/naked.cpp, tests/codegen/asm_gcc.d, tests/fail_compilation/asm_gcc_indirect.d
I.e., use the expression's lvalue as operand for `"m"` memory inputs, like GDC. Previously, this was restricted to output operands (`"=m"`); input operands were still using the expression's rvalue (and so required an explicit address-of operator for variables).
=> GCC-style asm: Add support for indirect input operands

CMakeLists.txt, runtime/CMakeLists.txt, runtime/StandaloneDRuntimeTests.cmake
=> druntime: Include core.stdcpp.* modules

driver/cl_options.cpp, driver/cl_options.h, gen/functions.cpp, tests/codegen/noplt.d
This patch gives new option which avoids the PLT and lazy binding while
making external calls.
Implementation inspired by `-fno-plt` support to Clang.
Clang's patch: https://reviews.llvm.org/D39079
=> Add --fno-plt option to avoid PLT external calls

driver/targetmachine.cpp
Bitrig is now defunct OpenBSD fork. It released 1.0 in 2014 and hasn't had another release since.
I'm not sure if LDC officially supports it, just delete an occurence of bitrig from the source.
=> Remove bitrig support

dmd/semantic3.d, gen/abi-aarch64.cpp, gen/functions.cpp, gen/nested.cpp, tests/compilable/captured_nonpassed_params.d
Fixing the iOS regressions seen in #3379 after the rebase.
=> Fix ICE for *captured* parameters *not* passed on the LLVM level

bitrise.yml, runtime/.gitignore, runtime/TestRunnerTemplate/TestRunner.xcodeproj/project.pbxproj, runtime/TestRunnerTemplate/TestRunner.xcodeproj/project.xcworkspace/contents.xcworkspacedata, runtime/TestRunnerTemplate/TestRunner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, runtime/TestRunnerTemplate/TestRunner.xcodeproj/xcshareddata/xcschemes/TestRunner.xcscheme, runtime/TestRunnerTemplate/TestRunner/Base.lproj/Main.storyboard, runtime/TestRunnerTemplate/TestRunner/Info.plist, runtime/TestRunnerTemplate/TestRunner/main.m, runtime/TestRunnerTemplate/TestRunnerTests/Info.plist, runtime/TestRunnerTemplate/TestRunnerTests/TestRunnerTests.m, runtime/ldc-build-runtime.d.in
This setups up a CI pipeline for iOS to run on http://bitrise.io. It consists of a template for an Xcode project and a bitrise.yml file to configure the pipeline. When running `ldc-build-runtime`, the template will be used to create a real Xcode project. The Xcode project will run the unit tests for both druntime and Phobos.
This will run the unit tests on a real physical device on Bitrise.
For this review, the main interesting files would be:
* bitrise.yml
* runtime/TestRunnerTemplate/TestRunnerTests/TestRunnerTests.m
* runtime/ldc-build-runtime.d.in
For this to work, an account on Bitrise needs to be connected to this repository, an Apple developer account needs to be connected to the Bitrise account and the Bitrise workflow needs to be configured to use the bitrise.yml file.
Example of …
=> Add support for running iOS unit tests on Bitrise

bitrise.yml
The previous device has been removed from the CI service.
=> Update to run iOS device testing on iPhone 6S 12.0

dmd/builtin.d
On Win64 and its double-precision real, it seems to be roughly 14x faster than Microsoft's C `ldexp` on my box (i5-3550).
On Ubuntu 20.04, the speed-up is something like 9x, again for double precision. Double and single precision versions aren't enabled yet, but will be with LDC v1.23 (already available in upstream druntime master).
=> druntime: Adopt fast ldexp implementation from libmir

.cirrus.yml
As the `std.format` unittest failure (missing `-` sign when printing a negative `double` as hex string) smells like a CTFE issue and might be related to a buggy host druntime's `core.stdc.math.log2l`.
The previous host compiler was FreeBSD's LDC v1.14, possibly including unknown patches.
=> CirrusCI: Fix the last few FreeBSD failures

.azure-pipelines/posix.yml, driver/targetmachine.cpp
Hardcoded instead of pre-setting `ldc2.conf` for the prebuilt Android packages, and thus simplifying cross-compilation (e.g., issue #3437).
Also use `core2` instead of `x86-64` for Android x86_64.
=> Android: Default to cortex-a8 CPU for ARMv7-A

gen/function-inlining.cpp, gen/functions.cpp, gen/tollvm.cpp, tests/codegen/inlining_gh3126.d
Previously, the logic gave up early if semantic3 was run for the function to be inlined, either because the function is going to be codegen'd in some root module, or because sema3 was already run for an
`available_externally` 'copy' in a previous compilation unit. This restricted a function to being defined in at most one compilation unit per `ldc2` invocation.
So e.g. a little `pragma(inline, true)` wrapper in druntime wasn't inlined into other druntime modules, because the whole lib is built in a single cmdline by default, and sema3 was obviously run for the actual emission in the corresponding object file.
When later compiling Phobos in a single cmdline, only the first object file referencing the wrapper got lucky, running sema3 manually and getting an `available_externally` 'copy'.
=> Cross-module inlining: Enable emission into multiple object files

driver/tool.cpp
According to the gcc 10.1 cmdline docs.
=> Switch to a white list of archs wrt. -m32/-m64 in cc cmdlines

dmd/vsoptions.d
As that was the way to request MSVC auto-detection in v1.20 and older.
=> Windows hosts: Handle LDC_VSDIR set to non-existing path

gen/funcgenstate.cpp, tests/linking/betterc_cleanups.d
A reboot of #3480, fixing #3479 and related issues.
=> -betterC: Don't use unsupported EH for handling clean-ups

.azure-pipelines/posix.yml, bitrise.yml, driver/linker-gcc.cpp, driver/targetmachine.cpp, gen/abi-x86.cpp, gen/asm-x86.h, gen/naked.cpp
This fixes the issue reported in https://forum.dlang.org/thread/hgkramhteqhfxirigxpq@forum.dlang.org.
=> Fix naked DMD-style asm emission for non-Mac x86 Darwin targets & add prebuilt druntime/Phobos for iOS/x86_64 to macOS package

gen/typinf.cpp
Surfacing now as #3486 added a corresponding assertion.
I've tested this with an older vibe-d v0.8.6 lying around on my box.
The assertion was hit for the TypeInfo of a nested struct:
https://github.com/vibe-d/vibe.d/blob/3c7ae13989003b7ebc59de23c5b6a0fb0466f119/http/vibe/http/router.d#L570-L574
I wasn't able to quickly reduce it to a stand-alone testcase and am reluctant to put any more effort into this.
=> Fix issue #3501: Don't re-define struct TypeInfos

dmd/expression.h, gen/irstate.cpp, gen/irstate.h, gen/llvmhelpers.cpp, gen/llvmhelpers.h, gen/toconstelem.cpp, gen/toir.cpp, gen/tollvm.cpp
This doesn't include peekData() as described in https://github.com/ldc-developers/ldc/issues/3490 not sure about the process about updating the interface files, if it's fine I'll just add it into this PR.
=> Refactor toir visit(StringExp) to avoid un-necessary computations.

gen/classes.cpp, gen/dibuilder.cpp, gen/llvmhelpers.cpp, gen/rttibuilder.cpp, gen/toconstelem.cpp, gen/toir.cpp, ir/irclass.cpp, ir/irfunction.cpp, ir/irfunction.h, tests/compilable/gh3496.d
Whenever we need an IR function, we'd better make sure it exists. Handle that in `DtoCallee()`, by invoking `DtoDeclareFunction()` by default, instead of the previous `DtoResolveFunction()` + `DtoCallee()` combo.
`DtoResolveFunction()` usually declares the function, but somehow doesn't for abstract and body-less functions.
=> Fix issue #3496 - missing IR declarations for some fwd-declared functions

gen/statements.cpp, tests/PGO/final_switch_release.d
See GH issue #3375 (it fixes the instrumentation part of that bug on my machine, but apparently there are other bugs troubling PGO still).
This change includes checking of whether there is a default statement when using `case <variable>` (LLVM IR switch instruction cannot be used), although that is currently not allowed in the D language. Therefore there is no testcase that covers that.
=> Fix PGO instrumentation crash for final switch(enum) statements together with -release

gen/pgo_ASTbased.cpp, tests/PGO/hash_smallchange.d
See Clang PR: https://reviews.llvm.org/D79961
Note that we do not include versioning code for our PGO files: PGO files from older LDC versions are not guarantee to work with newer versions of LDC. The user will see warnings about different function hashes, so he is aware the profile is not applied for those functions. Hash clashes may occur (old version hash corresponding to different function newer version hash), which is unfortunate but I think we do not need to go to the length of solving that as it only concerns optimization, not miscompilation. (it is similar that we don't guarantee object files from older compiler to work with newer compiler due to potential ABI changes which may also be silent)
Thanks @jondegenhardt
=> Fix partial discarding of function hash info for PGO

gen/pgo_ASTbased.cpp, gen/statements.cpp, tests/PGO/unrolledloopstatement_gh3375.d
Also adds extra precautions to catch this problem earlier in the future.
Fixes issue #3375
=> Add missing `UnrolledLoopStatement` to PGO region count calculator. 

gen/classes.cpp, gen/classes.h, gen/toir.cpp
This works around #3526 (but makes sense in general IMO).
For that testcase, the v1.22 IR was:
```ll
%"(bar() , foo)().length@vtbl" = getelementptr inbounds [6 x i8*], [6 x i8*]* %4, i32 0, i32 5 ; [#uses = 1, type = i8**]
%5 = load i8*, i8** %"(bar() , foo)().length@vtbl", align 8 ; [#uses = 1]
%"(bar() , foo)().length" = bitcast i8* %5 to i64 (%current.Foo*)* ; [#uses = 1]
%6 = call x86_vectorcallcc i64 %"(bar() , foo)().length"(%current.Foo* nonnull %2) ; [#uses = 1]
```
Now it's:
```ll
%"length@vtbl" = getelementptr inbounds [6 x i8*], [6 x i8*]* %4, i32 0, i32 5 ; [#uses = 1, type = i8**]
%5 = load i8*, i8** %"length@vtbl", align 8     ; [#uses = 1]
%length = bitcast i8* %5 to i64 (%current.Foo*)* ; [#uses = 1]
%6 = call x86_vectorcallcc i64 %length(%current.Foo* nonnull %2) ; [#uses …
```
=> Simplify IR names of virtual function pointers

driver/cl_options.cpp, driver/cl_options.h, driver/linker.cpp, driver/main.cpp, gen/dibuilder.cpp, gen/dibuilder.h, tests/debuginfo/msvc_dwarf.d
=> Add `-gdwarf` CLI option to emit DWARF debuginfos for MSVC targets

driver/args.cpp, driver/args.h, driver/ldmd.cpp, driver/tool.cpp, driver/tool.h
Fixes #3535 and an issue for ldmd2 wrt. unquoted args containing spaces in response files for ldc2 (uncovered during manual tests). Also create the temporary response files in the temp directory, not in the current working dir.
=> Fix linker cmdline length limitation via response files

driver/linker-gcc.cpp, driver/linker-msvc.cpp, driver/linker.cpp, driver/linker.h, tests/linking/platformlib.d
Introduce -platformlib option to control libraries added automatically for Windows targets.
=> Fix for #3374

.azure-pipelines/posix.yml, azure-pipelines.yml
While the official prebuilt 10.0.0 version was for Ubuntu 18.04 only, v10.0.1 is for 16.04 only (...) and thus usable again for us.
While their apt repo has worked fine so far AFAIK, we've had pretty bad experiences with it in the past, so I definitely prefer a GitHub
download.
Oh and there are once again no prebuilt Windows packages for an LLVM/clang point release.
=> Azure CI: Bump host clang to v10.0.1 on Linux

.github/FUNDING.yml
I'd like to try this and see how it works out. I have to look for a new job, so it's a good time for such an experiment and can potentially affect the targeted weekly hours, reserving some time for LDC/dlang development & support.
This is my profile: https://github.com/sponsors/kinke
=> Add a GitHub Sponsors button

dmd/dmangle.d, dmd/dsymbolsem.d, dmd/escape.d, dmd/expressionsem.d
Just in case we 'need' a v1.23.1 point release with LLVM 11 support; merging fixes from upstream stable before the v2.094 switch probably won't hurt.
=> Merge upstream stable (dlang/dmd@f602545af9)

.azure-pipelines/windows.yml, tests/debuginfo/args_cdb.d, tests/debuginfo/baseclass_cdb.d, tests/debuginfo/basictypes_cdb.d, tests/debuginfo/nested_cdb.d, tests/debuginfo/scopes_cdb.d, tests/debuginfo/strings_cdb.d, tests/debuginfo/vector_cdb.d
Investigating the spurious failures showed that sometimes a breakpoint can be hit twice consecutively. Use `bp /1` to remove the breakpoint after it's been hit to work around this.
I've hit no failures anymore after running the 7 cdb tests >500 times in a row on my box.
=> Windows: Stabilize cdb-based CodeView lit-tests

gen/toir.cpp, tests/codegen/gh3553.d
Don't simply forward the caller's context without checking whether the lambda actually needs a parent context. Fixes #3553.
=> Fix potentially wrong context pointers when calling delegate literals

driver/linker-msvc.cpp, tests/sanitizers/link_fuzzer.d, tests/sanitizers/lit.local.cfg
Lit-test `sanitizers/fuzz_asan.d` works, while `fuzz_{basic,mixin}.d` fail with linker errors, as (implied & apparently required) `-fsanitize-coverage=inline-8bit-counters` isn't supported on Windows yet (see https://bugs.llvm.org/show_bug.cgi?id=35674; I've tried the `trace-pc-guard` variant as well as excluding the tracing altogether...), e.g.:
```
fuzz_basic.d.tmp.obj : error LNK2019: unresolved external symbol __start___sancov_cntrs referenced in function sancov.module_ctor_8bit_counters
fuzz_basic.d.tmp.obj : error LNK2019: unresolved external symbol __stop___sancov_cntrs referenced in function sancov.module_ctor_8bit_counters
fuzz_basic.d.tmp.obj : error LNK2019: unresolved external symbol __start___sancov_pcs referenced in function sancov.module_ctor_8bit_counters …
```
=> Windows: Add *some* support for -fsanitize=fuzzer and enable ASan tests

gen/declarations.cpp, gen/function-inlining.cpp, tests/codegen/inlining_templates.d
[The remaining non-upstreamed piece from #3456.]
With the new `available_externally` emission into each referencing CU, the enforced regular emission from the module members tree shouldn't be required anymore.
After adapting the `codegen/inlining_templates.d` lit-test accordingly (no IR definitions anymore in .ll file, because `available_externally` doesn't make it there), I've noticed that a lambda in imported and inlined `call_enforce_with_default_template_params()` wasn't emitted - it got culled by `alreadyOrWillBeDefined()`.
Function/delegate literals aren't culled anymore.
=> Don't enforce (normal) emission for pragma(inline, true) function templates, and don't cull lambdas

tests/lit.site.cfg.in, tests/sanitizers/lit.local.cfg, tests/sanitizers/tsan_noerror.d, tests/sanitizers/tsan_tiny_race.d, tests/sanitizers/tsan_tiny_race_TLS.d
A reboot of #3525 after #3522.
=> Fix ThreadSanitizer support by removing detaching of main thread upon program termination

gen/nested.cpp, tests/codegen/nested_gh3556.d
=> Traverse full chain of nested aggregates when resolving a nested variable

cmake/Modules/BuildDExecutable.cmake
The ldc2 executable wasn't re-linked when only the D object file(s) changed. Fortunately, the custom target still suffices to improve
parallelization.
=> Fix build problem after #3575

.azure-pipelines/posix.yml
For simple cross-compilation via `-mtriple=arm64-apple-macos` as long as a suited Xcode version >= 12.0 (?) is installed.
=> Azure CI: Include macOS arm64 libraries in prebuilt Mac package

dmd/aggregate.h, dmd/dstruct.d, dmd/expressionsem.d, dmd/typinf.d, gen/declarations.cpp, gen/llvmhelpers.cpp, gen/toir.cpp, gen/typinf.cpp, gen/typinf.h, ir/irstruct.cpp, tests/codegen/export_aggregate_symbols.d, tests/codegen/gh2346.d, tests/codegen/pragma_no_typeinfo.d, tests/codegen/static_array_huge.d, tests/codegen/static_typeid_gh1540.d
**First commit only**:
Analogous to ClassInfos, incl. normal linkage (external for non-templates, weak_odr for templates).
This enables to get rid of frontend logic wrt. whether to add `TypeInfoStructDeclarations` to a module's members tree - previously,
it was defined as linkonce_odr in the owning module and each referencing module (unless speculative) - and related extra semantic and codegen for the special member functions.
I've gone a bit further and moved the entire TypeInfo emission for LDC to the codegen layer; no `TypeInfoDeclarations` are added to the module members anymore. Whenever we need a TypeInfo symbol during codegen, it is declared or defined, and we don't need to rely on brittle frontend logic with speculative-ness complications.
This might slightly increase compilation …
=> Emit struct TypeInfos in referencing compilation units only

README.md
My undecisive suggestion would be to just link to the VisualD installer for those users who would rather have a branded experience. I don't really have any opinion on this.
README.md would look like:
=> Mention the VisualD Windows installer in the README.

gen/linkage.h, gen/passes/GarbageCollect2Stack.cpp, gen/passes/metadata.h, gen/typinf.cpp, gen/typinf.h, ir/iraggr.cpp, ir/irclass.cpp, ir/irstruct.cpp
Compiling the `rt.util.typeinfo` unittests (mostly disabled until now) leads to base-typed forward declarations of built-in TypeInfos colliding with the init symbols for their `TypeInfo_*` classes in `rt.util.typeinfo`.
We've already had a workaround for this in one place (`typinf.cpp`); extend it to the other side as well (`iraggr.cpp`).
Also make sure to emit the TypeInfo metadata even if the IR symbol already exists as init symbol.
Also keep init symbols of built-in TypeInfo classes mutable just like any other TypeInfo, so that e.g. `synchronized()` can be used on the implicit monitor.
And finally, simplify the TypeInfo metadata for the GC2Stack pass.
=> Handle IR collisions wrt. built-in TypeInfos and make them mutable

.azure-pipelines/windows.yml, driver/linker-msvc.cpp, driver/linker.cpp, driver/main.cpp, tests/lit.site.cfg.in
Fixes #2657 by deferring the `llvm_shutdown()` call.
This allows to remove bundled `lld-link.exe` for the prebuilt Windows packages.
=> Fix LTO with -link-internally for MSVC targets

driver/main.cpp, tests/codegen/unknown_critical_section_size.d
Resolves #3607.
This has been added 5+ years ago with dlang/dlang.org@4c9a20a75f3a577edc89abacc81902f1cb11c32c.
=> Predefine version `FreeStanding` when targeting bare-metal

gen/abi-win64.cpp, gen/dibuilder.cpp
I expect this to be slightly more performant than the previous behavior, where a delegate was treated like a corresponding struct, passed via hidden pointer and returned via sret.
The primary motivation is a smooth preparation for PR #3578 - in order to allow people to experiment with `-preview=in` without recompiling druntime and Phobos, `in` slices and delegates must not be passed by-ref with `-preview=in` (see dlang/dmd#11828). This would have required a special case for delegates on Win64, which is IMO better handled this way.
=> Win64 ABI: Pass/return delegates like slices - in (up to) 2 GP registers

gen/abi-win64.cpp, gen/abi-x86.cpp, tests/codegen/no_abi_blit_for_nonpod.d
Streamlining this with the other ABIs and preventing small non-PODs from being passed in a register or on the stack, which breaks interior pointers and hinders adding move ctors.
=> Windows extern(D) ABIs: Pass non-PODs by ref to hidden copy

gen/abi-win64.cpp, gen/abi.cpp, gen/abi.h, tests/codegen/vector_abi_x86.d
Corresponding to Microsoft's `__vectorcall`, see https://docs.microsoft.com/en-us/cpp/cpp/vectorcall?view=msvc-160.
=> Win64 extern(D) ABI: Pass/return Homogeneous Vector Aggregates in SIMD registers

azure-pipelines.yml, packaging/windows_installer.iss
With the option to add the `bin` dir to the current user's `PATH`, choosing x64 and/or x86 libraries, and optionally opening `README.txt` after installation.
An uninstaller is generated and accessible from 'add/remove programs'.
The `major.minor` version part (or first 8 commit hash chars for CI builds) constitute the 'app ID' - v1.24.1 upgrades v1.24.0, but
v1.25.0-beta1 is a separate 1.25 family installed side-by-side.
Also reflect installed LDC versions in (the 32-bit view of) the registry - e.g., key `HKLM\SOFTWARE\LDC\1.24` with values `InstallationFolder` and `Version` (`1.24.0`).
=> Add CI-automated Windows installer based on Inno Setup

gen/runtime.cpp
To fix ABI incompatibilities between the previous struct and `void*` used by the hardcoded compiler prototypes, e.g., for WebAssembly, which uses the default `UnknownTargetABI`, which uses LLVM `byval` for all structs and static arrays.
=> druntime: Define rt.aaA.AA as naked pointer, no struct wrapper

gen/irstate.h, gen/mangling.cpp, gen/mangling.h, gen/ms-cxx-helper.cpp, gen/trycatchfinally.cpp, tests/compilable/gh3501.d
[Extracted from #3517.]
As reported in https://github.com/ldc-developers/ldc/issues/3501#issuecomment-661551187.
Previously, LDC would simply override an existing TypeDescriptor global with an equivalent definition if assertions were disabled.
Use different equivalent TypeDescriptors in this exotic case now, by using proper mangling. [The linker can presumably still fold duplicates via ICF.]
Ideally, these descriptors would be truly unique, but WinEH depends on string comparisons to check for matching catch clauses, and currently depends on `TypeInfo_Class.name` to generate these strings at runtime when throwing an exception, see https://github.com/ldc-developers/druntime/blob/19731a92a97dbe4d7f7a4e15ceaff8444a1f879a/src/ldc/eh_msvc.d#L192-L211.
So if those names were fully qualified …
=> Fix colliding WinEH TypeDescriptors for exceptions with the same TypeInfo_Class name

.travis.yml, dmd/dsymbolsem.d, dmd/dtemplate.d, dmd/globals.d, dmd/globals.h, driver/cl_options.cpp, driver/cl_options.h, driver/main.cpp, gen/declarations.cpp, gen/function-inlining.cpp, gen/function-inlining.h, gen/functions.cpp, gen/llvmhelpers.cpp, gen/llvmhelpers.h, gen/modules.cpp, gen/naked.cpp, gen/rttibuilder.cpp, gen/rttibuilder.h, gen/runtime.cpp, gen/tollvm.cpp, gen/typinf.cpp, ir/iraggr.cpp, ir/irclass.cpp, ir/irstruct.cpp, ir/irvar.cpp, runtime/CMakeLists.txt, tests/d2/CMakeLists.txt
[In essence, a revised version of the remaining stuff from #3422.]
I.e., *define* templated symbols in each referencing compilation unit (=> object file) when using discardable `linkonce_odr` linkage, analogous to C++.
This makes each compilation unit self-sufficient wrt. templated symbols, which also means increased opportunity for inlining and less need for LTO. There should be no more undefined symbol issues caused by buggy template culling.
The biggest advantage is that the optimizer can discard unused `linkonce_odr` symbols early instead of optimizing and forwarding to the assembler. So this is especially useful with `-O` to decrease compilation times and can at least in some scenarios greatly outweigh the (potentially very much) higher number of symbols defined by the glue layer. …
=> Extend -linkonce-templates by matching template emission scheme

CMakeLists.txt, dmd/dsymbolsem.d, dmd/semantic2.d, dmd/semantic3.d, driver/archiver.cpp, driver/cl_options.cpp, driver/cl_options.h, driver/ldc_version.d.in, driver/linker.cpp, driver/main.cpp, driver/timetrace.cpp, driver/timetrace.d, driver/timetrace.h, driver/timetrace_sema.d, driver/toobj.cpp, gen/functions.cpp, gen/modules.cpp, tests/driver/ftime-trace.d
This uses LLVM's TimeProfiler functionality, such that LLVM's work is traced in the same profile (optimization and machine code gen).
Functionality is meant to be identical to Clang and LLD's --ftime-trace.
=> Add --ftime-trace functionality.

.azure-pipelines/windows.yml
Build steps:
- Build zlib v1.2.11 using `contrib\vstudio\vc14\zlibvc.sln` (static release lib incl. asm, which needs to be built separately, e.g., `cd contrib\masmx64 && bld_ml64.bat` - I've added `/safeseh` in `contrib\masmx86\bld_ml32.bat`).
MSCRT was set to `/MT`, and `/GS- /Zl` used for MinGW-based libs compatibility.
Includes (`{zconf,zlib}.h`) and lib (`zlibstat.{lib,pdb}`) copied to `C:\LDC\curl-7.74.0\deps[_x86]`.
- Patch `winbuild\MakefileBuild.vc`:
- Extend `CFLAGS` by `/DDONT_USE_RECV_BEFORE_SEND_WORKAROUND`.
- Extend `CFLAGS_LIBCURL_STATIC` by `/GS- /Zl` (for MinGW-based libs compatibility...).
- Build DLL + import lib + .exp file:
`nmake /f Makefile.vc mode=dll VC=16 WITH_DEVEL=C:\LDC\curl-7.74.0\deps[_x86] WITH_ZLIB=static GEN_PDB=no DEBUG=no MACHINE=x{64,86} …
=> Azure CI Windows: Upgrade bundled libcurl to v7.74.0

dmd/target.d, gen/abi-aarch64.cpp, gen/abi-win64.cpp, gen/abi-x86-64.cpp, gen/abi.cpp, gen/abi.h, gen/target.cpp
I.e., the ABI-specific decision for which parameter types to prefer passing a ref over a value.
The x86_64 and AArch64 ABIs are pretty clear - use a ref if the POD type cannot be passed in registers. For all others, use a simple default heuristic based on the type size - if larger than 2 machine words, use a ref. Note that this includes x87 `real` for the 32-bit x86 ABI.
=> Implement ABI stuff for -preview=in

driver/linker-gcc.cpp, driver/main.cpp
Testing https://github.com/ldc-developers/druntime/pull/192.
=> druntime: Cherry-pick libunwind-based backtrace alternative and use it for musl targets

CMakeLists.txt, runtime/CMakeLists.txt
LLVM 12 will bump it to 3.13.4 anyway. Resolves #3647.
=> CMake: Bump min version to 3.4.3 like LLVM 11 to silence deprecation warning

dmd/cli.d, dmd/dmangle.d, dmd/dmodule.d, dmd/expression.d, dmd/expression.h, dmd/expressionsem.d, dmd/globals.d, dmd/globals.h, dmd/mars.d, dmd/mtype.d, dmd/semantic2.d, dmd/utils.d, driver/archiver.cpp, driver/archiver.h, driver/linker.cpp, driver/linker.h, driver/main.cpp
Requiring some adaptations for enhanced `emitMakeDeps` functionality. Also fixes #3636.
=> Merge upstream stable

gen/declarations.cpp, gen/function-inlining.cpp, gen/tollvm.cpp, ir/irvar.cpp, tests/codegen/lambdas_gh3648.d, tests/codegen/lambdas_gh3648b.d
As they are emitted into each referencing object file anyway.
Handling the globals resolves issue #3648.
I think this also solves issue #2968 - in the presumably rare event that you absolutely don't want to emit a function into its owning CU and only into each referencing CU, an enum-lambda can be used as shown in the testcase.
With `pragma(inline, true)`, it'll most likely be actually inlined and not make it to the object files.
=> Emit lambdas as linkonce_odr, including contained globals

.github/workflows/supported_llvm_versions.yml, .travis.yml, azure-pipelines.yml
Their open-source engagement is fading, and jobs take a while to get scheduled.
Shippable will die too on ~~March~~ May 3rd; I hope the AArch64 Travis job can last a little while longer for some AArch64 test coverage.
Also add 2 more retry rounds to work around recent OOM regressions.
=> Travis CI: Cut down to Linux AArch64 only

dmd/dmodule.d, dmd/mars.d, dmd/module.h, driver/main.cpp, gen/modules.cpp, tests/driver/cleanup_obj_gh3643.d
To prevent conflicts for concurrent LDC processes in the same working dir, resolving #3643.
Re-use this for the temporary object files of `-run` by enforcing `-cleanup-obj` in that case. Additionally enforcing `-oq` prevents
conflicting filenames in that dir and allows to get rid of previous `Module.makeObjectFilenameUnique()`.
=> -cleanup-obj: Put object files into temporary directory by default

gen/optimizer.cpp, tests/codegen/inlining_disablecross.d
People use `dflags "-enable-cross-module-inlining" platform="ldc"` in their `dub.sdl` files; default and debug builds without `-O` thus incur a superfluous compile-time cost (extra `available_externally` emissions) for no benefit.
=> Ignore -enable-cross-module-inlining if inlining is generally disabled

.azure-pipelines/1-posix-setup.yml, .circleci/config.yml, .cirrus.yml, .github/workflows/supported_llvm_versions.yml, .travis.yml, shippable.yml
This can significantly improve throughput, because ninja keeps on going after a child process dies and tries to build as many targets as it can in the current pass.
=> CI: Use `-k0` for ninja cmdlines potentially running into out-of-memory errors

driver/dcomputecodegenerator.cpp
Updating valid_cuda_versions gives access to additional builtins.
The programmer is responsible for adapting to the evolving CUDA semantics but this should not be a breaking change.
=> Dcomputextra

utils/gen_gccbuiltins.cpp
This updates the gen_gccbuiltins utility to handle 'i1' types as dlang bool.
The 'vec' substring concatentation against "bool" seems innocuous but should be reviewed.
=> accept i1 types as dlang bool

dmd/declaration.h, gen/asmstmt.cpp, gen/functions.cpp, tests/codegen/asm_gcc_no_fp.d
As GDC doesn't either (see https://d.godbolt.org/z/6qMG76).
=> Don't enforce the frame pointer for functions with GCC-style inline asm

gen/dibuilder.cpp, gen/dibuilder.h, tests/debuginfo/args_cdb.d, tests/debuginfo/enums_cdb.d
=> Fix overzealous toBasetype'ing for debuginfo types

gen/abi-generic.h, tests/codegen/gh3692.d
As the alignment of the final LL type may be greater than the rewritten value's. Fixes #3692.
=> Fix insufficient alignment of BaseBitcastABIRewrite allocas

driver/args.cpp
I've missed this in #3663 (only tested manually on Linux back then).
=> Adapt to Windows-specific LLVM 12 API change

driver/cache.cpp, driver/codegenerator.cpp, driver/timetrace.cpp, driver/toobj.cpp
[This](https://reviews.llvm.org/D101506) drops old deprecated OpenFlags support.
OF_{Append,None,Text} has been available since LLVM 9.
- https://reviews.llvm.org/rG1f67a3cba9b09636c56e2109d8a35ae96dc15782
=> Use new OpenFlags enumeration

.github/workflows/supported_llvm_versions.yml, gen/dibuilder.cpp, gen/dibuilder.h, runtime/DRuntimeIntegrationTests.cmake, tests/driver/save_optimization_record.d
As I've seen that we run them in (default) release mode, which includes `-release` and so disables assertions etc.
=> CMake: Run the druntime integration tests in debug mode too

.travis.yml
=> Travis CI: Bump Ubuntu base image to 18.04, for Python 3.6

dmd/globals.d, dmd/globals.h, driver/cl_options.cpp, driver/cl_options.h, driver/main.cpp, gen/functions.cpp, gen/llvmhelpers.cpp, gen/llvmhelpers.h, gen/moduleinfo.cpp, gen/modules.cpp, gen/ms-cxx-helper.cpp, gen/naked.cpp, gen/optimizer.cpp, gen/passes/DLLImportRelocation.cpp, gen/passes/Passes.h, gen/tollvm.cpp, gen/tollvm.h, gen/trycatchfinally.cpp, gen/typinf.cpp, ir/iraggr.cpp, ir/iraggr.h, ir/irclass.cpp, ir/irmodule.cpp, ir/irstruct.cpp, ir/irvar.cpp, tests/codegen/export.d, tests/codegen/fvisibility_dll.d, tests/codegen/inputs/fvisibility_dll_lib.d
To pave the way for simple DLL generation (end goal: `druntime-ldc-shared.dll`).
The `dllexport` storage class for functions definitions is enough; the automatically generated import .lib seems to resolve the regular symbol name to the actual symbol (`__imp_*`), so `dllimport` for declarations seems superfluous.
For global variables, things are apparently different unfortunately.
=> Windows: Make -fvisibility=public export all defined symbols and import external data

runtime/DRuntimeIntegrationTests.cmake
Testing https://github.com/ldc-developers/druntime/pull/198.
=> druntime: Generalize 'shared' integration tests to include Windows

dmd/console.d, dmd/errors.d, dmd/globals.d, dmd/mars.d
dlang/dmd#12541 will land in 2.098; I want it in LDC v1.27 already because colors come in handy in GitLab CI logs etc.
=> Cherry-pick upstream support for enforcing ANSI colors for redirected stderr on Windows

driver/cl_options.cpp, driver/cl_options.h, gen/coverage.cpp, tests/codegen/cov_modes.d
This gives the user the ability to get a more performant coverage count execution, at the cost of thread-safety or just boolean true/false on a line (no more counting).
I restricted the testing to Linux, due to the test commandline crazyness (the coverage output filename is very annoying and cannot be set by the user).
=> Add -cov-increment option to specify the type of increment instruction

.travis.yml
We don't have AArch64 packages at the moment, so downloading v1.27.0-beta1 fails.
=> Travis CI: Pin host compiler to v1.26.0

CMakeLists.txt
Fixes https://github.com/ldc-developers/ldc/issues/3737
Usage example:
```
cmake -DALTERNATIVE_MALLOC_O=/usr/local/lib/mimalloc-1.7/mimalloc.o
```
Especially codegen performance is greatly improved with mimalloc (https://microsoft.github.io/mimalloc/index.html), around ~30% on a large codebase.
=> CMake: Add `ALTERNATIVE_MALLOC_O` option for user to link LDC with a malloc-overriding allocator like mimalloc.o

runtime/CMakeLists.txt, runtime/jit-rt/DefineBuildJitRT.cmake
(Only) when compiling them all-at-once anyway; primarily for implicit cross-module inlining across the same library.
This won't work as long as there are multiple conflicting declarations across a library's modules - issue #2782.
=> CMake: Compile shared Phobos libs to a single object file

.azure-pipelines/4a-mac_x64.yml, azure-pipelines.yml
IIRC, I've disabled these because of myriads of linker warnings when trying to use them, and those should be fixed by LLVM 12 now.
=> Azure CI: Build and bundle shared libs for iOS too

dmd/globals.d, dmd/globals.h, dmd/id.d, dmd/id.h, driver/cl_options.cpp, driver/cl_options.h, driver/main.cpp, gen/llvmhelpers.cpp, gen/llvmhelpers.h, gen/modules.cpp, gen/optimizer.cpp, gen/typinf.cpp, ir/iraggr.cpp, ir/irmodule.cpp, ir/irvar.cpp, runtime/CMakeLists.txt, tests/codegen/fvisibility_dll.d
* Newly require `-link-defaultlib-shared` for implicit dllimport.
E.g., this enables to compile druntime DLL with `-fvisibility=public` for pure exports and no (local) imports (such as builtin TypeInfos).
* `-link-defaultlib-shared` alone now only implicitly imports symbols from druntime/Phobos.
This simplifies building complex DLLs linked against a bunch of static libs (dub only supports static lib dependencies!); the static
libs don't need to be compiled with `-fvisibility=public` anymore (if the DLL itself isn't either), `-link-defaultlib-shared` is sufficient.
This is mainly useful for existing DLLs with explicit exports, to make them link against *shared* druntime/Phobos and so end up with a single druntime/Phobos for the whole process.
=> Windows: Add -dllimport CLI option for more selective implicit dllimports

driver/main.cpp
While CppRuntime should ideally be moved out of the compiler,
it is currently reserved by the compiler and can't be defined
in user code. The most used Musl platform is Alpine Linux,
which doesn't have an alternative for CppRuntime_Clang,
so just define it to use Gcc for now.
=> Driver: Use CppRuntime_Gcc by default with Musl

.azure-pipelines/6-package.yml, .cirrus.yml, cmake/Modules/BuildDExecutable.cmake, gen/nested.cpp
=> Fix DtoCreateNestedContextType() for -linkonce-templates

gen/functions.cpp, gen/irstate.h, gen/naked.cpp, gen/toir.cpp
Found while investigating (but not fixing) #3690.
=> Fix bad assumption of FuncGenStates stack reflecting lexical parent/child relationships

dmd/declaration.d, dmd/declaration.h, dmd/dinterpret.d, dmd/id.d, dmd/traits.d, gen/llvmhelpers.cpp, gen/toconstelem.cpp, gen/toir.cpp, tests/semantic/traits_initSymbol.d
A clean way of directly accessing struct and class init symbols. It yields a `const(void[])` slice; the length reflecting the struct/class instance size, and the pointer either pointing to the init symbol or being null for zero-initialized structs.
Paves the way for resolving #3773 in druntime as well as accessing class init symbols without `TypeInfo_Class.initializer()` indirection, and so with `-betterC` as well.
=> Add __traits(initSymbol, <aggregate type>)

gen/functions.cpp, ir/irstruct.cpp
As there are apparently cases where the struct hasn't had semantic3 yet, at least with `-linkonce-templates`. This prevents erroneous `xopCmp` etc. (failing to compile) from being referenced in the TypeInfo (=> linker errors) / being analyzed for `-linkonce-templates` codegen. `semanticTypeInfoMembers()` replaces them by `object._xopCmp()` etc. if compilation fails.
=> Make sure special struct TypeInfo members are semantically analyzed before emitting the TypeInfo

.azure-pipelines/1-posix-setup.yml, .azure-pipelines/windows.yml, .circleci/config.yml, .cirrus.yml, .github/workflows/supported_llvm_versions.yml, .travis.yml, shippable.yml
For some Linux images at least, where the lit 12.0.1 upgrade came with some nice `ModuleNotFoundError: No module named 'setuptools'` error from one hour to the next.
=> Fix lit 12.0.1 installation regression

driver/main.cpp, gen/passes/SimplifyDRuntimeCalls.cpp, gen/target.cpp, gen/tollvm.cpp, tests/compilable/arch64bit_abi32bit_gh3802.d
I don't know how to trigger the `_d_array_slice_copy` simplification by SimplifyDRuntimeCalls, so can't test that part of the PR.
=> Fix issue #3802 - Fix size_t size for 32bit ABI on 64bit architectures.

.travis.yml
Now that we have AArch64 packages again.
=> Travis CI: Revert to latest LDC (beta) as host compiler

driver/cl_options.cpp, gen/functions.cpp, gen/llvmhelpers.cpp, gen/llvmhelpers.h, ir/iraggr.cpp, ir/irclass.cpp, ir/irmodule.cpp, ir/irstruct.cpp, ir/irvar.cpp
Via a sorts-of '-linkonce-templates light', only defining all *data* symbols instantiated from druntime/Phobos templates in each referencing CU (as `weak_odr`).
=> -dllimport=defaultLibsOnly: Avoid -linkonce-templates requirement

driver/codegenerator.cpp, ir/irfunction.cpp
Encountered with the MSVC++ compiler and an LLVM 12 with disabled assertions, complaining about an `assert` macro expansion.
=> Fix little compilability regression

.cirrus.yml, .github/workflows/supported_llvm_versions.yml
As GitHub Actions dropped support for Ubuntu 16.04.
=> CI: Move ltsmaster host-compiler job from GH Actions to Cirrus CI

driver/tool.cpp, driver/tool.h, tests/driver/missing_tool.d
To prevent bad experiences like https://forum.dlang.org/post/tjsbfalkosmrebhjfmah@forum.dlang.org.
=> Don't silently ignore invalid external tool specifications

gen/dibuilder.cpp, tests/debuginfo/args_cdb.d
According to the ABI specification, when describing the delegates memory
layout, the context pointer is named .ptr .
https://dlang.org/spec/abi.html#delegates
Signed-off-by: Luís Ferreira <contact@lsferreira.net>
=> DI: delegate context pointer should be .ptr instead of .context

README.md
Maintained at https://github.com/void-linux/void-packages/blob/master/srcpkgs/ldc/template
=> Add Void Linux to package manager list

gen/dibuilder.cpp
Add a special case for size_t compat on 32-bit OpenBSD, which fixes linker errors when building LDC on 32-bit OpenBSD.
=> Use d_size_t in dibuilder.cpp

runtime/CMakeLists.txt
I was stuck on trying to fix a bug on my code, whenever i was manipulating around large stucts, it'd change global data
I first thought of a memory corruption somewhere, but it turns out it was a stackoverflow issue!
Increasing the default stack (from 64kb) to 1mb fixed the issue... temporarily! as i was playing with more data, i hit the issue again.. so i looked around and found this PR on the zig repo: https://github.com/ziglang/zig/issues/4496
Tada! now instead of overwritting my global memory, it throws a runtime error! that's better! i can now debug the issue properly!
Let's save people days of headache and make these options the default!
Zig/Rust also bumped the default stack size to 1mb (emscripten has a stack size of 5mb)
=> wasm: Add new default lld switches to protect from stackoverflow overwriting global memory

gen/asm-x86.h
This meant adding a new pattern for the 0 args, EDX:EAX,ECX clobber set.
=> Add rdtscp to the dmd-style inline assembler.

.azure-pipelines/1-posix-setup.yml, .azure-pipelines/4a-mac_x64.yml, .github/workflows/supported_llvm_versions.yml, .travis.yml, driver/linker-gcc.cpp, driver/linker-msvc.cpp, gen/modules.cpp, runtime/CMakeLists.txt, tests/codegen/ctor_initarray_gh2883.d, tests/codegen/llvm_used_1.d
=> Posix: Move magic DSO registration code to rt.dso druntime module

runtime/CMakeLists.txt
=> CMake: Fix warning when building runtime libs stand-alone

gen/target.cpp
RISC-V ILP32/LP64 ABI defines `long double` as 128bit.
Reference: https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/master/riscv-cc.adoc#cc-type-details
Signed-off-by: Luís Ferreira <contact@lsferreira.net>
=> gen/target: make real 128bit on RISC-V targets

driver/cache.cpp
This makes the error message look like this, for example:
```
Error: Could not create name of temporary file in the cache (errno 13: Permission denied)
\---------------------------/ this is the new part
```
=> Output error code and message string upon cache file errors.

gen/nested.cpp, tests/codegen/nested_nrvo_gh3883.d
Fixes #3883 by capturing NRVO vars by ref - unless the nested context is a heap closure.
=> Fix capturing NRVO variables

dmd/template.h, gen/declarations.cpp
Such instances are guaranteed not to need codegen (e.g., CTFE only).
Extracted from #3860.
=> -linkonce-templates: Cull 'discardable' template instances

dmd/dtemplate.d
Affecting the frontend itself, see https://issues.dlang.org/show_bug.cgi?id=22717.
Preparing LDC early is required to make DMD's Buildkite CI pass with the proposed fix in https://github.com/dlang/dmd/pull/13593.
=> Prepare for an upcoming breaking change with frontend v2.099 regarding opEquals order

CMakeLists.txt
To decrease the likelihood of stack overflows during heavily recursive `needsCodegen()`, e.g., #3913.
=> Windows: Double ldc2.exe stack limit to 16 MB

gen/llvmhelpers.cpp, gen/llvmhelpers.h, gen/tollvm.cpp, ir/iraggr.cpp, ir/irvar.cpp, tests/codegen/dllimport_gh3916.d
Instantiated data symbols were previously never dllimported with `-dllimport=all`. So if the parent template instance wasn't codegen'd into the binary directly, it remained undefined.
For `-dllimport=defaultLibsOnly`, the 'solution' to this problem was to define-on-declare data symbols instantiated from druntime/Phobos templates, making sure each binary defines all such symbols it references.
In both cases, switch to an approach where we dllimport all instantiated data symbols (or druntime/Phobos symbols only), and
dllexport them whenever defining them (so that other object files or binaries can import them). This may lead to more 'importing
locally defined symbol' linker warnings, but may also lead to less duplicates and possibly 'proper' sharing of instantiated globals
across the whole …
=> Fix #3916 - undefined symbols with `-dllimport=all` on Windows

dmd/dsymbolsem.d, dmd/dtemplate.d, dmd/globals.d, dmd/globals.h, driver/cl_options.cpp, driver/main.cpp, gen/declarations.cpp, gen/llvmhelpers.cpp
Make `-linkonce-templates` *not* tamper with the general template emission algorithm anymore (so on top of default non-allinst or `-allinst` modes), and keep those tweaks as experimental `-linkonce-templates-aggressive`.
Compiling the druntime/Phobos unittests is only marginally slowed down compared to the more aggressive variant (~1.5% for debug, ~2.5% for release). It does show some rough 10% increase in required memory, but that's in line with non-linkonce-templates.
The more aggressive variant has the advantage of skipping `needsCodegen()` and potentially codegen'ing less symbols. The problem is that if an instantiated symbol isn't explicitly referenced, for instance a CRT ctor, it might not be codegen'd at all.
=> Make -linkonce-templates less aggressive by default & add -linkonce-templates-aggressive

CHANGELOG.md, tests/sanitizers/asan_fakestack_GC.d, tests/sanitizers/asan_use_after_return.d
See https://github.com/google/sanitizers/wiki/AddressSanitizerExampleUseAfterReturn for an explanation of what bugs can be caught with ASan's fakestack enabled.
Apologies for the mess in git on master :(
=> Add druntime support for AddressSanitizer stack-use-after-return, fakestack

driver/codegenerator.cpp, driver/targetmachine.cpp, gen/dibuilder.cpp, gen/dibuilder.h, gen/functions.cpp, gen/inlineir.cpp, gen/nested.cpp, gen/passes/GarbageCollect2Stack.cpp, gen/tocall.cpp, gen/uda.cpp, ir/irfuncty.cpp, ir/irfuncty.h
`llvm::AttrBuilder` was changed to require an LLVMContext in its constructor, and can no longer be copied.
declare `DEBUG_TYPE` after includes for the GC2Stack pass as `llvm/Support/GenericDomTreeConstruction.h `(included from `llvm/IR/Dominators.h` `#define`s and `#undef`s it.
`llvm::DIBuilder::createExpression` now takes an `ArrayRef<uint64_t>` instead of `int64_t`. EmitLocalVariable has similarly changed
There is still to go the changing of load instructions to specify a type when loading, but that is significantly larger and more complicated. Will do that in a follow up PR.
=> Prepare for LLVM15: Headers, attributes

dmd/globals.d, dmd/globals.h, driver/main.cpp
Fixes #3945 by handling newlib like uclibc.
Implemented similar to fixupUClibc. newlib will be removed from the
environment part of the triple, if present. The rest of the environment
is preserved (such as eabi). For example, the triple
arm-none-eabi-newlib will be converted to arm-none-eabi and 
CRuntime_Newlib will be set.
=> Added support for newlib

.azure-pipelines/4-install.yml
Fixing #3939 for the prebuilt macOS/arm64 and Android packages.
=> Azure CI: Include druntime ImportC files (__builtins.di & importc.h) in cross-compiled packages

driver/targetmachine.cpp
By normalizing them, to resolve issues like #3971.
=> Handle 'invalid' default LLVM target triples

runtime/CMakeLists.txt
It's been dead for a while, since i686 support was dropped. Merging x86_64 and arm64 installations manually in e.g. bash (see the macOS_universal Azure CI job) seems much simpler and flexible to me.
=> CMake: Drop macOS fat multilib support

.github/actions/2a-build-pgo/action.yml
As the warnings also appear on Linux and Mac when using an LLVM *without assertions*.
=> GH Actions: Tweak -vp-counters-per-site for Posix too

driver/codegenerator.cpp, tests/sanitizers/asan_fiber.d, tests/sanitizers/asan_fiber_main.d, tests/sanitizers/asan_stackoverflow.d
I've finally found what was the problem! Now the user will see the variable name that is overflown (close to the address read), e.g.:
```
=================================================================
==73095==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x000101507f08 at pc 0x000100c7ece8 bp 0x000101507e70 sp 0x000101507e68
WRITE of size 4 at 0x000101507f08 thread T0
#0 0x100c7ece4 in _D10asan_fiber3fooFPiZv asan_fiber.d:21
#1 0x100c7ee1c in _D10asan_fiber6prefooFZv asan_fiber.d:31
#2 0x100de8ecc in fiber_entryPoint+0x4c (asan_fiber.d.tmp:arm64+0x10016cecc)
Address 0x000101507f08 is located in stack of thread T0 at offset 72 in frame
#0 0x100c7ed0c in _D10asan_fiber6prefooFZv asan_fiber.d:28
This frame has 1 object(s):
[32, 72) 'aiaiaiaiaiaiaiaiaiai' <== Memory access at …
```
=> Enable output of variable names in ASan and MSan error reporting.

driver/cl_options.cpp, driver/cl_options.h, driver/codegenerator.cpp, tests/codegen/fno_discard_value_names.d
This option has effect when outputting LLVM IR through LLVM option `--print-after=...` and similar cmdline options. It is needed to show variable names in IR in Godbolt's CE optimization pipeline view: https://d.godbolt.org/z/rjbEPaehn
See: https://github.com/compiler-explorer/compiler-explorer/pull/3838/files#diff-791e27601ad6c45c8712671c7e401aefe6d736159523745bc18b991bedcb4442R49
=> Add --fno-discard-value-names : Do not discard value names in LLVM IR

gen/tollvm.cpp, gen/tollvm.h
Also mark untyped `DtoLoad` as deprecated.
=> Add typed overloads for GEP, mark old ones deprecated

CMakeLists.txt
Useful when switching between LLVM version to determine you are building against what you think you are.
=> Log the LLVM version when running CMake

gen/abi-x86.cpp
`value_or` added in https://github.com/llvm/llvm-project/commit/3c49576417bab1b07764aa0b22664cbc8d3c3f53
`getValueOr` deprecated in
https://github.com/llvm/llvm-project/commit/5512f398a039e3ed7df502a0c263a8f366a84a4c
=> Fix `getValueOr`-> `value_or` deprecation

gen/cl_helpers.h
Fixes compilation broken by https://github.com/llvm/llvm-project/commit/fcd9fa416d0d3585f9d6c68302df8ba39889608a
I've no idea if this the proper thing to do, but it fixes compilation
=> `gen/cl_helpers.h`: Allow `MultiSetter` to be default constucted

gen/llvmhelpers.h, gen/tocall.cpp
I'm not at all sure about this. Any inputs welcome. (also idk if this is the best code style either)
=> Rework `DtoCallable` to remove `getPointerElementType`

gen/llvmhelpers.cpp, ir/irtypeaggr.cpp, ir/irtypeaggr.h
The previous API of returning two `unsigned`s was ambiguous when accessing the second member of a union that is the first member of a struct, where both output were set to zero.
It now returns one `unsigned` and an output `bool` to determine if it should be used as either a field or byte offset.
=> Change `IrTypeAggr::getMemberLocation` to indicate field or byte offest

gen/passes/GarbageCollect2Stack.cpp, gen/typinf.cpp
Augment the type info for arrays to include the element type in addition to the array type as a second type-as-metadata MDNode.
Use this in place of looking up the element type from the array type
=> Remove use of `getPointerElementType` from GC2Stack

gen/dvalue.cpp, gen/dvalue.h, gen/llvmhelpers.cpp, gen/llvmhelpers.h, gen/nested.cpp, gen/structs.cpp, gen/toir.cpp, ir/iraggr.cpp, ir/iraggr.h, ir/irtypeaggr.cpp, ir/irtypeaggr.h, ir/irtypeclass.cpp, ir/irtypestruct.cpp, tests/codegen/align_class.d, tests/codegen/gh2346.d
I hoped this day would never come, but we need crappy bit fields for ImportC - and D 2.101 (FWIW, I was very much against that decision). They mess up a bunch of assumptions (every member aligned at a byte boundary and of an integral size in bytes, so directly addressable) and come with no LLVM support AFAICT, so... much fun.
=> Bit fields

driver/targetmachine.cpp, driver/tool.cpp, gen/abi-riscv64.cpp, gen/abi-riscv64.h, gen/abi.cpp, runtime/CMakeLists.txt
This adds support for riscv64gc with the default LP64D ABI.
This work with https://github.com/ldc-developers/druntime/pull/204 and https://github.com/ldc-developers/phobos/pull/71.
Enable attribute `+d` by default to support riscv64gc D standard extension.
ABI is implemented according to RISCV Calling Convention.
Currently it is not able to pass all tests.
Most failed tests are related to NaN payload issue. But this maybe a issue related to the platform. e.g., after `atan` calculation, NaN payload will be cleared. This behavior is the same with GDC. C codes compiled with GCC and Clang act the same.
The `zlib-debug` and `zlib-debug-shared` test failure is probably caused by a wrong signed/unsigned compiler optimization. This needs further investigation.
The `druntime-test-gc-*` test also …
=> RISCV64: Initial support

gen/asmstmt.cpp, gen/irstate.h
Split from https://github.com/ldc-developers/ldc/pull/4121 to reduce the size of the diff to isolate errors
=> Add corresponding types to `IRAsmStmt::Operands`

gen/asmstmt.cpp, gen/irstate.h
This reverts commit f4a4f76b8988c5ebd9733c579a87ec74eaca85de.
=> Revert "Add D types to `IRAsmStmt::Operands` (#4138)"

gen/arrays.cpp, tests/codegen/gh4134.d
partial revert of https://github.com/ldc-developers/ldc/commit/37aca9c9405226d10bb0aeb082ffeb508da78b9e fixes #4134, tested locally (e: not with an LLVM with assertions enabled though apparently)
=> Fix issue 4134

gen/arrays.cpp, gen/tocall.cpp, gen/toir.cpp, gen/tollvm.cpp, gen/tollvm.h
It only does two elements and is exclusively used for slices
fixes #4137
=> Rename `DtoAggrPaint` to `DtoSlicePaint`

gen/nested.cpp, tests/codegen/gh4130.d
This fixes the issue, I'm not sure if the correct thing to do is to make DMD not emit bogus ASTs to begin with.
fixes #4130
=> Fix issue 4130

gen/optimizer.cpp, tests/codegen/attr_optstrat.d
Found an explanation of what was happening with optnone attribute being ignored here: https://www.duskborn.com/posts/llvm-new-pass-manager/#the-curious-case-of-the-optimized-optnone-functions
I made the change suggested there.
=> Fix for optnone not being respected with new passmanager

driver/toobj.cpp, gen/dcompute/targetOCL.cpp, tests/codegen/dcompute_cl_addrspaces_new.d, tests/codegen/dcompute_cl_addrspaces_old.d, tests/lit.site.cfg.in
The test has this at the top of it.
```
// REQUIRES: target_SPIRV
// RUN: %ldc -c -mdcompute-targets=ocl-220 -m64 -mdcompute-file-prefix=addrspace -output-ll -output-o %s && FileCheck %s --check-prefix=LL < addrspace_ocl220_64.ll \
// RUN: && %llvm-spirv -to-text addrspace_ocl220_64.spv && FileCheck %s --check-prefix=SPT < addrspace_ocl220_64.spt
```
judging by e.g. https://github.com/llvm/llvm-project/blob/main/llvm/test/CodeGen/SPIRV/ExecutionMode.ll it seems we should be able to use `llc` to then get text that we can verify. How do I `//RUN:` a different set of commands based on the LLVM version that LDC was built against?
=> Use LLVM's SPIRV backend for LLVM 16

.github/actions/6-integration-test/action.yml, runtime/CMakeLists.txt
=> CMake: Install 32-bit LTO versions of druntime & Phobos for multilib builds

driver/main.cpp, gen/runtime.cpp
- remove initialization of removed legacy passes
- add initialization of AggressiveInstCombine pass
- Fix build for new MemoryEffects attributes (memory(read) instead of `readonly`)
=> LLVM 16 fix build

driver/main.cpp, gen/arrays.cpp, tests/codegen/vastart_vaend_gh1744.d
Separate out the code fixes from https://github.com/ldc-developers/ldc/pull/4257
This adds LDC_LLVM_OpaquePointers version identifier, needed for supporting druntime with opaque and typed pointers. This is needed for testing with `--opaque-pointers=false/true`.
=> Opaque pointer fix and LDC_LLVM_OpaquePointers

.cirrus.yml, .travis.yml
GitHub Actions already skips these other tags: https://github.com/ldc-developers/ldc/blob/5c3478c129492acf2201222d5398090a07072f66/.github/workflows/main.yml#L268
=> Travis & Cirrus CI: Do not upload artifacts to GitHub release for tags without `v` prefix

gen/toir.cpp, gen/tollvm.cpp, gen/tollvm.h, tests/codegen/gh2865.d, tests/codegen/gh4264.d
The `DtoGEP` functions assume the offset is a 32-bit value, but when used with a `SymOffExp`, the offset may be 64-bit. In that case, the GEP should use an i64 for the offset.
Fixes #4264.
Let me know if I should make any changes. Thanks!
=> Fix miscompilation when adding a 64-bit constant to a symbol

CHANGELOG.md, driver/cl_options.cpp, driver/cl_options.h, gen/functions.cpp, tests/codegen/fno_delete_null_pointer_checks.d
The commandline option name stems from GCC and Clang.
=> Add -fno-delete-null-pointer-checks

tools/update-dmd-rewrite.sh
See https://github.com/ldc-developers/ldc/discussions/4245.
=> Add update-dmd-rewrite.sh script

tests/sanitizers/asan_fakestack_GC.d, tests/sanitizers/asan_fiber_main.d, tests/sanitizers/asan_use_after_return.d, tests/sanitizers/lsan_memleak.d
The substitution `%env_asan_opts` already contains the `env` command.
=> Remove double `env` from lit tests.

tests/codegen/gh3692_llvm15.d, tests/codegen/inline_ir.d
Now the tests support opaque and typed ptr output.
=> Fix some lit tests for typed pointer LLVM15.

dmd/root/ctfloat.d, dmd/root/ctfloat.h, dmd/root/longdouble.h, gen/asmstmt.cpp, gen/ctfloat.cpp, gen/pragma.cpp, ir/irclass.cpp
fixes compilation warning on newer clang versions.
See https://issues.dlang.org/show_bug.cgi?id=23648 for frontend.
=> Replace `sprintf` with safer `snprintf`

.cirrus.yml, .github/actions/1-setup/action.yml
Instead of the lld from the prebuilt LDC-LLVM package, with enabled assertions for untagged CI builds. Besides slowing down linking, we also suffer from sporadic failing LLD assertions (since v13) for MSVC targets.
=> GH Actions / Cirrus CI: Use lld from host clang (without assertions) as default linker

CHANGELOG.md, driver/codegenerator.cpp, tests/fail_compilation/asm_error_gh4293.d
=> Fix regression with LLVM 13+: some errors in inline assembly don't stop compilation

driver/cl_options_sanitizers.cpp, driver/cl_options_sanitizers.h, gen/optimizer.cpp, tests/sanitizers/fuzz_asan.d
Make this optional for users, especially on Linux. Because LLVM's default has changed, and using UAR requires runtime support.
relates to https://github.com/ldc-developers/ldc/pull/4328
=> Add -fsanitize-address-use-after-return

dmd/dinterpret.d, driver/timetrace.d, tests/driver/ftime-trace-ctfe.d, tests/driver/ftime-trace.d
`--ftime-trace` was not yet tracing CTFE, a major oversight... With these changes it now _does_ trace CTFE. The start, and function calls during CTFE. I think that gives the user enough info to pinpoint where time is spent.
Testcase gives this output:
@rikkimax
=> ftime-trace: add tracing of CTFE !

driver/cl_options_sanitizers.cpp
Adds support for `-fsanitize-coverage=trace-loads,trace-stores` (added in newer versions of LLVM).
=> Add coverage tracing for loads and stores

runtime/druntime/src/core/simd.d, tests/compilable/intrinsics_imports.d, utils/gen_gccbuiltins.cpp
Adds simple testcase to test that generation of intrinsics import files is indeed happening. This uncovered missing vector type aliases for MIPS, fixed that too. Resolves issue #4347
=> Fix gccbuiltins_*.di generation for LLVM >= 15.

runtime/druntime/src/ldc/eh_msvc.d
As since druntime v2.102, the `Throwable.infoDeallocator` field needs to be set too in order to properly free the newly malloc'd `Throwable.info` trace when finalizing a `Throwable`.
=> Windows: Use _d_createTrace() for creating exception backtraces

driver/cl_options.cpp
It's been there for a while and has been used at Weka for a while too.
=> Remove "experimental" from --cache

.circleci/config.yml, .cirrus.yml, .github/actions/1-setup/action.yml, .github/workflows/main.yml, .github/workflows/supported_llvm_versions.yml, CHANGELOG.md
As GitHub Actions eagerly removed support for it (5 years old now).
=> CI: Bump Ubuntu 18 jobs to Ubuntu 20

.github/workflows/supported_llvm_versions.yml
As the 10.x images aren't available anymore.
=> GH Actions: Bump macOS 10.15 jobs to macOS 11

tools/timetrace2txt.d
The options indents all list items. Helps with editors (such as SublimeText) that automatically enable "code folding" based on indentation, which makes it easier to navigate large time traces with deep item nested levels.
=> Add --indent option to timetrace2txt.

CHANGELOG.md, driver/toobj.cpp, gen/optimizer.cpp
Tested manually with the Symmetry project, and LLVM 14. The `-g` compile times with both legacy and new pass managers are on par again.
=> Fix #4354 - Huge compile slowdown with -g and the new LLVM pass manager

.cirrus.yml, tests/dmd/runnable/test34.d
As there's a single remaining failure - `runnable/test34.d` fails, with enabled optimizations only.
=> Cirrus CI: Don't allow macOS arm64 jobs to fail anymore

gen/tollvm.cpp
We have a new codepath for LLVM >= 16, so the deprecation is solved.
=> Fix deprecation warning

driver/args.cpp, driver/args.h
This helps for LLVM16 support (deprecated llvm::Optional).
=> Simplify executeToolAndWait, the optional parameter is specified for every call

.cirrus.yml
Not sure if it's just the *-shared variant; we'll see.
=> Cirrus CI macOS arm64: Work around sporadic core.thread.fiber-shared failures

CHANGELOG.md, gen/tollvm.cpp, tests/codegen/inputs/lambdas_dmd23722b.d, tests/codegen/lambdas_dmd23722.d, tests/codegen/lambdas_gh3648.d, tests/codegen/lambdas_gh3648b.d
See https://issues.dlang.org/show_bug.cgi?id=23722.
=> Handle lambda mangle collisions by emitting lambdas with internal linkage

gen/declarations.cpp, tests/codegen/attr_callingconvention.d, tests/compilable/gh2782.d, tests/compilable/inputs/gh2782b.d
Instead of eagerly IR-declaring all such functions in root modules being compiled.
This might reduce compile times in some cases, and is a cheap way to improve the situation wrt. issue #2782.
=> Lazily IR-declare all function fwd declarations

driver/codegenerator.cpp, driver/toobj.cpp, tests/driver/fwarn-stack-size.d
Fix issue where an LLVM error or warning during IR passes (e.g. `--fwarn-stack-size`) does not abort outputting files. The object file would be added to the cache, and subsequent repeated LDC execution would fetch the object file from the cache, effectively swallowing the error.
=> Don't output files on LLVM errors.

CHANGELOG.md, driver/cl_options_instrumentation.cpp, driver/cl_options_instrumentation.h, driver/main.cpp, gen/modules.cpp, gen/target.cpp, tests/codegen/fcf_protection.d
Resolves issue #4435
~~I do not know how to cleanly add compiler-defined enum value (e.g. `__CET__ == 1`), so I opted for adding compiler-defined versions instead.~~
=> Add -fcf-protection.

.github/workflows/supported_llvm_versions.yml, driver/args.cpp, driver/linker.cpp, driver/linker.h, driver/main.cpp, driver/targetmachine.cpp, gen/dcompute/druntime.cpp, gen/dibuilder.cpp, gen/ms-cxx-helper.cpp, gen/optimizer.cpp, gen/runtime.cpp, gen/uda.cpp, tools/ldc-profdata/llvm-profdata-16.0.cpp, utils/FileCheck-16.cpp, utils/not.cpp
Each commit in the series explains the rationale behind each decision, but nothing scary really.
The main issue area I have is getting the CI itself to bend to my will, so I could need some help here?
- gdb is being janky for the DMD tests (complains about `.x` - I saw before a nonjanky gdb was forced?
- Can't make it "see" FileCheck which breaks the lit tests
Note: due to llvm<16 forcing C++-11 we have to use conditional compilation, otherwise we're trying to
use C++-17 features ..
=> Enable LLVM 16.0.3

.circleci/config.yml
Mac isn't covered by the open-source credit budget, and apparently the monthly 30k credits for these 2 jobs are exhaused rather soon; there hasn't been *that* much activity lately, but the jobs fail to trigger for some days now. On some days, we've apparently reached 8k credits.
The 'Vanilla LLVM' GHA Mac x64 jobs are similar (e.g., testing BUILD_SHARED_LIBS).
=> CircleCI: Remove Mac jobs

.cirrus.yml, .github/workflows/supported_llvm_versions.yml
As preparation for the upcoming resource limits starting in September.
The 'Ubuntu 20.04 x64 multilib rtSanitizers' job was a duplicate of the *Circle* CI one, except for having twice as many CPU cores and using LDC v1.31 as host compiler, not v1.24 like Circle CI.
And bootstrappability from old LDC v1.9.0 can be tested with a 'Vanilla LLVM' GHA job instead.
=> Cirrus CI: Remove 2 jobs

.github/workflows/main.yml, tests/plugins/basic_sema_plugin.d, tests/plugins/visitor_example.d
Fixes #4462 for our official packages.
=> GH Actions: Export ~all symbols from prebuilt LTO'd macOS binaries

CHANGELOG.md, driver/targetmachine.cpp, driver/targetmachine.h, driver/tool.cpp, tests/driver/riscv_abi4.d, tests/driver/riscv_abi5.d
=> Default to rv64gc on riscv64 [slightly revised]

CHANGELOG.md, driver/targetmachine.cpp, driver/targetmachine.h, driver/tool.cpp, tests/driver/riscv_abi4.d, tests/driver/riscv_abi5.d
=> Default to rv64gc on riscv64

gen/mangling.cpp, tests/dmd/runnable/test23343.c
These are apparently used in the Mac system headers. Fixes https://github.com/ldc-developers/ldc/issues/4485.
=> ImportC: Support weird `asm("_" "<name>")` mangling stuff

packaging/windows_installer.iss
=> Windows installer: Add option to add to *system* PATH in admin install mode

.github/workflows/main.yml, .github/workflows/supported_llvm_versions.yml
This pull request upgrades `actions/checkout` and `actions/cache` in the GitHub Actions workflow file to their latest version.
This upgrade can suppress some warnings during the GitHub Actions CI run (e.g. Node.js deprecation warnings).
=> CI: upgrade GHA steps version

dmd/cond.d, driver/main.cpp, driver/targetmachine.cpp, driver/tool.cpp, gen/abi/abi.cpp, gen/abi/loongarch64.cpp, gen/abi/targets.h, gen/target.cpp, runtime/druntime/src/core/thread/osthread.d, tests/driver/loongarch64_abi.d
This pull request ports the LDC compiler to LoongArch64 CPU architecture.
LoongArch64 is a new CPU architecture and has been supported by LLVM/Clang since LLVM 16.
You can find more information about this architecture here: https://loongson.github.io/LoongArch-Documentation/README-EN.html.
------
The port for D runtime is also in progress at https://github.com/dlang/dmd/pull/15628.
=> Add initial support for LoongArch64

driver/timetrace.d
As it's likely to contain backslashes on Windows (argv[0]). Fixes #4506.
=> Time trace: JSON-escape process name

gen/passes/GarbageCollect2Stack.cpp, tests/codegen/gh4510.d
This fixes #4510.
LLVM RAII helper did not fit in case, at https://github.com/ldc-developers/ldc/commit/1d969cfccaf7181b5760a0ae7cd6088a36e3de44.
=> Fix a regression in gc2stack optimization

CHANGELOG.md, gen/abi/abi.cpp, tests/compilable/gh4489.d
An assertion already makes sure we don't. Fixes #4489.
=> ABI: Don't rewrite HFVAs if there's no need to

CHANGELOG.md, driver/cl_options_instrumentation.cpp, driver/cl_options_instrumentation.h, gen/functions.cpp, gen/optimizer.cpp, tests/PGO/sample_based.d
Resolves issue #4527
~~Still a work in progress because I am not sure if it really works: IR output of the testcase shows `!30 = !{!"function_entry_count", i64 -1}` for `foo`, whereas I guess it should say 100 instead of -1.~~  Fixed it, debug line info is needed for actual use ofcourse! (`-gline-tables-only` suffices).
=> Add -fprofile-sample-use

driver/targetmachine.cpp
This also fixes these annoying linker warnings:
`ld: warning: no platform load command found in 'libphobos2-ldc.a[113](core.o)', assuming: macOS`  #4501
=> We have to explicitly set the OS version on newer macOSes to support LTO

driver/toobj.cpp
The `.data()` method on a `StringRef`, returns a `const char*` to the first character but there is no guarantee that the string is null terminated.
In order to get a proper null terminated string it is necessary to use `.str()` which will return a C++ `std::string` which provided the `.c_str()` method to get the null terminated C string.
The invalid behavior can be seen by running (where the user doesn't have acces to the `inaccessible` folder):
```
$ ldc2 <<< '' - -od=inaccessible/impossible
Error: failed to create output directory: inaccessible/impossible/__stdin_4416.o
```
The error message should only include `inaccessible/impossible`.
=> driver/toobj.cpp: writeModule: don't use StringRef::data to get a c_str

.github/actions/3-build-cross/action.yml, .github/actions/merge-macos/action.yml, .github/workflows/main.yml, driver/targetmachine.cpp, tests/compilable/gh4489.d
=> CI: Always include macOS version in explicit triples

CMakeLists.txt
NDEBUG needs to be correctly set depending on how LLVM is built. This commit moves -{D,U}NDEBUG from EXTRA_CXXFLAGS to LDC_CXXFLAGS as LDC_CXXFLAGS is already used for everything that links with LLVM and should be a better place to pass this.
Suggested by Martin Kinkelin in
https://github.com/ldc-developers/ldc/pull/4574
Fixes #4573.
=> CMake: Pass NDEBUG through LDC_CXXFLAGS rather than EXTRA_CXXFLAGS

driver/cpreprocessor.cpp, driver/linker-gcc.cpp, driver/toobj.cpp, driver/tool.cpp, driver/tool.h, tests/driver/cli_CC_envvar.d
In case CC is set try to split it by spaces into a command and arguments. This is the same behaviour as in dmd.
=> support CC envvar to be in the form "command args..."

dmd/builtin.d, dmd/declaration.h, dmd/dtemplate.d, dmd/func.d, gen/llvmhelpers.cpp, gen/pragma.cpp, gen/tocall.cpp
Using `mangleOverride` directly instead. Also get rid of superfluous string copies. And for `LLVMatomic_rmw`, don't store the operation string in the instantiated FuncDeclarations anymore, but fetch it from the parent TemplateDeclaration.
=> Refactor away LDC-specific `FuncDeclaration::intrinsicName`

runtime/druntime/src/core/thread/osthread.d
This pull request adds LDC-specific inline-assembly-based MIPS64 N64 OS thread implementation to replace the broken generic implementation.
=> runtime: add osthread implementation for MIPS64 N64 ABI

cmake/Modules/ExtractDMDSystemLinker.cmake
When it is at the end of the list, there is no `;`. This regex change fixes that.
=> Fix -target/-arch link flag detection

cmake/Modules/FindLLVM.cmake, driver/archiver.cpp, driver/codegenerator.cpp, driver/targetmachine.cpp, driver/targetmachine.h, driver/toobj.cpp, gen/arrays.cpp, gen/dibuilder.cpp, gen/llvmhelpers.cpp, gen/ms-cxx-helper.cpp, gen/optimizer.cpp, gen/optimizer.h, gen/pgo_ASTbased.cpp, gen/tocall.cpp, gen/toconstelem.cpp, gen/tollvm.cpp, gen/tollvm.h, gen/trycatchfinally.cpp, gen/uda.cpp, runtime/druntime/src/ldc/intrinsics.di, tools/ldc-profdata/llvm-profdata-18.1.cpp, utils/FileCheck-18.cpp
This pull request adds LLVM 18.1.x support to LDC.
LLVM recently switched to a new versioning scheme, where LLVM 18.1.0 was the first stable release of LLVM 18 series.
Aside from the usual API renaming, `zext` can not be used directly now and needs to be utilized through a constant folding mechanism.
=> tree-wide: port LDC to LLVM 18

gen/classes.cpp, gen/classes.h, gen/dvalue.cpp, gen/dvalue.h, gen/ms-cxx-helper.cpp, gen/toir.cpp, tests/codegen/devirtualization_assumevtable.d, tests/codegen/inlining_leakdefinitions.d
Assumptions added:
- class methods do not change the object's vtable pointer
- loads through vtable pointer are invariant (vtables are immutable throughout program life)
Examples of the improvement in devirtualization:
```d
class A {
void foo();
void oof();
}
void ggg() {
A a = new A();
a.foo();  // was already devirtualized
a.foo();  // devirtualized by this PR
}
void exacttypeunknown(A a, A b) {
a.foo();
a.foo(); // no vtable lookup, PR removes 2 memory reads
}
```
=> Add memory invariant assumptions for virtual calls to improve devirtualization

gen/uda.cpp, tests/codegen/attr_target_overrides_mattr_x86.d, tests/codegen/attr_target_x86.d
If a target feature has been specified both in source code through `@target` and on the command line through `-mattr` let the former overwrite the latter.
Reported first as https://github.com/libmir/mir-ion/pull/46 there is an inconsistency to how `@target` is handled that can lead to ugly errors during compilation.
Assuming the file:
```d
import ldc.attributes;
import ldc.intrinsics;
pragma(LDC_intrinsic, "llvm.x86.avx2.pshuf.b")
__vector(ubyte[32]) avx2_pshuf_b(__vector(ubyte[32]), __vector(ubyte[32]));
@target("avx2")
void foo () {
__vector(ubyte[32]) x;
x = avx2_pshuf_b(x, x);
}
void main() {}
```
Currently, compiling it with `ldc2 -mattr=-avx2` results in:
```
LLVM ERROR: Cannot select: 0x563de78b7350: v32i8 = X86ISD::PSHUFB 0x563de78b70b0, 0x563de78b7190
0x563de78b70b0: v32i8,ch = …
```
=> Allow `@target` attribute to overwrite global attributes.

.github/actions/3-build-cross/action.yml, .github/actions/3-build-cross/android-llvm-config.in, .github/actions/5a-android-x86/action.yml, .github/workflows/main.yml, CHANGELOG.md, driver/linker-gcc.cpp, driver/main.d, driver/targetmachine.cpp, runtime/CMakeLists.txt, runtime/druntime/src/core/sys/posix/dlfcn.d, runtime/druntime/src/rt/sections.d, runtime/druntime/src/rt/sections_android.d, runtime/druntime/src/rt/sections_elf_shared.d
=> Android: Switch to native ELF TLS & latest LTS NDK, and enable shared druntime/Phobos

runtime/druntime/src/core/sys/posix/config.d
```bash
$ /opt/bin/ldmd2 --version | head -n 8
LDC - the LLVM D compiler (1.38.0-git-bc00d4b):
based on DMD v2.108.0 and LLVM 17.0.5
built with LDC - the LLVM D compiler (1.33.0)
Default target: x86_64-alpine-linux-musl
Host CPU: znver3
http://dlang.org - http://wiki.dlang.org/LDC
$ /opt/bin/ldmd2 -run hellod-sample.d 
/usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /opt/lib/libdruntime-ldc.a(fiber.o): in function `_D4core6thread5fiber5Fiber10allocStackMFNbmmZv':
fiber.d:(.text._D4core6thread5fiber5Fiber10allocStackMFNbmmZv+0x7d): undefined reference to `mmap64'
/usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /opt/lib/libdruntime-ldc.a(os.o): in function `_D4core8internal2gc2os10os_mem_mapFNbNimbZPv': …
```
=> Musl Clean

driver/tool.cpp
This PR prevents LDC from clobbering an already-set-up MSVC environment that targets AArch64 or ARM, addressing https://github.com/ldc-developers/ldc/issues/4624.
It doesn't add the ability to automatically set-up an MSVC environment for targeting AArch64 or ARM when that's what LDC is targeting, but not clobbering existing environments is a nice improvement.
=> Handle already-set-up MSVC environments targeting AArch64/ARM.

gen/asm-x86.h, gen/asmstmt.cpp, tests/compilable/c_masm.c
DMD recently gained support for case-insensitive DMD-style inline assembly, for ImportC, when targeting Windows: https://github.com/dlang/dmd/pull/15595
This PR replicates that support in LDC.
=> Support case-insensitive DMD-style inline assembly.

gen/asm-x86.h, tests/codegen/dmd_style_asm_with_variable_and_offset_memory_reference.d
This is a bodge.
See issue https://github.com/ldc-developers/ldc/issues/2257 and the comments in the code for more context.
But, in short: where now we generate `4+$0` which would expand to `4+someGlobalVariable`, or `4+16(%ebp)`, or `4+(%ebp)` (invalid), we instead generate `4-8+${0:H}` which would expand to `4-8+8+someGlobalVariable`, or `4-8+24(%ebp)`, or `4-8+8(%ebp)` (valid).
The `H` modifier applies the +8 offset unconditionally: https://github.com/llvm/llvm-project/blob/330d8983d25d08580fc1642fea48b2473f47a9da/llvm/lib/Target/X86/X86AsmPrinter.cpp#L405-L406
=> Fix issue #2257: LLVM does not accept generated inline assembly with variable+offset

driver/cpreprocessor.cpp, tests/driver/clang-cl-target-forwarding.d
This PR propagates the target to `clang-cl` when it's used to preprocess C, addressing https://github.com/ldc-developers/ldc/issues/4626.
`clang-cl` doesn't seem to support `-mcpu=` nor `-mtune=`, and `-march=` can't be used in their place for AArch64/ARM targets.
So, to ensure the features of LDC's targeted CPU are propagated, every processor feature gets forwarded on via the `-target-feature` option—the downside of this being that it generates a massive command-line: the longest being 11,691 characters just for the target-features when targeting AArch64, which is a non-negligible contribution to Windows' limit of 32,766 UTF-16 code-units for a command-line, but there are only four paths in the command so I think it should be fine.
=> Propagate the target to `clang-cl` when it's used to preprocess C.

gen/functions.cpp, tests/codegen/dmd_style_asm_in_inline_c_function.c, tests/codegen/inputs/inlinables_asm.d, tests/codegen/ldc_style_asm_in_inline_d_function.d, tests/fail_compilation/dmd_style_asm_in_inline_d_function.d
This PR makes it so the inline attribute is ignored for functions which contain DMD-style inline assembly (as such functions are always made never-inline), addressing issue https://github.com/ldc-developers/ldc/issues/4630.
This is what DMD does, and this makes it possible to compile third-party code which has inline functions with DMD-style inline assembly (e.g. `windows.h`).
=> Avoid setting always-inline for functions that contain DMD-style inline assembly.

driver/main.cpp, runtime/druntime/src/core/stdcpp/new_.d
With the current switch to NDK 26+ it should now be safe to assume the Clang C++ mangling/runtime.
The background for adding this is that the BindBC bindings currently error out when building for Android, because they require a C++ runtime version in order to potentially perform some manual symbol mangling.
=> Define CppRuntime_Clang when building for Android

tests/instrument/lit.local.cfg, tests/sanitizers/lit.local.cfg
In case compiler-rt libs are not available, the lit tests would fail. This extra checking should help in that case.
=> lit: check more carefully if compiler-rt support is there for ASan/MSan/XRay/... testing

tests/dmd/dshell/cpp_header_gen.d, tests/dmd/dshell/dll_cxx.d, tests/dmd/tools/d_do_test.d, tests/dmd/tools/dshell_prebuilt/dshell_prebuilt.d
Clang makes a distinction between clang and clang++. In particular, clang++ will give a warning when it is passed .c source files; and the extra output warning text means that dmd testsuite output checking fails. The warning can be silenced (-Wno-deprecated) but then other tests will fail because #ifdef __cplusplus will be true, leading to header file import issues.
Cherry-pick from https://github.com/dlang/dmd/pull/16434  +  extra LDC-specific changes
(I ran into this issue during Alpine MUSL LDC work, and also when explicitly setting CC=clang++ on macOS. With this PR, CC=clang CXX=clang++ works)
=> Make distinction between CC and CXX in the testsuite

.github/actions/1-setup/action.yml, .github/workflows/main.yml
Using the new CI runners (awesome performance!).
=> GHA: Promote macOS-arm64 cross-compilation job to full native job

.cirrus.yml, .github/workflows/supported_llvm_versions.yml, runtime/druntime/src/core/thread/fiber.d
Related to https://github.com/ldc-developers/ldc/issues/4613
@kinke I think it is better to disable individual unittests like this, than to disable the whole file in the CI script. I spent quite some time on trying to debug this failing test, thinking it was due to musl libc, but instead I found out from #4613 that it is a general AArch64 issue (indeed, also fails on my mac). I would have liked to see that in the source file, rather than hidden in CI configuration. Similar to how we tag known failures of a lit tests inside that actual lit test. This simply ensures that users (and I ;-)) can expect to successfully run the testsuite as normal (without having to know an exclude list).
=> Fix crashing core.thread.fiber unittest for AArch64.

tests/codegen/inputs/mangling_definitions.d, tests/codegen/mangling.d
The test `codegen/mangling.d` has been failing for me on x86 with a segmentation fault because of stack corruption due to the function: https://github.com/ldc-developers/ldc/blob/93afbfa5e2c22d89e54cb45f588474cc6e3a2595/tests/codegen/inputs/mangling_definitions.d#L49
not respecting the stdcall convention which is set as the default for functions with D linkage on x86.
I've tried to fix this by changing the default calling convention for naked assembly functions on x86 and adding an attribute in the `mangling.d` file to specify the C calling convention.
I'm not sure how this test has been passing on windows x86.
=> Fix `tests/codegen/mangling.d` on x86

tests/codegen/casm.c, tests/codegen/casm.i
This test may fail on x86 because, when calling the C preprocessor, ldc will append a -m argument based on the target. If the target is x86_64 and the host is x86 the C compiler may fail with:
```
cc1: error: CPU you selected does not support x86-64 instruction set
```
An easy solution for this is to specify i386 instead of x86_64 in the target triple.
I'm not 100% sure if the `-mtriple` argument can be just dropped so I went ahead with a more conservative fix.
=> tests/codegen/casm.c: Move to casm.i to avoid calling the preprocessor

gen/abi/loongarch64.cpp, runtime/druntime/src/core/thread/fiber.d, runtime/druntime/src/core/threadasm.S
This PR fixes support for LoongArch so that it can run on LoongArch systems.
=> Fix LoongArch support

gen/llvmhelpers.cpp, gen/runtime.cpp
ldc2 returns SIGSEGV instead of SIGABRT for any value of
assert in betterC (or -checkaction=C or defaultlib="" ...)
due to some improper usage of __assert. As per the C compilers,
(gcc, clang, etc.), __assert_fail should be used for C asserts.
See my related PR for DMD:
https://github.com/dlang/dmd/pull/16515
=> Fix glibc assert: __assert -> __assert_fail

.cirrus.yml
The old one cannot be used at the moment, although 13.2 is supposed to be supported until the end of June according to freebsd.org.
=> Cirrus CI: Bump FreeBSD image from v13.2 to v13.3

runtime/druntime/src/ldc/eh_msvc.d
…from VS 17.11
I'm using the preview version of VS, I hope this is compatible with VS 17.10.
=> fix exception unwinding with libcmtd.lib/vcruntime140d.dll 14.40.x

gen/abi/abi.cpp, tests/dmd/runnable/extra-files/cpp_nonpod_byval.cpp, tests/dmd/runnable/nonpod_byval.d
Fixes issue #4679. The test updates originate from https://github.com/dlang/dmd/pull/16570.
=> MSVC++ ABI: Fix POD semantics special case

gen/runtime.cpp
Introduced in #4667 and reported in the announce dlang forum.
=> Fix C-assert regression for MinGW targets

.github/workflows/alpine_musl.yml, driver/linker-gcc.cpp, runtime/druntime/src/core/sys/posix/sys/statvfs.d, tests/dmd/CMakeLists.txt
Separate PRs to enable musl:
Upstream PRs:
=> Add musl libc CI using Alpine Linux container on Ubuntu GHA

tests/plugins/lit.local.cfg
.../tests/plugins/lit.local.cfg:23: SyntaxWarning: invalid escape sequence `\(`
A plain `\` is used to escape a character in a string so one needs `\\` to escape a character in a regex. The check worked correctly otherwise, this just fixes the warning.
=> tests/plugins/lit.local.cfg: Properly escape regex

CHANGELOG.md, gen/dvalue.cpp, gen/toir.cpp, ir/iraggr.cpp, ir/irtypeaggr.cpp, tests/compilable/gh4646.d
=> Fix bit field IR storage from weird integer to i8 array

.github/actions/3-build-cross/action.yml, CHANGELOG.md
See https://github.com/android/ndk/wiki/Changelog-r27.
=> Bump used Android NDK to r27

runtime/CMakeLists.txt
Sometimes CMake silently(!) ignores `.S` (asm) files if ASM isn't mentioned in the project directive. I ran into it during build my custom non-posix && non-windows target. It was very hard to understand what is happens
Similar issue: https://stackoverflow.com/questions/23452089/why-is-cmake-ignoring-assembly-files-when-building-static-library/67902603#67902603
=> druntime: adds ASM language to cmake project() directive

ir/irtypeaggr.cpp, tests/codegen/gh4719.d, tests/compilable/gh4719.d
Alternative to https://github.com/ldc-developers/ldc/pull/4720
=> AggrTypeBuilder: mark aggregate as packed when field offset is not naturally aligned, to fix #4719

driver/linker-msvc.cpp, driver/tool.cpp, driver/tool.h
This happens in an environment where MSVC was set up first (so env var `VSINSTALLDIR` defined), and later prepending a dir such as `C:\Program Files\Git\usr\bin` to PATH, so that the first `link.exe` on PATH isn't the Microsoft one.
=> Windows: Avoid accidentally using GNU link.exe for linking

tools/timetrace2txt.d
Making use of UTF Box drawing characters https://en.wikipedia.org/wiki/Box-drawing_characters  (TIL ;-)
Example:
```
5.348 ╼ ExecuteCompiler, , <no file>
0.934   ├╼ Sema1: Module timetrace2txt_1, , <no file>
0.917   │  ├╼ Sema1: Import object, timetrace2txt_1.object, <no file>
0.917   │  ├╼ Sema1: Module object, , <no file>
0.121   │  │  ├╼ Sema1: Import attribute, __anonymous, /Users/johan/ldc/ldc/runtime/druntime/src/object.d:111
0.120   │  │  │  ╰╼ Sema1: Module core.attribute, , /Users/johan/ldc/ldc/runtime/druntime/src/object.d:111
0.105   │  │  │     ├╼ Sema1: Import attributes, core.attribute.ldc, /Users/johan/ldc/ldc/runtime/druntime/src/core/attribute.d:37
0.104   │  │  │     │  ╰╼ Sema1: Module ldc.attributes, , /Users/johan/ldc/ldc/runtime/druntime/src/core/attribute.d:37
0.006 …
```
=> timetrace2txt: make the text output just a little bit prettier

CHANGELOG.md, driver/configfile.d
Fix https://github.com/ldc-developers/ldc/issues/4714
=> ldc2.conf: %%ldcconfigpath%% support added

.github/workflows/main.yml, CHANGELOG.md, ir/iraggr.cpp, ir/irtype.cpp, ir/irtypeaggr.cpp, ir/irtypeaggr.h, ir/irtypeclass.cpp, ir/irtypeclass.h, ir/irtypestruct.cpp, tests/compilable/gh4734.d
With the nice side-effect of fixing #4734.
=> Get rid of cycles in DtoType()

driver/main.cpp, tests/codegen/xtensa.d
cc @Turkeyman
TODO
- [ x ]  tests
- [ x ] PR for enabling Xtensa in release workflow https://github.com/ldc-developers/llvm-project/pull/2
Druntime C bindings can be done at a later date.
=> [Xtensa] addPredefinedGlobalIdent for Xtensa

driver/ldmd.cpp
=> ldmd2: Don't ignore other flags with `-mcpu=<?|h|help>`

.github/workflows/supported_llvm_versions.yml, CHANGELOG.md, CMakeLists.txt, driver/linker-gcc.cpp, runtime/CMakeLists.txt, runtime/ldc-build-runtime.d.in
Many Linux distributions including [Debian](https://wiki.debian.org/UpstreamGuide#No_inclusion_of_third_party_code), [Fedora](https://docs.fedoraproject.org/en-US/packaging-guidelines/#bundling), and, [Gentoo](https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies), have a policy of unbundling 3rd party dependencies like zlib from software projects. This PR implements support for this so that distributions don't have to implement the same logic individually.
Currently Debian does [remove](https://salsa.debian.org/d-team/ldc/-/blob/93f0e1ea7893eaee408ac9d3c9716d1c31a87bd3/debian/patches/01_no-zlib-embed.patch) the zlib code but they leave the static variants of libphobos with undefined symbols to zlib functions making `-link-defaultlib-shared=false` require the additional `-lz` switch …
=> Support building phobos against a system copy of zlib

CHANGELOG.md, driver/main.cpp, tests/codegen/emscripten.d
Based on https://github.com/ldc-developers/ldc/pull/4738.
=> Emscripten: Predefine versions as for a regular musl Linux platform

.github/actions/helper-build-ldc/action.yml, .github/workflows/main.yml, .github/workflows/supported_llvm_versions.yml, runtime/CMakeLists.txt, runtime/DRuntimeIntegrationTests.cmake, runtime/druntime/test/common.mak, runtime/druntime/test/shared/Makefile, runtime/druntime/test/stdcpp/Makefile, runtime/ldc-build-runtime.d.in
Based on https://github.com/ldc-developers/ldc/pull/4743.
=> Better support building the runtime separately [mod]

runtime/CMakeLists.txt, runtime/DRuntimeIntegrationTests.cmake
My use case for this is compiling the runtime for x86 on x86_64. `-DMULTILIB=ON` is not sufficient as I need to create a separate project in order to use a system copy of zlib like I've described in https://github.com/ldc-developers/ldc/pull/4742#issue-2489471216.
=> Better support building the runtime separately

gen/abi/abi.cpp, gen/abi/targets.h, gen/abi/wasm.cpp, gen/target.cpp, tests/codegen/emscripten.d
To resolve #4757 and make our wasm ABI a bit more compatible with clang/emscripten's. This includes switching to 128-bit `real`.
=> wasm: Add a preliminary TargetABI implementation

.github/workflows/main.yml
macos-12 will be deprecated soon: https://github.com/actions/runner-images/issues/10721
=> Migrate from macos-12 to macos-13 for Github Action main build on macOS x86_64.

CHANGELOG.md, dmd/expressionsem.d, dmd/target.d, tests/codegen/vector_ops.d
=> Promote shift RHS to vectors if needed

tools/update-dmd-rewrite.sh
The default replacement of commit refs from original to rewritten hash seems to hick up occasionally for one commit, not always replacing the original hash. I've now hit this two or three times for a recent-ish DMD master commit, which was cherry-picked to stable upstream. Replace the hash manually to the correct one (in our dmd-rewrite-master branch).
=> update-dmd-rewrite.sh: Work around filter-repo weirdness

driver/cl_options_sanitizers.cpp, driver/cl_options_sanitizers.h, driver/linker-gcc.cpp, gen/optimizer.cpp, tests/sanitizers/asan_recover_stackoverflow.d
Resolves #4770
Note that env variable setting `ASAN_OPTIONS=halt_on_error=false` is needed to actually recover from failures (executables built with clang behaves the same).
=> Implement -fsanitize-recover for ASan and MSan.

packaging/dub_version, packaging/reggae_version
Incl. reggae to a version which uses that dub (https://github.com/atilaneves/reggae/pull/315).
The dub regression was https://github.com/dlang/dub/issues/2973.
=> Bump bundled dub to latest stable with crucial regression fix

ir/irclass.cpp, tests/codegen/gh4790.d
I.e., ignore all modifiers of the base class.
=> Fix #4790: Make sure `TypeInfo_Class.base` is always a `TypeInfo_Class` ref

CHANGELOG.md, driver/configfile.d
Hi, this introduces a placeholder for `ldc2.conf` which is set to the version of LDC.
The rationale is: when following the "Cross-compiling with LDC" on a linux system, according to section "Default libraries", it is required to download prebuilt runtimes of the version matching the host compiler.
Since the host compiler is subject to system updates, I might find myself in a situation of version mismatch if I forget to update target libraries.
Favoring versioned directories may work as a preventive measure against such cases.
```
lib-dirs = ["/opt/ldc2-%%ldcversion%%-windows-multilib/lib64"];
```
=> Add configuration placeholder %%ldcversion%%

gen/dibuilder.cpp, gen/dibuilder.h
A couple of days ago I added support to mago to evaluate the `__debugOverview`, `__debugExpanded` and `__debugStringview` hooks as free functions instead of struct members (see https://rainers.github.io/visuald/visuald/Debugging.html#customization). Apart from allowing to add debug visualizers for library types without editing the source, I hoped to also have LDC support this feature even though it omits class and struct members in the debug info. Here's a tiny example:
```D
struct String
{
string _s;
}
string __debugOverview(const String* s)
{
return s._s;
}
```
Unfortunately, LDC omits the function parameters from the function type, but they are needed for overload resolution. This a small patch to add these. It also ticks off one item of …
=> add debug info for function parameter types

CHANGELOG.md, gen/modules.cpp
This pull request fixes control-flow protection attribute marking by explicitly replacing the old values to avoid an LLVM assertion.
This can happen when compiling multiple D source files in one command line invocation.
=> gen: fix control-flow protection attribute marking

runtime/druntime/test/shared/Makefile
I think this was fixed in `rt.sections_elf_shared` at one point.
=> druntime: Enable 'host' shared integration test on Darwin

CHANGELOG.md, CMakeLists.txt, driver/main.cpp, driver/targetmachine.cpp, gen/abi/ppc64le.cpp, gen/modules.cpp, gen/target.cpp, gen/toir.cpp, ldc2.conf.in, ldc2_install.conf.in, ldc2_phobos.conf.in, runtime/druntime/src/core/atomic.d, runtime/druntime/src/core/stdc/config.d, runtime/druntime/src/core/stdc/math.d, runtime/druntime/src/core/stdc/stdio.d, runtime/druntime/src/core/stdc/stdlib.d, runtime/druntime/src/core/thread/fiber.d, tests/driver/ppc_float_abi.d
This pull request adds an option to use IEEE long double ABI on Linux (if the host environment supports it).
Some adjustments are made to accommodate the new ABI (glibc uses dual-ABI in this case, where new IEEE long double-capable functions are suffixed with `__ieee128`; older functions using IBM long double are also kept for compatibility reasons).
=> ppc64(le): Add an option to use IEEE long double ABI on Linux

CHANGELOG.md, dmd/root/longdouble.d, gen/abi/aarch64.cpp, gen/target.cpp, runtime/druntime/src/__importc_builtins.di, runtime/druntime/src/core/internal/vararg/aarch64.d, runtime/druntime/src/core/stdc/math.d, runtime/druntime/src/core/stdc/stdarg.d, runtime/druntime/src/core/sys/windows/dll.d, runtime/druntime/src/core/sys/windows/stacktrace.d, runtime/druntime/src/core/sys/windows/threadaux.d, runtime/druntime/src/core/sys/windows/winnt.d, runtime/druntime/src/core/thread/fiber.d, runtime/druntime/src/core/thread/osthread.d, runtime/druntime/src/ldc/eh_msvc.d, runtime/druntime/src/object.d, runtime/druntime/src/rt/dso.d
This allows to build and run the runtime with ldc-build-runtime and option `-march=arm64` on Windows on ARM. The compiler used is the one for x64 (it shows some floating-point inaccuracies in the x86-emulator).
All druntime unittests pass but the two disabled ones involving chained exceptions in fibers.
In phobos a std.process test fails (but also for emulated x64) and a tests in std.outbuffer indicates that there is still an issue with va_arg handling. Without a curl build, the respective tests fail, too.
I haven't yet managed to run the compiler test suite on the ARM machine.
=> run on and build for Windows on ARM64

tests/dmd/compilable/stdcheaders.c
As used by GHA in their latest `windows-2022` image.
=> Fix compilable/stdcheaders.c regression with latest MSVC v17.13 headers

.circleci/config.yml, .cirrus.yml, .github/actions/4d-test-libs/action.yml, .github/workflows/supported_llvm_versions.yml
I've seen them hanging yesterday for Linux aarch64 GHA, still running that step after 17 mins.
=> CI: Prevent hanging druntime/Phobos unit/integration tests

.github/actions/1-setup/action.yml, .github/actions/5a-ios/action.yml, .github/workflows/main.yml
To fix weird issues without LTO and/or with mimalloc, like the dreaded `libc++abi: Pure virtual function called!` errors and unwinding segfaults for the `driver/config_diag.d` lit-test.
=> GHA macOS x86_64: Use LDC v1.35.0 as host/bootstrap compiler with Xcode-matching LLVM

driver/linker-gcc.cpp
wasm-ld and lld::wasm don't understand the -rpath argument.
=> driver/linker-gcc.cpp: Don't pass -rpath to linker on wasm targets

.github/actions/2-build-bootstrap/action.yml, .github/workflows/main.yml, CHANGELOG.md, tests/dmd/fail_compilation/needspkgmod.d
Incl. enabling C++ LTO for the compiler, as well as PGO (although I'm not sure PGO really works; >1k warnings wrt. changed function control flows... **edit**: oh well, looks like those are for the `ldc2-unittest` object file only).
=> CI: Bump Alpine image to v3.21

.github/actions/merge-windows/action.yml
To keep the archive unpackable with 7-Zip < v23.00, working around https://github.com/dlang-community/setup-dlang/issues/86 etc.
=> Windows multilib package: Disable ARM64 7-Zip filter

.cirrus.yml
The lit-tests fail with LLVM 19 and 18 (PGO and sanitizer issues), so sticking with LLVM 15.
=> Cirrus CI: Adapt to FreeBSD bumping default LLVM from 15 to 19

.github/actions/5-install/action.yml, .github/workflows/main.yml
By installing the bootstrap compiler and using its imports.
=> GHA: Simplify gathering the bundled imports for cross-compiled packages

driver/config.d, driver/configfile.d, tests/driver/config_append_assign.d, tests/driver/config_diag.d, tests/driver/inputs/appending_assign.conf, tests/driver/inputs/invalid_append.conf
The main goal that I'm trying to achieve with these changes is getting better support for building the compiler and the runtime separately (since that's what I rely upon). Fully doing this, however, is somewhat complicated so I'm trying to do it bit by bit.
In this PR I've implemented:
- The `~=` operator in ldc2.conf
- ldc2.conf being a directory
- some cmake refactors
The reasoning for this is that both the compiler and the runtime have some sort of switches that they want to encode so, if they are built separately, they can only install (at least) 2 separate files. The `~=` operator is mostly a convenience but it is sometimes useful to be able to append a flag without having to copy all of the default ones.
This also has the nice benefit of making the cmake code a little more cleaner …
=> ldc2.conf: Implement `~=` concatenating operator

.github/actions/5a-ios/action.yml, .github/actions/merge-macos/action.yml, .github/actions/merge-windows/action.yml
* Use the new ~= operator to de-duplicate switch `"-defaultlib=phobos2-ldc,druntime-ldc"`
* Windows multilib: minimize extra sections
=> GHA: Slightly de-uglify ldc2.conf for prebuilt packages supporting multiple targets

.github/actions/4c-test-dmd/action.yml, CHANGELOG.md, gen/functions.cpp, tests/codegen/attr_targetoptions.d, tests/codegen/exception_stack_trace.d, tests/codegen/frame_pointer_x86.d, tests/codegen/vector_abi_x86.d, tests/dmd/runnable/test17559.d, tests/dmd/runnable/test19086.d, tests/sanitizers/fuzz_asan.d
Primarily to fix (druntime) backtraces with optimized code for those targets, incl. prebuilt release druntime/Phobos.
Fixes #4594 and #4694.
=> Keep frame pointers by default with -O for some targets

.github/actions/3-build-cross/action.yml, .github/actions/5-install/action.yml, .github/actions/5a-android-x86/action.yml, .github/actions/5a-ios/action.yml, .github/actions/7-package/action.yml, .github/actions/merge-windows/action.yml, CHANGELOG.md, runtime/CMakeLists.txt, runtime/ldc-build-runtime.d.in
To simplify copying the libraries to an existing LDC installation.
=> ldc-build-runtime: Add `--installWithSuffix` option

.github/actions/1-setup/action.yml, .github/actions/4b-test-lit/action.yml, .github/actions/4d-test-libs/action.yml, .github/actions/helper-build-gdb/action.yml, .github/workflows/main.yml, CHANGELOG.md
Incl. bumping the min glibc version for the prebuilt Linux packages.
=> GHA: Bump ubuntu-20 jobs to ubuntu-22

.github/workflows/main.yml, CMakeLists.txt, runtime/CMakeLists.txt
New CMake 4 dropped support for < 3.5, breaking our CI (GHA at least). LLVM 19 requires v3.20. Ubuntu 20 came with v3.16.
=> Bump min required CMake version from v3.4.3 to v3.16.0

.github/workflows/main.yml
But keep using Xcode v16 (the default version for macos-15), not v15.4.
=> GHA: Downgrade macos-15 image to macos-14, to work around macOS v15.4 breakage

gen/abi/aarch64.cpp, gen/abi/abi.cpp, gen/abi/abi.h, gen/abi/arm.cpp, gen/abi/nvptx.cpp, gen/abi/ppc.cpp, gen/abi/ppc64le.cpp, gen/abi/riscv64.cpp, gen/abi/spirv.cpp, gen/abi/win64.cpp, gen/abi/x86-64.cpp, gen/abi/x86.cpp, gen/functions.cpp, gen/moduleinfo.cpp, gen/modules.cpp, gen/runtime.cpp
Based on the clang 19 logic (but not 100% accurate).
There's an interesting special case - Darwin on arm64 apparently uses *synchronous* tables.
=> Revise unwind-table emission, enabling them for most popular targets

.circleci/config.yml, .cirrus.yml, CMakeLists.txt, tools/CMakeLists.txt
The default LLVM version on FreeBSD Ports was switched to 19 a while ago. Current LDC bootstraps gets build against 15, which forces the port to pull in two LLVM versions, 15 and 19, at the same time.
=> Switch FreeBSD CI to LLVM 19

.cirrus.yml, .github/actions/4d-test-libs/action.yml, .github/workflows/supported_llvm_versions.yml
https://github.com/dlang/phobos/issues/10730
=> CI: Disable newly flaky `std.experimental.allocator.building_blocks.allocator_list` unittests on macOS and FreeBSD

.github/actions/helper-build-ldc/action.yml, .github/workflows/supported_llvm_versions.yml, CMakeLists.txt, cmake/Modules/BuildDExecutable.cmake, runtime/DRuntimeIntegrationTests.cmake
See https://cmake.org/cmake/help/latest/policy/CMP0132.html.
=> macOS: Fix #3901 - CMake quirks on macOS wrt. CMAKE_C[XX]_COMPILER

.github/actions/1-setup/action.yml, .github/actions/3-build-native/action.yml, .github/actions/7-package/action.yml, .github/workflows/main.yml, CMakeLists.txt
And the latest stable LDC release as first host compiler.
Fixes #4899 for good.
=> GHA macOS: Enable bootstrap stage again

driver/cl_options_sanitizers.h, gen/abi/aarch64.cpp, gen/classes.cpp, gen/dcompute/druntime.h, gen/dibuilder.cpp, gen/dynamiccompile.cpp, gen/llvm.h, gen/nested.cpp, gen/optimizer.cpp, gen/toir.cpp, gen/variable_lifetime.cpp, ir/irtypefunction.cpp, ir/irtypestruct.cpp, runtime/jit-rt/cpp-so/jit_context.cpp, utils/gen_gccbuiltins.cpp
This pull request adds basic LLVM 20 support for LDC.
LLVM 20 changed a lot of APIs again, especially how passes are structured.
=> Preliminary LLVM 20 support

dmd/cparse.d, driver/cpreprocessor.cpp, runtime/druntime/src/importc.h, runtime/druntime/test/importc_compare/Makefile, tests/dmd/compilable/fix24187.c, tests/dmd/compilable/stdcheaders.c, tests/dmd/compilable/testcstuff1.c, tests/dmd/runnable/test23889.c
Basically an eager cherry-pick of
* https://github.com/dlang/dmd/pull/21371
* https://github.com/dlang/dmd/pull/21370
* https://github.com/dlang/dmd/pull/21372
* https://github.com/dlang/dmd/pull/21391
=> Run C preprocessor in C11 mode

gen/toconstelem.cpp, tests/fail_compilation/gh4938.d
DMD seems to support AddrExp of struct literals only...
=> Fix #4938 - Be stricter wrt. supported AddrExp in toConstElem()

runtime/CMakeLists.txt, runtime/druntime/src/core/thread/fiber/package.d, runtime/druntime/src/core/thread/fiber/switch_context_riscv.S
This code is based on mine [earlier implementation](https://github.com/denizzzka/dfruntime/blob/dfruntime/runtime/druntime/src/core/thread/fiber/switch_context_riscv.S) for `rv32`, so both platforms should be supported: `rv32` and `rv64` with and without compressed instructions and with and without `HardFloat`.
For now it is tested only on `rv64` with `HardFloat` (QEMU, Ubuntu 24.10, `ldc2` from `~master`)
Implemented using separate file because I see potential for growth of this assembly code (I want to implement embedded ISA subset and maybe something vendor-specific), and also to put an end to ~~vicious~~ scaring me  practice of putting assembly code for completely different platforms into one huge .S file
Path to the new asm file is the same as in the current DMD `~master` for …
=> Adds native support for Fiber context switching on RISC-V

gen/abi/nvptx.cpp, gen/abi/spirv.cpp, gen/dcompute/target.h, gen/dcompute/targetCUDA.cpp, gen/dcompute/targetOCL.cpp, gen/functions.cpp, gen/semantic-dcompute.cpp, gen/uda.cpp, gen/uda.h
Needed for Vulkan where information about the number of threads to use is supplied to the attribute.
=> [dcompute] `has`->`getKernelAttr`, return expression literal

.github/workflows/main.yml
Now that we have an LDC v1.41.0 host compiler whose ldmd2 executable works on macOS 15.4.
=> GHA Main: Bump macOS arm64 job to macOS 15 again

CHANGELOG.md, gen/uda.cpp, runtime/druntime/src/ldc/dcompute.d, tests/codegen/dcompute_cl_images.d
This PR does not update the OpenCL nor CUDA backends to their corresponding attributes (`reqd_work_group_size(X, Y, Z)`. This is required for the Vulkan compute backend to function.
=> [dcompute] update `@kernel` UDA, include launch dimension

driver/codegenerator.cpp, driver/targetmachine.cpp, gen/abi/aarch64.cpp, gen/abi/generic.h, gen/classes.cpp, gen/dcompute/druntime.h, gen/dcompute/targetCUDA.cpp, gen/dcompute/targetOCL.cpp, gen/nested.cpp, gen/passes/GarbageCollect2Stack.cpp, gen/passes/SimplifyDRuntimeCalls.cpp, gen/runtime.cpp, gen/tocall.cpp, gen/toir.cpp, gen/variable_lifetime.cpp, ir/irtypeclass.cpp, ir/irtypefunction.cpp, ir/irtypestruct.cpp, runtime/druntime/src/ldc/intrinsics.di
Best reviewed per commit.
I am unsure what the correct value to use for the `llvm::LocationSize` in the case we don't know the size.
There are still a bunch of deprecations from using `InsertPosition` e.g. from `gIR->topallocapoint()` instead of `BasicBlock::iterators` for insertion.
=> Fix a bunch of errors and deprecation for LLVM 21

driver/linker-gcc.cpp
Some projects use the zlib C function directly and, given that those symbols are available when phobos embeds zlib (the default) and when linking the stdlib statically, the projects often don't include a `-lz` in their build settings. This omission then prevents a successful build with PHOBOS_SYSTEM_ZLIB=on and
-link-defaultlib-shared.
Until a permanent decision is made if those projects should change their build scripts or if the compiler should always add `-lz`, add the library anyway, to minimize breakages.
This also makes the behavior consistent with gdc which also adds an unconditional `-lz` when zlib is not embedded.
See-Also: https://github.com/ldc-developers/ldc/pull/4742
=> Add -lz when PHOBOS_SYSTEM_ZLIB=on and -link-defaultlib-shared

.cirrus.yml, .github/actions/3-build-cross/action.yml, .github/actions/5-install/action.yml, .github/actions/5a-android-x86/action.yml, .github/actions/5a-ios/action.yml, .github/actions/5b-make-portable/action.yml, .github/actions/merge-macos/action.yml, .github/actions/merge-windows/action.yml, .github/workflows/main.yml, CHANGELOG.md, CMakeLists.txt, packaging/windows_installer.iss, runtime/CMakeLists.txt, runtime/ldc-build-runtime.d.in
The proposal is to have:
* `00-docs.conf`
* `30-compiler.conf`: 'compiler-specific defaults'
* The main goal is to add the implicit `-I` post-switch(es) (=> min priority as post-switches) for the bundled druntime/Phobos imports.
* Might contain LLVM-version-specific hacks, like the `-func-specialization-size-threshold=1000000000` for LLVM 16.
* Also drags in druntime and Phobos by default (so a normal (pre-)switch, overrideable in a later config file or by the user directly) for linking via `-defaultlib=phobos2-ldc,druntime-ldc`.
* 5X: This is the group for target-specific settings - mainly `lib-dirs` and according `rpath`, as well as potential extra switches (for cross-compilation and/or to default to `-link-defaultlib-shared[=false]` if only one shared/static version of the libs is …
=> ldc2.conf dir: Slightly shuffle order and file names, and make `ldc-build-runtime --installWithSuffix` install a .conf file

.github/actions/5a-android-x86/action.yml, CHANGELOG.md, driver/cpreprocessor.cpp, driver/linker-gcc.cpp, driver/toobj.cpp, driver/tool.cpp, driver/tool.h, tests/driver/cross_cc_fallback.d
When cross-compiling on a non-Apple Posix build machine pick the C cross compiler (when not specified through `$CC` or `-gcc=`) from:
- `<triple>-gcc`
- `<triple>-clang`
- `clang --target=<triple>`
This should be a better UX when cross-compiling with simpler build systems like `dub` or even without one at all, offering a out-of-the-box functional setup, on most systems.
The advantage to performing this check in the compiler code as opposed to hardcoding a default value in the config file is that:
1. Multiple programs can be searched, instead of just one
2. The `$CC` value continues to be respected, which keeps more advanced cross-compiling setups working (for example Meson)
----
A sample implementation of https://github.com/ldc-developers/ldc/pull/4978#issuecomment-3242341965, I haven't …
=> driver: Pick a better default C cross compiler on non-Apple Posix
