gen/dibuilder.cpp
gen/dibuilder.h

This removes a FIXME in dibuilder.

DebugInfo: Add accessibility to member types.

---

driver/toobj.cpp
gen/dibuilder.cpp
gen/optimizer.cpp

Update of PassManager interface to match the corresponding deprecation in LLVM's trunk for 3.7

Update of deprecated PassManager interface

---

gen/dibuilder.cpp
gen/dibuilder.h
gen/module.cpp

- Do not create debug info after we called finalize.
- Clean up debug info generation for module ctor/dtor.
- Rename EmitSubProgramInternal() to EmitModuleCTor().
- Remove unused parameter from CreateTypeDescription().

Several updates to debug info generation.

---

gen/naked.cpp

This only concerns MinGW64.
Currently, naked asm functions [*] get a leading underscore in LLVM IR output. However, the call to the function is using the name without extra leading underscore. This seems to work fine on MinGW32, but gives unresolved symbol linker errors on MinGW64. This PR fixes that.
Together with the PR for druntime, I can now successfully build and execute Hello World!
isWindowsGNUEnvironment()  is true for Mingw32 and Mingw64. Here I added the extra check that the arch is not 64bit, so that the if-statement body (adding a leading underscore) is not executed for Mingw64.
The check for LLVM < 3.5 seems to explicitly check for MinGW32. I have LLVM 3.7 (trunk).
[*] e.g. :
real ldexp(real n, int exp) {
asm {
naked;
push RCX;
...

Do not add leading underscore to naked asm functionname for MinGW64

---

ir/iraggr.cpp
ir/irtypeaggr.cpp

The `union` is not created as packed type. This seems to create problems with the default initializer:
struct Foo
{
static union Bar
{
bool b;
ulong l;
}
Bar bar;
}
static this()
{
Foo foo = Foo();
}
creates an error. If you change the order inside the union
static union Bar
{
ulong l;
bool b;
}
then the code works.
Also cleans up the creation of the additonal zeroes for the initializer.

Fix for issue #841.

---

driver/main.cpp
driver/targetmachine.cpp

Provide versions ARM_SoftFP and D_HardFloat when float-abi is softfp.  Also use same default float-abi selection for thumb as for arm.

Provide version ARM_SoftFP when float-abi=softfp

---

ir/iraggr.cpp

Fixes issue #812 .
I will create a separate PR that adds a testcase to the testsuite. I do not know how to combine PRs across submodules (I actually have to figure out how to effectively work with submodule branches at all...).

Skip erroneous creation of implicit initializers for zero-length array in aggregates

---

runtime/CMakeLists.txt

Have cmake gather D dource from the new phobos subdirectories under std (e.g. std/regex/).
Seems like there could be one recursive glob for everything under phobos/std/ but I went for the existing pattern in CMakeLists.txt.  This should help create more fireworks with #868.

Add new phobos subdirs

---

gen/functions.cpp

The 2.067 front-end doesn't rewrite these to void anymore, so let's rewrite in ```DtoFunctionType()```.
This issue has surfaced in a ```std.conv``` unit test, where ```std.range.primitives.front()``` is instantiated for ```const(void)[]```. The void return expression is swallowed by the front-end, so that ```return a[0];``` is rewritten to an empty ```return;``` statement. Our LL version of the ref-void function returns an i8*...
The ```front()``` template refuses ```void[]``` but accepts this ```const(void)[]```...

Watch out for functions returning "ref void".

---

gen/typinf.cpp

This change prevents a bunch of missing class TypeInfo definitions when linking.
It restores the previous TypeClass::builtinTypeInfo() logic that always returns false (the IN_LLVM path below) for Tclass and puts back in a relevant FIXME comment in case there are still plans to revisit this.
Old version for reference:
```C++
int TypeClass::builtinTypeInfo()
{
/* This is statically put out with the ClassInfo, so
* claim it is built in so it isn't regenerated by each module.
*/
#if IN_DMD
return mod ? 0 : 1;
#elif IN_LLVM
// FIXME if I enable this, the way LDC does typeinfo will cause a bunch
// of linker errors to missing class typeinfo definitions.
return 0;
#endif
}
```

Generate missing TypeInfo initZ symbols

---

gen/toir.cpp

Thereby enabling nested assign/binAssign expressions in left-hand-sides of assign/binAssign expressions as well as taking the address of assign/binAssign expressions (e.g., required to return assign/binAssign expressions by reference).
```D
import core.stdc.stdio;
ref int foo()
{
static int a;
return ++a *= 5;
}
void main()
{
int a = foo();
printf("%d\n", a);
int b = 0;
((++b *= 5) *= 2) += 3;
printf("%d\n", b);
b = 0;
((++b *= 5) *= 2) += ++b * b;
printf("%d\n", b);
b = 0;
((++b *= 5) *= 2) += ++b * (b -= 6);
printf("%d\n", b);
b = 0;
(((b = 1) *= 5) *= 2) = b - 1;
printf("%d\n", b);
}
```
yields
```
5
13
131
65
9
```

Descend to nested lvalue for assign, binAssign and address-of expressions.

---

gen/llvmhelpers.cpp
gen/llvmhelpers.h
gen/runtime.cpp
gen/toir.cpp

As long as the struct has a dtor, otherwise continue forwarding to `_d_delmemory()`.
I've also refactored the `DtoDelete*()` helper functions to take D values instead of LL ones, so that the caller doesn't need to know whether to pass in a LL lvalue or rvalue.

Call _d_delstruct() runtime function when deleting struct pointers.

---

gen/llvmhelpers.cpp
gen/toir.cpp

Runtime function `_d_delarray_t()` expects the `TypeInfo_Struct` argument to be null if the struct has no dtor.
This fixes `runnable/hospital.d`, which deletes a dynamic array of class handles (i.e., we've previously cast the element's ClassInfo to a TypeInfo_Struct and then attempted to call the StructInfo's xdtor (luckily mapping to the ClassInfo dtor apparently), additionally with an incorrect pointer argument... ;)). This patch only deletes the memory allocated for the handles and doesn't destruct the actual class instances!
For `hospital.d`, it doesn't matter as the class has no dtor.
There seem to be more GC related issues uncovered by the `rt.lifetime` tests. E.g., `GC.runFinalizers()` won't invoke dtors of structs allocated on the heap and probably neither those of class objects. …

Don't try to invoke non-existent dtors when deleting dynamic arrays.

---

gen/llvmhelpers.cpp
gen/llvmhelpers.h
gen/runtime.cpp
gen/toir.cpp

This is required for the GC to be able to call their dtors, if need be (by appending a `TypeInfo` pointer after the actual struct in case the struct has a dtor).
`_d_newitemT()` / `_d_newitemiT()` also perform the initialization, so we don't need to take care of that in `toir.cpp` anymore.

Allocate structs on the heap via runtime function _d_newitem.

---

driver/main.cpp

If several modules are linked together, an empty module is used as
target. Starting with LLVM 3.6, there seems to be a slight difference
between an empty module and a module with IR.
The PR uses always the first module as the target. This has the nice
side effect that we are no longer affected by LLVM bug 11479.

Fix for issue #855.

---

dmd2/cppmangle.c
gen/naked.cpp

Please consider this change. This PR removes the extra underscore in mangled symbols on OSX. The specific test that fails without this change is runnable/cppa.d.

Fix linking errors of export(cpp) symbols on OSX.

---

driver/cl_options.cpp
driver/ldmd.cpp

Implement dmd `-verrors` option in ldc2 and ldmd2.  This also fixes the dmd-testsuite failures that use `-verrors` missing.

Add new dmd -verrors option

---

dmd2/mars.h
dmd2/module.c
dmd2/module.h
driver/cl_options.cpp
driver/ldmd.cpp
driver/main.cpp
gen/coverage.cpp
gen/coverage.h
gen/module.cpp
gen/runtime.cpp
gen/statements.cpp
gen/toir.cpp

This PR adds coverage analysis to LDC2 (cmdline option -cov[=n%]), equal to DMD's coverage analysis (http://dlang.org/code_coverage.html).
Two data structures are added to the module object file for coverage analysis: _d_cover_data and _d_cover_valid. _d_cover_data is an array of the execution count for each line of code (the execution count is atomically incremented at the start of each statement). _d_cover_valid is a bit-array that for each line says whether there is a statement on that line for which the execution count must be printed.
Each module compiled with -cov is registered for coverage output by calling _d_cover_register2() in druntime/rt/cover.d, passing _d_cover_data and _d_cover_valid. Then, druntime will take care of outputting the coverage listing. _d_cover_register2() is …

Add Coverage Analysis (à la DMD)

---

gen/abi-generic.h
gen/abi-ppc64.cpp
gen/abi-win64.cpp
gen/abi-x86-64.cpp

And get rid of obsolete integer rewrites on Win64 and PPC and some general rewrites on System V x86_64 platforms.

Win64 ABI fix: return non-POD structs via sret.

---

dmd2/module.h
gen/irstate.h
gen/toconstelem.cpp
gen/toir.cpp
gen/tollvm.cpp

This is redone PR for caching the string literal global variables. Added caching to `DtoConstString` and `ToConstElemVisitor`. Got rid of pair<GlovalVariable*, DValue*>. Switched to use StringRef as the map key, and StringMap as the global variable cache.  One thing I'm not sure about is whether it is necessary to make a copy of e->string.  Since StringExp objects are never destroyed, it seems ok to store e->string pointer in `StringRef key`.  Please, review.

Cache global variables for string literals.

---

gen/llvmhelpers.cpp
gen/llvmhelpers.h
gen/tocall.cpp

This fixes an ICE on Win64/MSVC2013. See the discussion at the end of https://github.com/ldc-developers/ldc/pull/856
Please verify that this is indeed the intended behavior of `stripModifiers()` throughout LDC. If not, we could add an extra `bool recursive = false` argument.
If merged, please also merge into `merge-2.067`. (I don't know how to cherrypick commits, still learning git)

`stripModifiers()` should recursively remove modifiers

---

.travis.yml
CMakeLists.txt
README.md

This PR enables collecting gcov code coverage statistics and pushing them to coveralls.io.  It also adds the coveralls badge to README.  Someone with access to ldc-developers account has to create/connect a coveralls.io account to ldc-develoepr/ldc repository to make this work. This PR should close the issue #380.  I enabled test coverage for llvm 3.5 build, but of course any other one can be used as well. Please, review.

Add coverage testing.

---

dmd2/declaration.c

https://github.com/D-Programming-Language/dmd/pull/4598

DMD2: Fix missing initialization of OverDeclaration::overnext.

---

gen/functions.cpp
gen/llvmhelpers.h
gen/toir.cpp

Fixes `runnable/testassign.d`:
```D
void test12211()
{
int a = 0;
void foo(ref int x)
{
assert(x == 10);
assert(&x == &a);
x = 3;
}
foo(a = 10);
assert(a == 3);
foo(a += 7);
assert(a == 3);
...
}
```
Previously, in `foo(a += 7)` a new lvalue based on the rvalue binAssign result was passed to `foo()` instead of the nested lvalue `a`.

Enable passing binAssign expressions as ref/out arguments.

---

dmd2/declaration.c

Fix a bug where the mutable version of a Type is not properly resolved if it contains alias identifiers. This results in a bug later during compilation where stripModifiers() will return a not-fully-resolved type.
Fixes #893

Fix alias declaration type resolution

---

driver/cl_options.cpp
gen/cl_helpers.cpp
gen/cl_helpers.h
gen/optimizer.cpp
runtime/CMakeLists.txt

This approach is easier and requires less code. With some template foo
the BoolOrDefaultAdapter is not required.
This solutions applies to previous LLVM versions, too.

Implement FlagParser using llvm::cl::generic_parser_base.

---

dmd2/hdrgen.c

Merge-fix; fixes `compilable/testheader1i.d` and `compilable/testheader2i.d`.

Enable emitting function bodies when generating *.di headers.

---

gen/classes.cpp

Fixes an issue in `runnable/xtest46.d`.

Don't set default ctor in ClassInfo if it's @disabled.

---

gen/llvmhelpers.cpp
gen/structs.cpp

Although they occupy 1 byte, D now apparently doesn't care about the actual data when comparing instances for (in)equality.
Fixes `runnable/xtest46.d` and `runnable/cppa.d`.

Don't memcmp() empty struct types.

---

gen/dibuilder.cpp
ir/irvar.h

Debug info for nested local variables must be created for each
function (with different address expression). The resulting
debug info was not stored per function which resulted in the
use of the last created debug info even if it was wrong.
This commit fixes the bug and the current assertion with LLVM 3.7.

Fix a problem with debug info for nested local variables.

---

gen/dibuilder.cpp
ir/irfunction.h
ir/irvar.h

- the debug info is now stored in the IrFunction object
-> saves the lookup from VarDeclaration to IrVar
- uses a llvm::DenseMap instead of std::map
-> no comparison method required
-> hashing should be faster than tree lookup

Refactoring the debug info for nested local variables.

---

driver/toobj.cpp
gen/dibuilder.cpp
gen/dibuilder.h
ir/irfunction.h
ir/irtypeaggr.h

The solution is to use a typedef to hide the differences in most cases.

LLVM 3.7: Debug info classes changed again.

---

gen/dibuilder.cpp
gen/functions.cpp

The functions for all arrayops are compiler-generated but the functions
which are also defined in druntime are never emitted. This prevents
inlining of the function body and causes issue #938.
The fix is to emit the arrayops if inlining is enabled and otherwise
use the druntime provided implementations.
An alternative approach could be to always emit the arrayops and
never use the druntime version.

Possible fix for issue #938.

---

driver/cl_options.cpp
driver/cl_options.h
driver/linker.cpp
driver/main.cpp
driver/targetmachine.cpp
driver/targetmachine.h
driver/toobj.cpp

Adds a new command line option -mabi= and uses the value to compute
the ABI to use. Adds the ABI to linker and assembler invocation, too.
Allows consistent invocation of the whole tool chain.

MIPS: Implement ABI handling.

---

gen/llvmhelpers.cpp

This leads to serious problems for values we really should
not be loading from, such as 100k element static arrays.
It was hard to figure out exactly why we need to emit DWARF
info here, so the easiest solution is to just have a look
at assignments during the next big debug info push.
@liranz

Remove extra load on assignment generated only for debug info

---

dmd2/declaration.h
dmd2/dsymbol.h
gen/llvmhelpers.cpp

DtoSymbolAddress: Remove support for unused ClassInfoDeclaration

---

gen/classes.cpp
gen/toir.cpp

Casts are just bitcasts, and do not try to invoke
class invariants on asserts.
@yebblies mentioned he would extend the DMD test suite
accordingly.

Do not try to use RTTI for C++ classes

---

gen/dibuilder.cpp

This fixes a crash with debug info for lambdas, where DMD appends
the lambda function declaration to the wrong module.
But the comparison is supposed to be tautological anyway, as we
only ever call it from DtoDefineFunction. Furthermore, it seems as
passing false can never work unless you manually (without going
through llvm::DIBuilder) resolve the Vars node later. Clang does
not try to do this either.

We always define functions for which we emit DWARF subprograms

---

ldc2_install.conf.in
ldc2_phobos.conf.in

This is the only sensible solution until e.g.
D-Programming-Language/phobos#3009 is merged, which makes
Phobos load libcurl dynamically. The issue with the current
situation is is that the user cannot even manually link
libcurl if linker errors occur, because it will appear
before libphobos2-ldc in the linker command line.
GitHub: Fixes #906.

Always link libcurl when Phobos is linked

---

dmd2/module.h
driver/main.cpp
gen/module.cpp

If a target file name is given (`-of`) and a library is created then
`-singleObj` is implied. This results in behaviour not compatible
with dmd. This commit checks for this situation and does not set
`-singleObj`. This fixes issue #978.

Do not imply ` -singleObj` if creating lib.

---

dmd2/cppmangle.c

- Calls now `fatal()` instead of `assert(0)` after an error message. This should reduce the ugly stack traces on windows.
- Chooses the CPP mangler based on the current target. Up to now the Visual C++ mangler was not used.

Updates to the CPP mangler

---

gen/asm-x86.h

This should allow some inline assembly originally crafted for 80-bit x87 reals to work with 64-bit doubles too, although it would still use the x87 coprocessor instead of trying to exploit enhanced x86 instruction sets.

Inline assembly fix for MSVC: treat real ptr as 64-bit double.

---

gen/llvmhelpers.cpp

Fixes things like `const(Foo) f = void; static shared this() { f = …; }`.

Do not emit globals with void initializer as LLVM constants

---

ir/iraggr.cpp
ir/irtypeaggr.cpp

The previous approach was to add i64, i32, i16, i8 members depending
on alignment and required space. This seems to cause several problems.
Solution is to use a byte array. This makes to code more compact, too.
Fixes issue #989.

Use a byte array for padding of unions/structs.

---

ldc2.conf.in
ldc2_phobos.conf.in
runtime/CMakeLists.txt

The linker on OS X emits a warning for these, breaking the
dmd-testsuite tests that verify the diagnostics.

Do not use non-existing library search paths on non-MSVC builds

---

gen/dibuilder.cpp
gen/module.cpp

This is likely an LLVM bug: The code in InlineFunctions.cpp
only updates the source location metadata for the instructions
in the inlined callee when the call site has a source location
set. When the caller has no location metadata, the scope for
the inlined instructions thus still points to the DISubprogram
for the original callee. This then leads to an assertion during
codegen.
GitHub: Fixes #998.

Fix debug info builds with inlining on

---

.travis.yml
gen/abi-mips64.cpp
gen/abi-ppc64.cpp
gen/abi-win64.cpp
gen/abi-x86-64.cpp
gen/abi-x86.cpp
gen/abi.cpp
gen/abi.h
gen/functions.cpp
gen/module.cpp
gen/runtime.cpp
gen/tocall.cpp

0.15.1 used stdcall convention everywhere. But the ABI change in 0.15.2
requires use of the C calling convention for variadic calls on x86
because the stdcall convention does not support vararg functions.
Solution is to check the llvm::FunctionType if the function has varargs.
This commit also makes the C calling convention the global default
because according to the LLVM documentation the fastcc convention used
for D linkage does not support varargs.
This fixes issue #1000.

Use C calling convention for variadic functions on x86.

---

gen/classes.cpp
gen/irstate.h
gen/llvmhelpers.h
gen/toir.cpp
ir/irfunction.cpp
ir/irfunction.h

This is an attempt to fix `runnable/sdtor.d:3438`.
Reduced test case:
```D
import core.exception, core.stdc.stdio;
struct S {
__gshared int count;
~this() { ++count; }
}
class C
{
this(S s, int f, S s2) {}
}
int foo(bool flag)
{
if (flag)
throw new Exception("hello");
return 1;
}
void main()
{
bool flag = true;
bool threw = false;
try { new C(S(), foo(flag), S()); }
catch (Exception) { threw = true; }
assert(threw == flag);
printf("S.count = %d\n", S.count);
if (flag)
assert(S.count == 1);
else
assert(S.count == 2);
}
```
Without this patch, the first two argument expressions `S()` and `foo(flag)` for `C::this()` cannot be resolved to the variables (`__pfx` and `__pfy`) declared for them in DMD's `functionParameters()`. Their declaration expressions (and dtor gates) form a `CommaExp` …

WIP: Codegen for NewExp::argprefix.

---

gen/asm-x86.h

`compilable/iasm_labeloperand.d` is the last official 2.067 issue (edit: okay, there's still shared libs and `rt.util.typeinfo-debug`) on Linux x64 after David's latest commits. :+1: It uses labels as source operands for `mov` instructions, which is currently not supported.
This commit checks whether an identifier operand is a function label, for all instructions and not just those explicitly supporting labels (`opTakesLabel()`). If the instruction doesn't take labels directly, the operands yield the label's address. Not sure whether this is all it takes, but we have the first green 2.067 builds at last! :)

[WIP] DMD inline asm: allow labels as generic operands

---

gen/irstate.cpp
gen/llvmhelpers.cpp
ir/irfunction.h

Unfortunately, I could not manage to isolate a self-contained
test case. The bug is quite specific to the exact memory
allocation decisions made by the standard library, as it would
not occur if the elements appended by the finally block codegen
fit into the current capacity.

Fix crash due to invalid iterators in DtoEnclosingHandlers

---

gen/llvmhelpers.cpp
gen/llvmhelpers.h
gen/rttibuilder.cpp
gen/rttibuilder.h
gen/toir.cpp
ir/iraggr.cpp
ir/irtypeaggr.cpp

We already generated the memsets for zeroing the padding,
but because we relied on the native LLVM type allignment
where possible instead of generating explicit padding
values, LLVM did not always copy those bytes around (e.g.
when spilling/reloading registers).

Always zero struct padding as required by TDPL

---

gen/runtime.cpp
ir/irlandingpad.cpp
ir/irlandingpad.h

Now we no longer require separate landing pads for collisions
in user code. This leads to less cruft being generated and opens
the door towards folding the successful and exceptional paths
through finally blocks into one.
This commit breaks Win64; ldc.deh2 will also need updating.

Exception chaining reimplementation for correct and lean IR

---

driver/codegenerator.cpp
gen/module.cpp

In case of a singleobj build and a provided output file (.exe or .obj). The dmd-testsuite tests used to produce lots of .o files while expecting .obj ones as specified in the command line.

Windows: don't overwrite object file extension to .o

---

gen/toconstelem.cpp

The new type parameter for `llvm::ConstantExpr::getGetElementPtr()` is checked for being the pointee of the provided base (or more precisely, the pointee of the base's scalar type).
So for the 'ugly' GEP, i8* as type for an i8* base was clearly wrong, and the 'nice' GEP with the fixed i8 type would only work for i8* bases.
By simply using `nullptr`, the type is inferred, and we perform a bitcast afterwards anyway.
This fixes dmd-testsuite issues on Win64, e.g., `runnable/test11.d`.

LLVM 3.7+: fix toConstElem(SymOffExp*).

---

gen/classes.cpp

... and always return null in that case. Is that correct?!
See https://github.com/ldc-developers/ldc/issues/1024.

Fix issue 1024: allow classes to be cast to typeof(null)

---

gen/llvmhelpers.cpp

Another one caused by special "context-specific" AST semantics. :/
GitHub: Fixes #982.

Fix ICE caused by type mismatch on casting sret return value

---

gen/arrays.cpp
gen/functions.cpp
gen/nested.cpp
gen/runtime.cpp
gen/runtime.h
gen/tocall.cpp
ir/irfuncty.cpp
ir/irfuncty.h
ir/irtypefunction.cpp

This is most visible on x86 (32-bit), where the stack
alignment is off otherwise.
This change is quite messy because many places assumed
that there was always exactly one LLVM parameter per
TypeFunction::parameters entry.

C ABI: Do not pass empty structs as parameters at all

---

CMakeLists.txt
ldc2.conf.in
ldc2_phobos.conf.in
runtime/CMakeLists.txt

These changes allow for LDC to be built with only a handful of warnings using VS 2015, without the need for any explicit CMake compiler flags.
We make it through warning level 3 by disabling a dozen specific warnings.
I've tested the Debug and RelWithDebInfo CMake build types.
For reference, here are the default CMake 3.3 variables for the Ninja generator and MSVC 2015:
```
-- CMAKE_C_FLAGS:  /DWIN32 /D_WINDOWS /W3
-- CMAKE_C_FLAGS_DEBUG: /D_DEBUG /MDd /Zi /Ob0 /Od /RTC1
-- CMAKE_C_FLAGS_MINSIZEREL: /MD /O1 /Ob1 /D NDEBUG
-- CMAKE_C_FLAGS_RELEASE: /MD /O2 /Ob2 /D NDEBUG
-- CMAKE_C_FLAGS_RELWITHDEBINFO: /MD /Zi /O2 /Ob1 /D NDEBUG
-- CMAKE_CXX_FLAGS:  /DWIN32 /D_WINDOWS /W3 /GR /EHsc
-- CMAKE_CXX_FLAGS_DEBUG: /D_DEBUG /MDd /Zi /Ob0 /Od /RTC1
-- CMAKE_CXX_FLAGS_MINSIZEREL: /MD /O1 /Ob1 /D …
```

Revise CMake scripts some more for MSVC

---

.travis.yml

Currently, the one job taking nearly twice as long as the others, i.e., LLVM 3.6 multilib (~53 mins vs. others averaging in ~29 mins), is started after the first batch of 5 parallel jobs.
Letting it start at the beginning will decrease the overall feedback time by roughly one third!

Travis: reverse job order.

---

runtime/CMakeLists.txt

Just to test it on Linux too to be sure. I've created a `vs2015` branch (https://github.com/ldc-developers/druntime/pull/32) on the official druntime repo.

druntime: cherry-pick upstream support for Visual Studio 2015

---

gen/arrays.cpp
gen/arrays.h
gen/toir.cpp

Properly ignore statically known SliceExp bounds

---

ldc2_install.conf.in
ldc2_phobos.conf.in
runtime/CMakeLists.txt
tests/d2/CMakeLists.txt

Besides being the right thing to do, this might also help us with the 32 bit Travis failures, since the issue seems to be that the i386 libcurl package does not include the appropriate symlinks to the shared library binaries.

Dynamically load libcurl when needed (backport from post-2.068 upstream)

---

appveyor.yml

https://ci.appveyor.com/project/kinke/ldc/history
2 jobs now (debug & release): Win64, Visual Studio 2015, `RelWithDebInfo` configuration for LLVM and LDC, preferring Ninja over msbuild and using a pre-built LLVM 3.7 RC (assertions enabled) from my DropBox. ;)
The unit tests are run; release ones are allowed to fail (core.thread fails in release). dmd-testsuite is excluded for now.
The resulting 'installed' LDC should be published as artifact, that somehow doesn't work yet.
We have at most 40 minutes before a job is killed and just 1 job at a time.

Add Appveyor support for Windows CI

---

appveyor.yml

The RelWithDebInfo LLVM takes 4 minutes to extract (just for comparison, on my native system: 10 secs) and 10+ minutes longer when linking ldc2.exe, most likely because of insufficient RAM.
So use the pre-built LLVM with debug infos for the debug job only (which publishes the artifact) and a new pre-built LLVM compiled with Release CMake config (LLVM assertions still enabled) for the release job, which is constantly struggling to finish inside the 40 minutes we've got.
*Edit*: the 12+ minutes overhead gets the debug job way too close to the 40 minutes limit, we've just made it by a few seconds. So use the Release-LLVM for the debug job too.

Appveyor: use new pre-built LLVM in Release config

---

ir/iraggr.cpp
ir/irtypeaggr.cpp

Fix alignment of interface info in class with align(1) members

---

driver/linker.cpp

An attempt to fix a test case results in breaking compiling with dub.
This PR reverts part of the former fix.
The changed test case is missing.

Fix (part of) issue #1061.

---

gen/declarations.cpp
gen/functions.cpp
gen/inlineir.cpp
gen/llvmhelpers.cpp
gen/llvmhelpers.h
gen/rttibuilder.cpp

Starting with LLVM 3.7, linkage and COMDAT are 2 different concepts.
This means that LinkageODROnce does not put the object into a COMDAT.
On Windows this resulted in linker error messages.
This PR places all template functions, TypeInfo objects and other
objects into a COMDAT.

Fix for issue #1061.

---

driver/targetmachine.cpp
gen/tocall.cpp

This is required for compiling latest vibe.d version.
Please note that a fix to vibe.d is also required, see
https://github.com/rejectedsoftware/vibe.d/pull/1255

Implement 128bit atomic load, atomic store and cmpxchg.

---

gen/classes.cpp
gen/classes.h
gen/runtime.cpp
gen/toir.cpp
ir/irclass.cpp

This allows us avoid the problems stemming from the 64 kiB
size limit hack in _d_toObject.
GitHub: Fix #1065.

Use thunks instead of calling _d_toObject for D interfaces

---

gen/declarations.cpp
ir/irclass.cpp

Initializers and thunk code were still missing in COMDAT section.

Fix more of issue #988.

---

gen/declarations.cpp
gen/functions.cpp
gen/llvmhelpers.h
gen/tollvm.cpp
gen/tollvm.h
ir/irclass.cpp

Linkage and the COMDAT flag is now returned as std::pair<>.
Also adds more COMDATs.

Refactor new COMDAT code.

---

driver/linker.cpp

This is the same behavior as dmd. Fixes issue #1084.

Do not append extension if library filee name already has one.

---

dmd2/expression.c
gen/functions.cpp
gen/pragma.cpp
gen/tocall.cpp
gen/tollvm.cpp

Whose types aren't rewritten by the regular TargetABI.
Fixes the undefined reference to `llvm_atomic_load()` for MSVC builds.
There's a couple more comparisons against `LLVMintrinsic` alone. And I'm not sure whether we can add some more instructions (fence, bitops) as intrinsics in `DtoIsIntrinsic()`.

Treat atomic instructions as intrinsics

---

gen/pragma.cpp

The wrong ABI is called for every function intrinsic. These are the
ones handled in DtoLowerMagicIntrinsic(). This PR adds the missing
instrinsic constants.

Add more intrinsics to DtoIsIntrinsic.

---

dmd2/cond.c
driver/main.cpp

Define CRuntime_Glibc for Linux and CRuntime_Bionic for Android.

Add missing version identifiers for C runtimes.

---

gen/abi-x86.cpp
gen/functions.cpp

Need to do further tests, but it seems like GCC does expect empty structs to be passed. If this is correct, it would be a Clang++/G++ ABI incompatibility on Linux.

x86: Only skip empty structs on OS X

---

driver/main.cpp

This fixes fail_compilation\diag4479.d on Win64.

Windows: replace forward slashes in cmdline source files by backslashes

---

appveyor.yml
driver/main.cpp
runtime/CMakeLists.txt
tests/d2/CMakeLists.txt

Should finally settle the long-lasting dilemma of abysmal performance with `-g`. I recently discovered that there really is no justification for automatically enabling the debug libraries at all, because some of the druntime contracts e.g. change AA lookup to be O(N) and similar stuff that is not just a constant overhead.
@redstar: This is my last big change/fix for 0.16.0.

driver: Only use slow -debuglib libraries if explicitly asked to 

---

gen/programs.cpp

On FreeBSD 10 clang is the default compiler. gcc is not installed
by default. This PR changes the used compiler driver for linking
to clang.

Use clang as default compiler driver on FreeBSD 10 or later.

---

gen/dibuilder.cpp

The 2.068 front-end seems to emit such `Loc`s, and LLVM complains about them. So this fixes a bunch of compile errors for merge-2.068.

Debug infos: don't emit a column info if line number == 0.

---

cmake/Modules/FindLLVM.cmake

Remove component ipa if building LDC with LLVM 3.8.

---

.travis.yml

This PR re-arranges the build parameters a bit. Basically, I moved
every option to a higher LLVM version. I expect that this will
show some more failures. It also prepares for the drop of support
of LLVM 3.1-3.4.

Use another Travis-CI build order.

---

gen/aa.cpp
gen/abi-generic.h
gen/abi-x86-64.cpp
gen/arrays.cpp
gen/llvmhelpers.cpp
gen/module.cpp
gen/nested.cpp
gen/toconstelem.cpp
gen/toir.cpp
gen/tollvm.cpp
gen/tollvm.h
ir/iraggr.cpp
ir/irtype.cpp
ir/irtypeaggr.cpp

Hopefully there are no issues due to potentially more promotions.

Refactor common `i1ToI8(voidToI8(DtoType(...)))` code occurrences

---

gen/llvmhelpers.cpp
gen/nested.cpp

Should fix #1127.
*Edit*: would probably be better suited for master; let's check the tests at least first here on merge-2.068 where the issue surfaces.

Nested static functions and function literals do not inherit the parent context

---

appveyor.yml
driver/configfile.cpp

And use it for the AppVeyor release to make it portable.

Windows: use forward slashes when replacing %%ldcbinarypath%% in config file

---

driver/cl_options.cpp
driver/cl_options.h
driver/main.cpp

There is a LLVM 3.7 command line option named color. This option is
only available if ldc is linked against shared LLVM libraries.
Because the LDC color option uses a FlagParser simple renaming does
not work. The solution is now:
- Rename LLVM option `color` to `llvm-color` and hide this option
- Dynamically create the LDC option `color`
This finally enables building with shared LLVM libraries.

Handle command line option color.

---

gen/abi-win64.cpp
gen/abi.h
gen/functions.cpp
gen/tocall.cpp
ir/irclass.cpp

Fixes https://github.com/ldc-developers/ldc/issues/1156.

Win64 ABI: pass 'this' before 'sret' for extern (C++)

---

driver/linker.cpp
vcbuild/amd64.bat
vcbuild/x86.bat

This command line sent to CreateProcess():
```
"C:\LDC\bin\amd64.bat" 1 2 "3" 4
```
is internally transformed to:
```
C:\Windows\system32\cmd.exe /c "C:\LDC\bin\amd64.bat" 1 2 "3" 4
```
Now guess what - cmd.exe treats the command string after /c or /k in a very special way if it begins with double quotes and is followed by other quoted args. In this example, it tries to invoke:
```
C:\LDC\bin\amd64.bat" 1 2 "3
```
Another example: `C:\Windows\system32\cmd.exe /c "C:\L D C\bin\amd64.bat" 1 2 "3" 4` => `C:\L`
The fix seems to be enclosing the whole command with additional double quotes (but no additional escaping of the command!) and using `/s` for cmd.exe:
```
C:\Windows\system32\cmd.exe /s /c ""C:\L D C\bin\amd64.bat" 1 2 "3" 4"
```
So the command is quoted, but not escaped, i.e., no …

Windows: fix command line when invoking linker batch file

---

gen/functions.cpp
gen/llvmhelpers.cpp
gen/llvmhelpers.h
gen/nested.cpp
gen/rttibuilder.cpp
gen/target.cpp
gen/tocall.cpp
gen/toconstelem.cpp
gen/toir.cpp
gen/tollvm.cpp
gen/tollvm.h
gen/typinf.cpp
ir/iraggr.cpp
ir/irfunction.cpp
ir/irfunction.h
ir/irtypeaggr.cpp
ir/irtypeaggr.h

Trying to get the alignment right by using the first non-default one in the following order of descending priority:
`VarDeclaration::alignment` [variables only of course]
`Type::alignment()`
`Type::alignsize()`
This fixes the alignment of `align(x) struct S { ... }` instances on the stack.
Local variables with an explicit align attribute are still default-aligned though. :/

Introduce DtoAlignment() and overload DtoAlloca() for VarDeclarations

---

gen/dibuilder.cpp

DBuilder.createSubroutineType no longer accepts a `file` argument.
Also fixed an inverted condition enabling CodeView.

more updates to LLVM master changes

---

gen/declarations.cpp
gen/llvmhelpers.cpp
gen/uda.cpp
gen/uda.h

<del>I'm still not sure whether we really want to go the `@attribute` route, or if we should prefer individual types (e.g. `@section(...)`).
The latter seems cleaner and more flexible (regarding aliasing different UDAs for different compilers). It might make sense to have string arguments for an UDA that just sets the corresponding LLVM function attribute, but using them for this seems somewhat off. GDC uses a single magic attribute struct, but that's probably just to map directly to the C `__attribute__` syntax.</del>
This now uses actual struct literals for attributes that can be generated by arbitrary CTFE expressions. This should allow for quite a bit of flexibility when targeting multiple compilers.

Implement @ldc.attributes.section(...) for variables

---

runtime/CMakeLists.txt

output_path was supposed to be a "local variable" of the
build_runtime() macro. The latter should probably be a
function instead anyway.

CMake: Fix multilib druntime/Phobos test runner builds on OS X

---

driver/main.cpp
driver/targetmachine.cpp

Not mean to be the end all as other darwin targets are coming along.  But this makes everything better with Xcode 7.  In particular, OS X ld in Xcode 7 warns when default LLVM triple with OS darwin is used because the darwin default version (x86_64-apple-darwin14.5.0 on my box) is greater than OS X version.  More work has to be done for specifying OS min versions and such.  Hope this is ok for now.
For background: http://forum.dlang.org/post/avnefmjkfgqbfiapibfv@forum.dlang.org

OS X - default OS to macosx instead of darwin

---

driver/main.cpp
gen/aa.cpp
gen/arrays.cpp
gen/attributes.cpp
gen/attributes.h
gen/classes.cpp
gen/functions.cpp
gen/functions.h
gen/llvmhelpers.cpp
gen/module.cpp
gen/runtime.cpp
gen/runtime.h
gen/statements.cpp
gen/toir.cpp
ir/irfunction.cpp
ir/irfuncty.cpp
ir/irfuncty.h

WORK IN PROGRESS
Makes the code much prettier I hope.
The main motivation is to enable sret for dynamic arrays, see closed PR #901.

Clean up druntime fwd decls

---

dmd2/parse.c
tests/ir/align.d

This fixes the remaining problem of issue #1154, explicit (overriding) alignment of local variables.
It's the first time I look at the parser code, so please review carefully.
What it looks like to me is that the attributes found on line 3804 are forgotten and not applied to normal local variables without initializers (the last part of the function). So I added code that applies the AlignDeclaration to the declaration, following a pattern found elsewhere in this function. Perhaps we also need to add the other attributes (except linkage?):
```C++
if (storage_class)
{
Dsymbol *s = new StorageClassDeclaration(storage_class, a);
a = new Dsymbols();
a->push(s);
}
if (structalign != 0)
{
Dsymbol *s = new AlignDeclaration(structalign, a);
a = new Dsymbols();
a->push(s);
}
if (udas)
{
Dsymbol *s …
```

Fix explicit alignment of local variables

---

gen/abi-generic.h
gen/abi-mips64.cpp
gen/abi-ppc64.cpp
gen/abi-win64.cpp
gen/abi-win64.h
gen/abi-x86-64.h
gen/abi-x86.h
gen/abi.cpp
gen/abi.h
gen/declarations.cpp

Another positive side-effect of #1168.
To be complemented by https://github.com/D-Programming-Language/druntime/pull/1443.

Win64 ABI: Rewrite magic __c_long_double struct as double

---

runtime/CMakeLists.txt

The required lib is now referenced as defaultlib in druntime's `msvc.c` if druntime is built with VS 2015, see https://github.com/ldc-developers/druntime/pull/47.

Update druntime and remove additional VS2015 .lib from config file

---

driver/response.cpp

On PowerPC and ARM a char is unsigned. Fix a few places that
relied on it being signed.

A char may not be signed, use signed char

---

runtime/CMakeLists.txt

Update druntime submodule with cherry-picked core.internal.convert upstream changes and start running its unit test again.
This should resolve issue #788.

Re-enable core.internal.convert unit tests

---

gen/uda.cpp
tests/ir/attr_target_x86.d

The implementation is rudimentary, but I think it works well enough.
The string passed to target(...) is not checked, and so the user has to be careful in specifying valid options. LLVM does warn on invalid options.
One significant difference with clang is that for the string "sse4.1", this PR will set "target-features" to "+sse4.1", whereas clang will set a long list of features "sse,sse2,sse3,ssse3,sse4.1" and more. From simple testcases, it appears this is not needed for LLVM to do the right thing.
Clang has an elaborate implementation that deals with x86's options, see clang/lib/basic/Targets.cpp. Perhaps that functionality can be moved into LLVM; if not, we will have to copy that code (and keep it up-to-date with the latest microarchitecture...).

Implement rudimentary support for @ldc.attributes.target("...")

---

dmd2/globals.h
driver/codegenerator.cpp
driver/main.cpp
gen/abi-x86.cpp
gen/module.cpp
gen/runtime.cpp

This PR replaces the few uses of `global.params.is<OS>` with
`global.params.targetTriple.isOS<OS>()`. This avoids adding a new
boolean for each supported OS.
It also defines all xBSD-type OS as using the dso-registry.
Only `global.params.isWindows` is not replaced because it is used by the frontend code.

Do not use global.params.is<OS>

---

driver/targetmachine.cpp

The Gentoo CHOST triple differs from the normalized triple used by
LLVM. See https://wiki.gentoo.org/wiki/CHOST for details.
This results in a failure to detect the used float ABI. The vendor
field can be hardfloat or softfloat in order to indicate the float
ABI. This is the only way to specify the hardfloat ABI because the
C library value gnueabihf is not supported.
This commit adds a check for vendor names hardfloat and softfloat.

Support Gentoo CHOST triple

---

driver/linker.cpp

The libraries -lsocket and -lnsl were missing.
Both are required to compile a "Hello World" style program.

Add missing libraries for OpenSolaris.

---

CMakeLists.txt

This happens on my ARM device and causes a cmake error.

Cmake: Remove trailing space from LLVM_LDFLAGS.

---

cmake/Modules/FindLLVM.cmake

Set cmake var LLVM_ENABLE_ASSERTIONS based on llvm-config --assertion-mode.
This is a solution to #1250.
This option isn't in a build I have of llvm 3.4 but it is in my 3.5.1 build.  Does LDC support older LLVM than 3.5.1?

cmake: Detect if llvm assertions enabled

---

gen/runtime.cpp

The added overhead for Windows et al. is utterly insignificant
compared to all the other typically unused declarations that
will be created by this, and copy/pasting the long condition
(see d072bdf) is error-prone. The alternative would have been
to factor the check out into a predicate function.

buildRuntimeModule: Always create _d_dso_registry forward decl (small cleanup)

---

ir/irtype.cpp
ir/irtype.h

The constructor of IrTypeSArray() calls sarray2llvm(). This function calls
DtoMemType() which may recursively try to construct another IrTypeSArray
for the same type. To prevent this the call to sarray2llvm() is moved
out
of the constructor into the factory method and an explicit check is added.
This fixes issue #1266.

Do not construct IrTypeSArray twice for same type.

---

gen/llvmhelpers.cpp
gen/tollvm.cpp
gen/tollvm.h

Previously, we would just ignore such casts altogether, leading to problems down the road when we would actually load the alloca/… for the source struct.
Fixes #1211.

DtoCast: Handle struct repainting

---

ir/irtype.cpp
ir/irtype.h
ir/irtypefunction.cpp

This is the same as in PR #1269. The Ir-Types may be initialized
twice (due to pointers, forward references etc.).
This commit fixes hopefully all instances of this problem, using
the same approach in each factory function.
This fixes issue #1112.

Do not construct Ir-Types twice for the same type.

---

driver/targetmachine.cpp
gen/abi-arm.cpp
gen/abi-arm.h
gen/abi-generic.h
gen/abi.cpp
gen/abi.h

This is the bulk of the AAPCS (Procedure Call Standard for the ARM Architecture) used for C interop.  This will be used for both arm and thumb target triples.  The extern(D) ABI tries to follows the AAPCS with a few exceptions.

Implement ARM AAPCS ABI and other ARM fixes

---

cmake/Modules/FindLLVM.cmake
runtime/CMakeLists.txt

These are: AArch64, ARM, Mips, PowerPC, SystemZ and X86.

Add gccbuiltins_*.di for more supported targets.

---

gen/toir.cpp
ir/iraggr.cpp

Field overlap checking was only done for structs, and only for implicit initializers. This PR fixes that.
The `AggregateDeclaration *decl` argument to `IrAggr::addFieldInitializers(...)` is never a `UnionDeclaration`. Instead, a union's fields are merged with the encompassing class's/struct's fields, with offsets such that the fields overlap. 
I have not included codegen testcases, but opened an issue to do so. I want to focus on the merge 2.069 branch, and this issue popped up there too (`runnable/interpret.d`).
It appears that explicit initializers are given for cases where I do not see any in the code. I believe the function will need more work, hopefully uncovered while try to construct tough codegen testcases.

Fix union initialization. Fixes issue 1286.

---

utils/gen_gccbuiltins.cpp

table gen parser "Properties" has been renamed "IntrProperties" in LLVM 3.9

fix building against LLVM master

---

CMakeLists.txt

Start to use the D compiler for building executables (linking).

Use D compiler to build idgen

---

gen/abi-arm.cpp
gen/tollvm.cpp

These changes fix a variety of things for ARM
- std.datetime unittest when optimizing
- std.random unittest when optimizing
- runnable/mars.d when optimizing (compile used to crash), and much faster compile time
- runnable/test12.d and runnable/test5854.d (sort w/ user defined opCmp was reverse list)
- runnable/cppa.d at -O3 by zero extending char types
The zero extension of char-types is not ARM specific and may help other targets too.

Additional ARM ABI fixes

---

gen/asmstmt.cpp

Allow asm statement to be tested in a __traits compiles check without fataling for those targets that don't support dmd style inline asm.  Without this, a compile could exit(1) mysteriously without any error messages.
Fixes runnable/testsafe.d on ARM and probably all other non-X86 targets.

Fix non-x86 __traits compiles for dmd inline asm

---

ir/irdsymbol.cpp
ir/irdsymbol.h

This fixes an assertion failure on Linux/AArch64 (Ubuntu) and on
Linux/PPC64 (RedHat).

Change initialization of IrDsymbol.irData.

---

dmd2/func.c
gen/abi-aarch64.cpp
gen/functions.cpp

This is required to resolve the type for AAPCS/AAPCS64.
Up to now it was not necessary because only char* was used.
AAPCS/AAPCS64 use a special extern(C++) struct __va_list.

Run semantic on Type::tvalist.

---

gen/tollvm.cpp
ir/irtype.cpp

This adds the missing code paths.

AArch64: This platform uses IEEE 128-bit floats.

---

driver/linker.cpp

Currently we want to pass -m64 to gcc which aborts the compiler.

AArch32/64: gcc does not support -m32/-m64.

---

gen/tollvm.cpp

The previous implementation sets all reals to 0.0.

Fix IEEE 128-bit reals.

---

gen/asm-x86.h

`Dst` means overwrites target, `Upd` means that new target value depends
on old value of target.
This hides the failure from #1292 but does not fix the root cause.

Change description of some x64 instructions for inline assembler.

---

gen/abi-arm.cpp

AAPCS defines va_list as a std::__va_list struct, which is needed to interface with C++.   This builds on @redstar 's recent change for AArch64 which has a similar situation, although AAPCS __va_list is not as complicated.  With this, test runnable/cppa passes.
Needs to be pulled with ldc-developers/druntime#64.
Now runnable/test42.d will need a fix for ARM because va_list is no longer a simple pointer.  Coming in the next few days.

Support ARM AAPCS style va_list for C++ mangling

---

ddmd/globals.d
ddmd/globals.h
ddmd/objc.d
driver/main.cpp
gen/functions.cpp
gen/objcgen.cpp
gen/objcgen.h

Experiment with letting LLVM generate image info based on module flags.  Probably the way to go.
I am not sure if doing pull requests or pushing directly to objc-wip branch is best.  I imagine incremental improvements over the next week or so.
Are we supposed to make -m32 x86 work too?  I noticed test suite Makefile only enables objc tests for 64-bit.
edit:  dmd -m32 doesn't make a working objc call.  In ldc, I got it to work by using the fragile ABI section names with -m32.  Is there any reason not to support x86?

More (or less) Objective-C Stuff

---

appveyor.yml
gen/dibuilder.cpp

A limitation of the MS linker/COFF format and enforced by LLVM.
Fixes issue #930.

MSVC: Limit debug info symbol names to ~64k

---

appveyor.yml
gen/abi-win64.cpp
gen/abi-x86.cpp
gen/attributes.cpp
gen/attributes.h
gen/dibuilder.cpp
gen/dibuilder.h
gen/functions.cpp
gen/irstate.h
gen/ms-cxx-helper.cpp
gen/ms-cxx-helper.h
gen/runtime.cpp
gen/statements.cpp
gen/target.cpp
gen/tocall.cpp
ir/irclass.cpp
ir/irfunction.cpp
ir/irfunction.h
tests/codegen/align.d
tests/codegen/attributes.d

Enable @rainers #1168 for Win64 too and add x86 AppVeyor jobs.
Requires https://github.com/ldc-developers/druntime/pull/65 and a post-3.8 LLVM (Rainer's work has uncovered a few LLVM bugs whose near-instant fixes didn't make it into 3.8 final).

Enable MSVC EH for Win64

---

driver/main.cpp

Some passes were initialized two times, some were missing.

Cleanup initialization of LLVM.

---

dmd2/cppmangle.c

There is no platform which uses `__float128` for `real` data type.
On AArch64 the wrong mangling is choosen. Just remove support for
`__float128`.

Fix mangling error on AArch64 platform.

---

gen/toir.cpp

Fixes a 2.070 testsuite bug that only manifests itself for 32bit compilation.
Code like this is bugged without this PR:
```D
uint[] values = [0,1,2,3,4];
size_t offset = 0;
auto a = values[offset .. offset+=2];
assert (a == [0,1] && offset == 2);
```
The type of `offset` is important. In the testsuite, the type is `uint`, such that for 64bit compilation the lowerbound expression `32bit offset` is converted to a 64bit value before evaluating the upperbound, hence it all works out OK for 64bit. For 32bit, no conversion is needed and the lowerbound expression is only fully evaluated after offset+=2.

Ensure strict evaluation order in slice expressions.

---

gen/typinf.cpp

Fixes issue #1377.
Thanks to David for the patch.

Define TypeInfo symbols as mutable (instead of immutable), to comply with DMD

---

gen/runtime.cpp

These functions are only called at most once: in case of a failure.
Marking them as 'cold' may help the (not yet added) IRCE pass.
Also adds the missing 'uwtable' attribute for x86_64.

Add 'cold' attribute to _d_assert, _d_arraybounds and _d_assert_msg.

---

CMakeLists.txt

Hopefully generating the .pdb again for AppVeyor.

CMake: Use appropriate DMD flags for CMAKE_BUILD_TYPE=RelWithDebInfo

---

gen/abi-aarch64.cpp
gen/abi-generic.h
gen/abi-ppc.cpp
gen/abi-ppc.h
gen/abi-ppc64le.cpp
gen/abi-ppc64le.h
gen/abi.cpp
gen/abi.h

The ABI for PPC/PPC64 big-endian is quite similar.
But the ABI for PPC64 little-endian is more like the ARM ABI.

Introduce new ABI class for PPC64LE.

---

gen/dvalue.cpp
gen/dvalue.h
gen/llvmhelpers.cpp
gen/llvmhelpers.h
gen/nested.cpp
gen/toir.cpp

See the commit descriptions for details (most changes are just refactorings).
Fixes #1294 (both by avoiding the issue, as well as fixing potentially undiscovered similar issues by tackling the root cause).

Refactor DVarValue handling; fix dumping ToElemVisitor result to stack slot

---

dmd2/root/port.c

The global namespace versions are not guaranteed to be available in
C++ mode, and GCC 5.3 on Arch Linux indeed does not make them available.
This is just long-term maintenance (the implementation has been
moved to D in DDMD/LDC master), so no IN_LLVM business anymore.
For now, this just changes the "generic" Posix branch, but eventually
we might want to move the other OSes to using std too.
GitHub: Fixes #1395.

port: Use std::* versions cmath/ctype functions

---

ddmd/root/rmem.d

~~Important: this should be merged *after* druntime has been updated with @weak for the memory allocation functions (otherwise LDC-master will not be able to build itself).
See https://github.com/ldc-developers/ldc/pull/1413~~
The change will become effective once LDC 0.17.2 (yet unreleased, assuming #1413 will be merged) is used.
Edit: so this means that our current CI systems do not use the `OVERRIDE_MEMALLOC=true` path.

Enable the DDMD overides for memory allocation when LDC+@weak is detected

---

ddmd/root/filename.d

Discovered while trying to compile LDC with itself.

Fix type of char parameters for Windows call. (already fixed upstream)

---

ddmd/root/port.d

master builds on ARM and phobos hello world works.  Now need to get ARM tests working, starting by putting 64-bit real support back in root/port.d.
Note there is more stuff in previous port.c C++ version that needs to move up to D version, such as supporting big endian.
edit: this has morphed into something simpler - just use real type of the build host D compiler.  It is needed on all the non-x86 hosts until real type cross-compiling is supported.

Use build host D real type [was ARM/AArch64 updates to master (support 64-bit/128-bit real type)]

---

gen/toir.cpp

This fixes the test failure for runnable/funclit.d

function literals also have to be generated from VarExp

---

CMakeLists.txt

This in turn triggers rebuilding of LDC with new idgen.d identifiers.

Add extra dependency on running idgen, so it is actually re-run after rebuilding it

---

utils/FileCheck-3.5.cpp
utils/FileCheck-3.6.cpp
utils/FileCheck-3.7.cpp
utils/FileCheck-3.8.cpp

This adds CHECK-SAME and erroring on unsupported "-NOT" check combinations

Backport important features of recent FileCheck to the 3.5-3.8 versions.

---

dmd2/root/port.c
driver/codegenerator.cpp
driver/linker.cpp
driver/main.cpp
gen/module.cpp

I finally matched the way dmd packs emulated TLS data with ldc, see below for more comments.

Add a handful of fixes for Android

---

gen/functions.cpp
gen/inlineir.cpp
gen/inlineir.h
gen/llvmhelpers.cpp
gen/toir.cpp
tests/codegen/inlineIR_math.d

This is the current behavior for inline ASM too.
When certain attributes are applied to the calling function, like "unsafe-fp-math", the inlined inlineIR function has to have the same attributes otherwise the calling function attribute will be reset to the safe merge of the two: "false". Because the same inlineIR function can be called in different functions using an alias definition, a new function (with possibly different attributes) has to be instantiated upon every call.
Related GH issue #1438

For `LDC_inline_ir` functions: instantiate a new "alwaysinline" function for each call

---

gen/abi-arm.cpp
gen/abi-generic.h

structs with 8-byte alignment or greater needs to be rewritten as array of i64 to be compatible with the AAPCS C ABI.
Picked up by recent test added to runnable/ldc_cabi1.d for passing struct with 8-doubles (thanks to  @redstar).

ARM AAPCS: struct rewrite with 8-byte alignment

---

README.md

Hi all,
I think it's quite convenient to show the users for which distribution a package is available.
Moreover it would be quite nice if on the [dlang download page](http://dlang.org/download.html) a user would be redirected to these installation instructions (e.g. then
https://github.com/ldc-developers/ldc/README.md#using-a-package) instead of the Github releases page.
PS: Did I miss a distro (you probably know this better)?

install from package instructions

---

tests/ir/atomicrmw.d

RMW operations on shared values have been deprecated for quite
some while, but since the test suite is not built with -de, this
has not been caught.
GitHub: Fixes #1454.

core.atomic: Fix atomicOp template constraint for -de

---

CMakeLists.txt

This fixes building with the ldc2-packaging scripts on Mac OS X.

[CMake] Allow linking with libc++, detected by "stdlib=libc++" in CMAKE_EXE_LINKER_FLAGS

---

runtime/CMakeLists.txt

Upstream does not use -d (anymore) either.

Do not squelch deprecation messages when building druntime/Phobos

---

CMakeLists.txt
cmake/Modules/FindDCompiler.cmake

Use with `cmake -DD_COMPILER=ldmd2`. Resolves issue #1320

[cmake] Allow specification of D_COMPILER on CMake cmdline.

---

ddmd/declaration.d

It was added ages ago to work around an issue with tuples not being
expanded in function arguments and/or variable declarations, but
it doesn't seem to be required anymore.

Remove TupleDeclaration.semantic3

---

.travis.yml

To test that there is a bootstrapping sequence with 1 intermediate C++-based D compiler
(instead of having to hop several compiler versions due to D features used that are not available in the C++-based version).

[Travis] Make sure we test at least one build with an C++-buildable LDC

---

ir/irclass.cpp
ir/irtypeclass.cpp
ir/irtypeclass.h

The vtbl still contained the class info entry for C++ interfaces.

fix issue #1473: ICE when implementing extern(C++) interfaces

---

CMakeLists.txt

This fixes issue #1460. It allows to pass linker flags from the commandline.

Append CMAKE_EXE_LINKER_FLAGS to the LDC_FLAG_LIST.

---

.travis.yml
CMakeLists.txt
circle.yml

- there is no need to select the C runtime on the command line, the C++ files already select it
- disable copying ldc2.conf to itself
- set optimization options depending on configuration
I hope this doesn't break other platforms...

fix cmake generation of VS projects:

---

.travis.yml

Switch to LLVM 3.8 because 3.8.0 was used for the beta release.

[Travis] Switch to LLVM 3.8 for OS X.

---

CMakeLists.txt

- Use CMAKE_EXECUTABLE_SUFFIX instead of custom variable
- Remove endianess check. The C++ source is endian-clean

Small CMakeLists.txt tweaks

---

tests/codegen/cpp_interface.d

Lit tests still don't run locally for me, so better try them in a PR.
Any idea what's wrong here:
```
Start testing: May 14 08:24 Romance Summer Time
----------------------------------------------------------
1909/1909 Testing: lit-tests
1909/1909 Test: lit-tests
Command: "C:/l/Python27/python.exe" "runlit.py" "-v" "."
Directory: C:/s/d/ldc/ninja-ldc/tests
"lit-tests" start time: May 14 08:24 Romance Summer Time
Output:
----------------------------------------------------------
-- Testing: 9 tests, 8 threads --
FAIL: LDC :: codegen/cpp_interface.d (1 of 9)
******************** TEST 'LDC :: codegen/cpp_interface.d' FAILED ********************
Script:
--
C:/s/d/ldc/ninja-ldc/bin/ldc2 -c C:\s\d\ldc\ldc\tests\codegen\cpp_interface.d
--
Exit Code: 127
Command Output (stdout):
--
Command 0: …
```

add testcase for issue 1481

---

cmake/Modules/FindLLVM.cmake

As usual the AMDGPUUtils library is missing in the list of libraries.

LLVM: Prevent linking error if linking against AMDGPU target.

---

driver/cl_options.cpp
driver/main.cpp
driver/targetmachine.cpp
driver/targetmachine.h

The value is now optional as there is nothing like a default relocation.

LLVM 3.9: llvm::Reloc::Default was removed.

---

driver/configfile.cpp
driver/configfile.h
driver/main.cpp
driver/targetmachine.h

This allows selecting the configuration group by target triple extracted from the command line.
This allows using the same installation for both 32-bit and 64-bit builds on Windows by just having different lib folders. Not sure how this is done on other platforms...

Allow different configurations in the ldc2.conf

---

gen/functions.cpp
gen/uda.cpp
gen/uda.h
ir/irfunction.cpp
ir/irfunction.h
tests/codegen/attr_fastmath.d
tests/codegen/attr_fastmath_x86.d
tests/codegen/attr_llvmFMF.d
tests/codegen/inlineIR_math.d

Adds `@fastMath` that should enable aggressive math optimizations.
The attribute sets "fast" attributes on all floating point operations, ~~but does not set "unsafe-fp-math". I think it _should_ set "unsafe-fp-math" though.~~ and it sets unsafe-fp-math=true. This will also enable reassociation optimizations.  ~~(`@fastMath(false)` will do the opposite)~~

Add @fastmath magic UDA

---

appveyor.yml

3 days old and free of the MS (CodeView) debug info regression shown by `runnable\opover2.d` on Win64 when using `-enable-inlining`.

AppVeyor: Use a slightly older LLVM build

---

appveyor.yml

[AppVeyor] Use LDC-1.0.0-beta2 for two of the four builds.

---

ddmd/globals.d
ddmd/globals.h
ddmd/mtype.d
driver/cl_options.cpp
gen/functions.cpp
gen/mangling.cpp
gen/mangling.h
ir/iraggr.cpp
ir/irclass.cpp
tests/codegen/hashed_mangling.d

This adds MD5 hashing of symbol names that are larger than threshold set by `-hashthres`. 
What is very unfortunate is that std.traits depends on the mangled name, doing string parsing of the mangled name of symbols to obtain symbol traits. This means that mangling cannot be changed (dramatically, like hashing) at a high level, and the hashing has to be done on a lower level.
Hashed symbols look like this:
`_D3one3two5three3L3433_46a82aac733d8a4b3588d7fa8937aad66Result3fooZ`
`ddemangle` gives:
`one.two.three.L34._46a82aac733d8a4b3588d7fa8937aad6.Result.foo`
Meaning: this symbol is defined in module `one.two.three` on line 34. The identifier is `foo` and is contained in the struct or class `Result`.
Symbols that may be hashed:
- functions
- struct/class initializer
- vtable
- typeinfo …

Add experimental -hash-threshold option to hash very long symbol names.

---

tests/CMakeLists.txt
tests/codegen/align.d
tests/codegen/hashed_mangling.d
tests/lit.site.cfg.in

Fixes the failing symbol hashing test.
Marks align.d test as an expected failure on Windows x86, see #1356

Lit tests on Windows x86 now PASS

---

appveyor.yml
driver/main.cpp
driver/targetmachine.cpp

`get32BitArchVariant()` for x86_64 seems to return i386 which is inconsistent with i686 (Pentium Pro+) for a native 32-bit build.

AppVeyor: Publish a multilib CI build

---

tests/codegen/attr_fastmath_x86.d
tests/codegen/attr_target_x86.d
tests/codegen/inlineIR_math.d

If I understand correctly, the "official" way of setting target triple is with an equals sign.
This PR fixes that in the tests.

Tests: use -mtriple= instead of without equals sign.

---

tests/codegen/simd_unaligned.d

Resolves issue #1518. Combines druntime patches from @MartinNovak and @9il.
Druntime changes: https://github.com/ldc-developers/druntime/commit/9189ca33b473d493aea71063ec3003ed9641b283

SIMD: Fix loadUnaligned for newer LLVM types and add storeUnaligned.

---

gen/abi-aarch64.cpp
gen/abi-arm.cpp
gen/abi-generic.h
gen/abi-ppc.cpp
gen/abi-ppc64le.cpp
gen/abi-win64.cpp
gen/abi-x86-64.cpp
gen/abi-x86.cpp
gen/abi.cpp
gen/abi.h
gen/functions.cpp
gen/llvmhelpers.cpp
gen/structs.cpp
gen/tocall.cpp
ir/irfuncty.cpp
ir/irfuncty.h

Allow ABIRewrites to return the D parameter's LL lvalue directly.
Most rewrites store to memory anyway, so let the D parameter point directly to that memory instead of a dedicated alloca bitcopy.

Optimize ABIRewrite system for lvalues

---

ddmd/cppmangle.d
gen/abi-x86.cpp
gen/abi.h
gen/llvmhelpers.cpp
gen/mangling.cpp
gen/mangling.h
gen/module.cpp
gen/runtime.cpp
gen/toir.cpp
tests/codegen/mangling_gh1519.d

This removes the 0x1 byte from `.mangleof` accessible from user code.
Resolves issue #1519

Windows: Move the prepending of 0x1 to C++ mangled functions from frontend to the backend.

---

LICENSE

- DDMD uses Boost Software License
- Update LDC copyright to 2016
This fixes issue #1322.

Fix LICENSE file.

---

circle.yml

Attempt to fix CI testing on CircleCI.

[CircleCI] Use pre-built LLVM binaries from llvm.org/releases

---

ddmd/globals.d
ddmd/globals.h
driver/codegenerator.cpp
driver/linker.cpp
driver/linker.h
driver/main.cpp
tests/linking/inputs/link_bitcode_import.d
tests/linking/inputs/link_bitcode_input.d
tests/linking/inputs/link_bitcode_input3.d
tests/linking/inputs/link_bitcode_libs_input.d
tests/linking/link_bitcode.d
tests/linking/link_bitcode_libs.d

Accept LLVM bitcode files (*.bc) on the commandline and add the code to the first source file on the cmdline (the first emitted module).
(succesfully tested on Weka's codebase)

Accept LLVM bitcode files (*.bc) on the commandline

---

ddmd/hooks.d
ddmd/idgen.d
ddmd/traits.d
gen/ldctraits.cpp
gen/ldctraits.d
tests/semantic/target_traits.d
tests/semantic/target_traits_diag.d

Edit: updated to current state of the PR.  (removed `__traits(targetFeatures)`)
This adds the following LDC-specific traits:
```D
__traits(targetCPU) == "broadwell"
__traits(targetHasFeature, "sse2") == bool
```
Example usage:
```D
import std.stdio;
void main() {
writeln("CPU = ", __traits(targetCPU));
writeln("Has 'sse3' = ", __traits(targetHasFeature, "sse3"));
writeln("Has 'sse4' = ", __traits(targetHasFeature, "sse4"));
writeln("Has 'sse4.1' = ", __traits(targetHasFeature, "sse4.1"));
}
```
Outputs on my machine:
```
❯ ../bin/ldc2 -wi -mcpu=native -run ../../tests/codegen/target_traits.d
CPU = haswell
Has 'sse3' = true
Has 'sse4' = false
Has 'sse4.1' = true
```

Add LDC-specific traits for CTFE information about the target machine.

---

driver/main.cpp

(tests ~~well~~ will be upstreamed)

Add predefined version identifier D_Coverage.

---

driver/codegenerator.cpp
driver/linker.cpp
tests/linking/link_bitcode.d
tests/linking/link_bitcode_libs.d
tests/semantic/target_traits_diag.d

I had too much trouble supporting bitcode file arguments for LLVM 3.5, so I disabled it (gives an error).
Also had to disable a __traits(target..) test because of LLVM-dependent error messaging.

Fix build for LLVM < 3.8

---

ddmd/cond.d

Add the identifiers that just got added to upstream DMD.

Add PS4 version identifier

---

gen/toir.cpp

This may be enough to fix https://github.com/ldc-developers/ldc/issues/1471 (at least there's no crash anymore for @rainers' minimal testcase).

object.classinfo: Return a TypeInfo_Class instead of a TypeInfo_Interface

---

driver/codegenerator.cpp

We had switched to a somewhat simplified implementation Martin
came up with for DMD based on our old one. Unfortunately, that
turned out not to work for certain ld.bfd versions on Linux
(e.g. 2.26.0.20160501), where the .bss section from other shared
objects would be picked up instead.
This reverts commit 08ad4fddb5af0024253a5e36513b808e2905d013.
GitHub: Fixes #1534.

codegen, runtime: Go back to old executable .bss range detection

---

gen/abi-arm.cpp

Some tests from the dmd testsuite fail because of this, specifically `ctest10` from `cabi1` and a handful from `ldc_cabi1`.  Once I put this fix in, the entire dmd testsuite passes natively on Android/ARM.  Presumably Dan put this in for `armhf` but iOS is `armel` also, isn't it?  Once @smolt and I hash out how to make this work across all tested ARM systems, I'll modify this patch and remove the WIP tag, then someone can merge.

Fix ARM soft-float ABI when passing structs with floating-point numbers

---

runtime/profile-rt/DefineBuildProfileRT.cmake

I just discovered that PGO in LLVM3.9 has yet again become more awesome: automatic merging of profile data across multiple runs of the same executable.
The define checked for in this PR is for file-locking during the awesome on-the-fly profile merging feature using `%m` in `-fprofile-instr-generate=abc_%m_xyz` (for example).

[profile-rt] Add check for defining COMPILER_RT_HAS_FCNTL_LCK in CMake script.

---

CMakeLists.txt
driver/cl_options.cpp
driver/cl_options.h
driver/ir2obj_cache.cpp
driver/ir2obj_cache.h
driver/toobj.cpp
tests/linking/ir2obj_caching.d

This adds a caching mechanism such that compiling the same source twice should be faster as it will use the previously generated object file.
The caching granularity is per LLVM module.
With  `-ir2obj-cache=<cache dir>`, LDC does:
1. Parse/analyse/etc the code
2. Generate LLVM IR
**3. Create hash of LLVM IR  (NEW)**
**4. Do hash lookup in cachedir.  (NEW)**
**If hash found: output symlink to cached object file and exit.  (NEW)**
5. Optimization
6. Output object file
**7. Store hash-objectfile in cache dir.  (NEW)**
Machine codegen takes a lot of time, so this caching results in a significant speed up (~65sec -> ~39sec on testcase). Generating the hash is done by hashing the raw bitcode output from LLVM. This is not for free and takes quite some time: it takes time to generate a 200MB …

Add IR-to-Objectcode caching with `-ir2obj-cache=<cache dir>`.

---

circle.yml

Still an old LLVM revision, but should be up-to-date soon.
http://lists.llvm.org/pipermail/llvm-dev/2016-June/101500.html

[CircleCI] Use official LLVM APT again

---

ddmd/attrib.d
ddmd/attrib.h
ddmd/cppmangle.d
ddmd/dscope.d
ddmd/globals.d
ddmd/globals.h
ddmd/hdrgen.d
ddmd/mtype.d
ddmd/parse.d
ddmd/visitor.d
ddmd/visitor.h

VS has different name manglings for classes and structs. With the
new extern(C++, class) and extern(C++, struct) declarations, the
name mangling algorithm is changed to use a mangling different
from the used D entity.
A common use case is to map a value type modeled as class in C++ to
a struct in D.
This is backport of https://github.com/dlang/dmd/pull/5875.

Add new extern(C++, class) and extern(C++, struct) declarations.

---

gen/llvmhelpers.cpp

The D types of the variable and the right-hand-side of the init `AssignExp` must match; this fixes issue #1548.
Don't restrict it to memory-only types anymore though; the sret-check performed by `DtoIsReturnInArg()` should suffice and makes more sense to me.
A test will follow once merged.

Tighten NRVO detection for VarDeclarations

---

gen/binops.cpp
gen/complex.cpp
gen/complex.h
gen/dvalue.cpp
gen/dvalue.h
gen/llvmhelpers.cpp
gen/llvmhelpers.h
gen/toir.cpp

* Introduce a DRValue base class to be able to discriminate between DLValues and DRValues (e.g., function parameters).
* Let DValue::getRVal() return each DValue's value as DRValue. This allows to convert a DLValue to a DRValue while retaining the D type, something we've previously lost when returning the low-level rvalue directly.
* Let the DtoR/LVal() helpers be the only way to convert a DValue to a low-level value.

Continue with DValue refactoring and fix issue #1327

---

gen/typinf.cpp

There was an ICE when building an enum's initializer for its TypeInfo if the enum's base type was a struct.

Fix issue #1581

---

gen/ms-cxx-helper.cpp

See https://llvm.org/bugs/show_bug.cgi?id=25162
However the LLVM inliner now knows not to inline functions inside cleanup pads and so this is no longer needed. I have tested with clang (trunk) and clang also no longer marks function calls explicitly with noinline: the inliner no longer tries to inline `alwaysinline` functions.
http://llvm.org/viewvc/llvm-project/cfe/trunk/test/CodeGenCXX/microsoft-abi-eh-cleanups.cpp?r1=251576&r2=255423&diff_format=h
The change is necessary because setting `noinline` conflicts with functions that have `alwaysinline` attribute added (due to `pragma(inline, true)`).
@rainers Can you confirm this is correct? Thanks.
(this PR is needed for https://github.com/ldc-developers/ldc/pull/1577)

Remove explicit `noinline` call attribute inside SEH catch/cleanup pads.

---

driver/configfile.cpp
driver/linker.cpp

Recent LLVM master switched to enable UNICODE on Windows, breaking some code in LDC.

use *W-functions if UNICODE #defined on windows

---

gen/toir.cpp

Don't perform a vtable lookup for those, resolve them directly instead.
Fixes issue #1450, where calling the base method in the overriding method resulted in an infinite loop and corresponding stack overflow.

Resolve virtual base functions (super.foo()) correctly

---

gen/functions.cpp
gen/llvmhelpers.cpp
gen/llvmhelpers.h
gen/statements.cpp
gen/tocall.cpp
gen/toir.cpp
ir/irfunction.h
tests/codegen/align.d
tests/codegen/in_place_construct.d

The plan is to in-place construct return expressions too if the function uses sret.
And I'd also like to get rid of all the temporary struct literals (possibly array literals too) which get memcopied too instead of being directly constructed into the variable. This should make life easier for the LLVM optimizer and speed-up debug builds as well as render the IR more compact and easier to read.

Some more direct in-place construction

---

gen/statements.cpp
tests/codegen/in_place_construct.d

Okay so this sadly isn't working.
Some Phobos unittests crash (and so does dmd-testsuite's `d_do_test` tool), apparently due to a lifetime issue exposed by regex stuff. Specifically, the `std.regex.internal.parser` tests crash in a `std.uni.CowArray` dtor (the single field, a `uint[]` slice, seems corrupt when setting the `refCount` property). This is triggered by `std.regex.internal.ir.wordCharacter()` which uses lazy caching via `memoizeExpr()`.
So it seems like there's a missing postblit call. But iirc, the IR for `std.regex.internal.ir` was pretty similar (except for a lot of omitted `.sret_tmp` allocas + memcopies), I didn't immediately spot the missing postblit call. Various experiments with `doPostblit` all failed (e.g., using the current logic for in-place construction too), and …

Use direct sret construction for return statements too

---

gen/dibuilder.cpp
gen/dibuilder.h
gen/nested.cpp
gen/statements.cpp
ir/irfunction.cpp
tests/debuginfo/msvc_eh.d
tests/debuginfo/nested.d
tests/debuginfo/nested_llvm306.d
tests/debuginfo/nested_llvm307.d
tests/lit.site.cfg.in

This is PR #1597 recreated for `master`.
*** * * * * * * ***
Debug info generation is broken when LDC is built against LLVM 3.8:
```
(gdb) break test.d:20  <= works
(gdb) run
(gdb) bt  <= no location info
#0  0x0000000000402f49 in D main ()
(gdb) info locals
No symbol table info available.
```
A `llvm::Function::setSubprogram()` call to assign the descriptor to the function was missing. Restoring it resulted in new compilation errors while building druntime and phobos, which were due to function parameters accessed from a nested function being declared as function parameters (they're not, they're fields of `nest_arg`) instead of "auto variables", and setting two variables for the same parameter index was triggering an assert:
```
ldc2: DwarfDebug.h:125: void …
```

Debug info generation fixes for LLVM >= 3.8

---

circle.yml

Attempt to fix CircleCI build, by pointing it to the LLVM 3.9 APT repo.
CircleCI cannot do matrix builds it seems. :(
So we have to choose whether CircleCI should test LLVM trunk or LLVM 3.9.

[CircleCI] Fix Circle CI build.

---

gen/uda.cpp
tests/codegen/attr_optstrat.d

I need this for debugging so implemented it. Any alternative ideas for the name "optStrat"?
Resolves #1549.
druntime change: https://github.com/ldc-developers/druntime/commit/1a718598bc8bf6ffbc68492544df33fe8558b8a4

Implement @optStrategy UDA.

---

ddmd/attrib.h
ddmd/ctfe.h
ddmd/declaration.h
ddmd/dsymbol.h
ddmd/expression.h
ddmd/identifier.h
ddmd/init.h
ddmd/module.h
ddmd/mtype.h
ddmd/root/array.h
ddmd/root/object.h
ddmd/statement.h
ddmd/template.h
ddmd/version.h
gen/asm-x86.h
gen/classes.cpp
gen/classes.h
gen/functions.cpp

This fixes incorrect overriding of class methods and gets rid of many C++ warnings.

Apply DDMD PR #5885 (f5f9150ea57cce5fabb43c79ff1b187d34d37044).

---

driver/exe_path.cpp
driver/exe_path.h
driver/ldmd.cpp
driver/main.cpp

Taking the address of `main` is UB in C++. Reading LLVM's source, any function address can be used (that's what clang does too).
See Clang's examples/clang-interpreter/main.cpp - Clang C Interpreter Example.

Refactor the call to `llvm::sys::fs::getMainExecutable`.

---

gen/nested.cpp
tests/debuginfo/nested.d
tests/debuginfo/nested_llvm306.d
tests/debuginfo/nested_llvm307.d

__See #1598 for context.__
Declare debuginfo directly on the GEP instead of on the frame alloca+offset, . An explicit DW_OP_deref is necessary (tested in LLDB).
Resolves an ICE introduced by PR #1598.

Fix debuginfo generation for the local variable frame for a function with nested functions

---

CMakeLists.txt
cmake/Modules/ExtractDMDSystemLinker.cmake
cmake/Modules/FindDCompiler.cmake
cmake/Modules/FindLLVM.cmake
utils/CMakeLists.txt

Currently, we are translating the linker flags for LLVM/libconfig and from `CMAKE_EXE_LINKER_FLAGS` into `-L` options. Since DMD/LDC prefix `-L` options by `-Xlinker` before passing them to the GCC driver (causing the latter to forward it directly to the underlying `ld`), this does not work in the general case, causing issues such as #1494.
In https://github.com/ldc-developers/ldc/pull/1468, a few driver-only flags were special-cased in LDC so that `-Xlinker` is not applied to them. However, I don't think this is a viable strategy in the long run. First of all, there are quite a few more options which are supposed to be passed to the linker driver instead of the linker. But rather more importantly, this only works with an LDC version that contains this fix, and not DMD.
Thus, we need a …

cmake: Directly use (g)cc for linking on Unix-like systems

---

gen/arrays.cpp
gen/llvmhelpers.cpp
gen/llvmhelpers.h
gen/statements.cpp
gen/toir.cpp

Not happy at all with this change, that whole `canSkipPostblit` logic seems quite fragile. It's determined in `visit(AssignExp*)`, passed to `DtoAssign()`, and exclusively used in `DtoArrayAssign()` (i.e., when assigning to a static/dynamic array).

Fix issue #1608

---

driver/main.cpp

(note: AppVeyor is temporary on LLVM 4.0)

Fix LLVM 4.0 build.

---

gen/statements.cpp
tests/codegen/inputs/switch_ICE_gh1638_bar.d
tests/codegen/switch_ICE_gh1638.d

Note: this fixes the bug but leaves proper refactoring for later.
We should not store codegen state into the AST and the variables touched in this commit should be moved out of the AST. Added a TODO item for it.
(I have tested several times that the testcase fails without the fix.)

Fix ICE upon second codegen pass of the same SwitchStatement.

---

gen/pgo.cpp
gen/pgo.h
gen/tocall.cpp
tests/PGO/indirect_calls.d

Now that LLVM 3.9 is being prepared for release, I am adding my indirect call PGO work.
_Only applies to LLVM >= 3.9. No functional changes intended for LLVM < 3.9._
This PR adds instrumentation code and metadata tagging code for PGO of indirect calls (a call through a function pointer that is unknown at compile-time).
The new PGO functionality is enabled by default but can be disabled with `-disable-pgo-indirect-calls`.
AFAIK this puts us on par with all front-end PGO capabilities of LLVM/Clang 3.9.
Because it is a relatively simple addition to the code (and for the unreleased LLVM 3.9 only), I hope this can still make it into the 1.1.0 release.
Blog article: https://johanengelen.github.io/ldc/2016/04/13/PGO-in-LDC-virtual-calls.html

[PGO] Add Indirect Call instrumentation and promotion.

---

ddmd/func.d
tests/codegen/func_contracts_gh1543.d

It appears that syntaxCopy can be used with the current frontend.

Fix #1543.

---

driver/targetmachine.cpp

Modern Linux distributions have their toolchain generate PIC code for
additional security features (like ASLR).
Since there is no (sane) way to detect whether the toolchain defaults to
PIC code, we simply default to PIC code on all Linux
distributions to avoid linking issues on these OSes.
The relocation model can be switched back to non-PIC code manually at
any time.
This change resolves issue #1618

Default to PIC code on Linux

---

driver/main.cpp
gen/optimizer.cpp

For LLVM >= 3.9, let profile-rt set the default filename. 
This prevents extra stderr messages when overriding the filename using the "LLVM_PROFILE_FILE" environment variable.

[PGO] For LLVM >= 3.9, let profile-rt set the default filename. 

---

ddmd/dimport.d
ddmd/dmodule.d
ddmd/expression.d
ddmd/module.h
driver/codegenerator.d
driver/main.cpp

This eliminates the hidden-virtuals warning flood.
See
https://github.com/dlang/dmd/pull/6001
https://github.com/dlang/dmd/commit/60f622ff1b95cb2f9236cda0ed886aa7ea492384
and
https://github.com/dlang/dmd/pull/6038

Early merge front-end fixes for Module.semantic.

---

CMakeLists.txt

This way, we don't rebuild all the D modules on changes to the
C++ bits anymore.

cmake: Split D module compile and link dependencies

---

.travis.yml
appveyor.yml
circle.yml

Result on my quad-core for dmd-testsuite-debug, using `DMD_TESTSUITE_MAKE_ARGS=-j4`: 490 secs => 175 secs
I've also used the opportunity to streamline the Travis/CircleCI/AppVeyor scripts.
The tests order has changed for AppVeyor (dmd-testsuite => Lit tests => unit tests) and the unit tests execution has been parallelized.
For CircleCI, the unittest compilation should now be properly parallelized, which should give another nice speed-up.

CI: Parallelize dmd-testsuite execution

---

gen/function-inlining.cpp
tests/codegen/inlining_invariants_gh1678.d

Resolves #1678.
If this fixes things, I'll try to make the testcase independent of phobos. That should also make it compile much faster.

Disable cross-module inlining of functions that call __invariant*.

---

gen/runtime.cpp

This fixes issue #958 by checking the function type of an existing function declaration with the same runtime function name inside the codegen'd module.
This should normally be an existing forward declaration from a previous runtime call, but the user is free to declare (and even implement) it too.
The LOC for the error is empty as the provided `loc` may likely be from a template instantiation from another module.

Check existing runtime function declarations for matching type

---

gen/runtime.cpp

Reverts ldc-developers/ldc#1570.
This broke the build due to mismatch with the _d_dso_registry definition in druntime. We should probably just change the latter to take a void* instead of CompilerDSOData*.

Revert "Check existing runtime function declarations for matching type"

---

gen/funcgenstate.cpp
gen/funcgenstate.h
gen/statements.cpp

We got two new warnings:
```
In file included from ../gen/funcgenstate.cpp:10:
.././gen/funcgenstate.h:129:12: warning: private field 'irs' is not used [-Wunused-private-field]
IRState &irs;
^
.././gen/funcgenstate.h:163:25: warning: private field 'llFunc' is not used [-Wunused-private-field]
llvm::Function *const llFunc;
^
```
The first warning appears to be a clang bug :(, the second one is fixed by this PR.
Also removed use of `gIR` (originally `llFunc` was used instead of `gIR` for creating BBs).

Fix unused private field warning (`SwitchCaseTargets::llFunc`) and remove use of global gIR.

---

gen/toir.cpp

This was hit when compiling `ddmd/lexer.d:1189`, where a `const(T)*` is implicitly cast to a `const(T*)`.
The `DLValue` ctor makes sure the LL pointer and the D type are compatible.

Fix too restrictive assertion for binassigns

---

vcbuild/msvcEnv.bat

Based on http://forum.dlang.org/post/xnjxxqypqycxlhzgzsrt@forum.dlang.org (thanks André!). Visual Studio provides the same keys in HKLM, so detecting them this way should work for both Visual Studio and the stand-alone Build Tools.
The lookup outside `WOW6432Node` is for 32-bit Windows.
A user-provided `LDC_VSDIR` environment variable doesn't have to end with a backslash anymore, and may point to a VS folder (backward-compatible) or a VC folder directly.

Windows: Detect Visual C++ Build Tools automatically

---

runtime/CMakeLists.txt

Avoids the associated deprecation/policy warning.

cmake: Avoid deprecated TARGET/LOCATION property

---

gen/typinf.cpp
ir/irtypeclass.cpp

I have no idea about all the implications of this, but it seems to fix issue #1698.

Fix issue #1698 (missing semantic3() for special member functions)

---

circle.yml
gen/toconstelem.cpp

Errors are gagged while trying to create a constant initializer for an associative array literal. So don't die with an assertion if the cast source is a NewExp (or something else than a supported ClassReferenceExp),
emit a gaggable error instead.
A dmd-testsuite test will follow once merged, as usual.

Fix issue #1723

---

circle.yml
gen/dibuilder.cpp
tests/debuginfo/codeview.d
tests/lit.site.cfg.in

Changes:
- byte,ubyte should be encoded as DW_ATE_signed_char/DW_ATE_unsigned_char, not DW_ATE_signed/DW_ATE_unsigned
- encode wchar,dchar as UTF
- do not declare struct/class definitions as FlagFwdDecl
- pass deco as unique identifier to UDTs
- dynamic arrays: use type name, don't leave it empty
- use proper type name for delegates
- add support for type "void" and "typeof(null)"
Not sure how much of this can negatively affect other platforms. Should I put it under some Windows/codeView specific conditional?

Issue 1716: Improve CodeView debug info

---

gen/dibuilder.cpp
gen/dibuilder.h
tests/debuginfo/cvbasictypes.d

Maps imaginary types to the floating point types, creates a struct for complex types.

CodeView: add support for imaginary and complex types

---

tests/debuginfo/codeview.d
tests/debuginfo/cvbasictypes.d

this disables the default symbol search path that might access the MS symbol servers

Fix long running codeview tests

---

circle.yml
cmake/Modules/FindLLVM.cmake
gen/optimizer.cpp

Now that LLVM 3.9 is released, we can use Travis and AppVeyor for all "serious" testing: they must be green. And we can use CircleCI for LLVM 4.0 (trunk) testing that may break e.g. upon LLVM API changes. This way, we get notified early about relevant LLVM trunk changes, and can react with easy small LDC patches.
Makes sense?
Also see https://forum.dlang.org/thread/nwajbeceaokohknjhlqb@forum.dlang.org

[CircleCI] Use LLVM 4.0 from APT

---

gen/function-inlining.cpp
gen/optimizer.cpp
tests/codegen/inlining_imports.d
tests/codegen/inlining_imports_pragma.d
tests/codegen/inlining_leakdefinitions.d
tests/codegen/inlining_stdlib.d
tests/codegen/inlining_templates.d

A few subtle cross-module inlining bugs have been discovered, so let's disable it for now per default. See #1718.
This PR completely disables cross-module inlining unless explicitly enabled through the cmdline flag `-enable-cross-module-inlining`.
In particular, this disables cross-module inlining of `pragma(inline, true)` functions.

Only enable cross-module inlining when explicitly set on the commandline.

---

driver/codegenerator.cpp
gen/inlineir.cpp
tests/codegen/discard_value_names_gh1749.d
tests/codegen/inputs/input_discard_valuename.d

LLVMContext::setDiscardValueNames(true) when not compiling to textual IR

---

tests/codegen/discard_value_names_ir2obj_cache.d

With local value name discarding, the IR and IR hash do not depend on the actual local variable name. So a name change should not result in a cache miss.
@klickverbot : an awesome consequence of https://github.com/ldc-developers/ldc/pull/1759 !

Add ir2obj cache test upon local variable name change.

---

driver/ir2obj_cache_pruning.d

Two bugs:
- relative size pruning is not performed when there is not also an absolute size limit
- the relative size limit was not calculated correctly.
I don't know how to test the relative size pruning well, so... no tests.

ir2obj-cache: fix bugs in relative size pruning.

---

gen/dibuilder.cpp

I chose this over `(void)...`.

Fix unused var warning.

---

CMakeLists.txt
cmake/Modules/FindLLVM.cmake

At least on Windows, library debuginfomsf is needed by debuginfocodeview.

fix build with LLVM 4.0

---

gen/dibuilder.cpp
gen/dibuilder.h
tests/debuginfo/cvbaseclass.d

uses inheritance information for base classes instead of listing base class members in derived classes

Debuginfo: add inheritance information to classes

---

gen/dibuilder.cpp
gen/dibuilder.h
gen/functions.cpp
tests/debuginfo/codeview.d
tests/debuginfo/nested.d
tests/debuginfo/nested_llvm306.d
tests/debuginfo/nested_llvm307.d

see https://github.com/ldc-developers/ldc/issues/1716
Is this relevant for gdb, too?

CodeView: fix display of dynamic array arguments

---

gen/dibuilder.cpp
tests/debuginfo/cvvector.d

This fixes vectors of void showing as delegates in debuggers (or asserting early).

CodeView: fix vector types void16 and void32

---

.travis.yml
circle.yml
ddmd/globals.d
ddmd/globals.h
driver/cl_options.cpp
gen/dibuilder.cpp
tests/d2/CMakeLists.txt

Another attempt at getting these running. gdb works much better if `-g` is used instead of `-gc` when compiling, as gdb then uses the correct initial source file and interprets global `uint` variables correctly.
@kinke I hope it's ok that I abuse the gdb branch by merging current dmd-testsuite's ldc.
One known issue is "optimized-out" variable in gdb10311.d.
see also https://github.com/ldc-developers/ldc/pull/1658

enable gdb tests in the dmd-testsuite

---

gen/toir.cpp
tests/codegen/complex_postexpr_gh1806.d

As you can see I got tangled up while trying to get trough the forest of casts :)
I'm not very fond of the `toElem` call, nor to the fact I'm using `LLConstantFP` directly instead of `DtoConstFP` but, as stated before, I got lost while trying to figure the how to jump forth and back between the llvm and the frontend types.
Cheers :)

Produce correct code for increment/decrement operations on complex types

---

gen/dibuilder.cpp
gen/dibuilder.h
tests/debuginfo/srcname.d

instead try harder to find a suitable filename and line location.
In case of implicitly generated functions without any information, it now uses the line of the declaration.

Fix issue #87: do not use "." for missing debug line info

---

driver/cl_options.cpp
driver/cl_options.h
driver/ir2obj_cache.cpp
driver/main.cpp
gen/optimizer.cpp
gen/optimizer.h
tests/linking/ir2obj_caching_flags1.d

This fixes ir2obj caching bugs (incorrect cache hits) when using some of the more exotic command line flags.

ir2obj cache: input all optimization settings into the hash.

---

circle.yml

This change makes sure that LDC can build itself. To protect against issues like: https://github.com/ldc-developers/ldc/issues/1774
The extra CircleCI test time is acceptable for me.
Edit: looks like it will add 7 minutes to the CircleCI build.

CircleCI: build LDC with itself and test that version.

---

gen/dibuilder.cpp
gen/dibuilder.h

Better annotate reasons for not emitting debug info. Also make it
easier to change conditions under which DI should be emitted.
This will make it easier when more dcompute related code is added, as
there cannot be any DI emission for dcompute (SPIRV does allow some
extra debug info but that is not in the current scope of dcompute yet, and done
a very different way, ~~not sure about CUDA~~ CUDA appears to support dwarf, with some extensions).

dcompute: [NFC] Refactor emission of debug info.

---

gen/functions.cpp
tests/codegen/vastart_vaend_gh1744.d

Add a matching call to llvm.va_end when llvm.va_start was called.

---

gen/dibuilder.cpp
tests/debuginfo/args_cdb.d

Size 0 caused references to be encoded as "near32", not "__ptr64".
Arguments passed by reference still need to be actually used in the called function to be shown, otherwise they seemed to be optimized away.

CodeView: arguments passed by reference not shown

---

gen/dibuilder.cpp
gen/dibuilder.h
gen/functions.cpp
gen/nested.cpp
tests/debuginfo/args_cdb.d
tests/debuginfo/nested_llvm306.d
tests/debuginfo/nested_llvm307.d
tests/debuginfo/strings_cdb.d

Non-MSVC targets: emit all parameters (except for captured ones) as DI parameters.
MSVC targets: emit all parameters as DI locals to work around misc. issues discussed in PR #1804.

Adapt emission of debuginfos for parameters

---

driver/cl_options.cpp
gen/cl_helpers.h
gen/llvmhelpers.cpp
gen/optimizer.cpp
tools/ldc-profdata/llvm-profdata-4.0.cpp

Not sure if has landed in circleCI already, but probably will soon.

fix build against LLVM master: clEnumValEnd removed

---

gen/llvmhelpers.cpp
tests/codegen/align.d

Currently, alignment below the pointer size is ignored:
```d
align(1) ushort counter; // gets "align 8" in LLVM IR
```
So you cannot closely pack variables.
The minimum alignment is intended according to a39997d326f0d3da353d8b9f27ffd559e6fcc5d7.
Reverting a39997d326f0d3da353d8b9f27ffd559e6fcc5d7 to see which std.conv test fails.

Allow alignment below sizeof(void*).

---

gen/naked.cpp
tests/codegen/asm_constraints.d

Way better than a llvm assertion, no? :)
On my system (running `llvm 3.8.1`) an invalid constraint causes the codegen phase to hang indefinitely :\
Fixes #802.

Validate the __asm constraints.

---

gen/functions.cpp
tests/codegen/attr_targetoptions.d
tests/codegen/inlineIR_math.d

This change is needed for LTO, as the linker/LTO-codegen otherwise would use the default TargetOptions.
~~Work-in-progress: will add tests when green.~~
Note: Clang does exactly the same.

Apply TargetMachine options as function attributes in IR.

---

.travis.yml
gen/modules.cpp
gen/runtime.cpp
runtime/CMakeLists.txt

Passes all of the test suite, including the shared library tests, except for module collision checking (which is most easily implemented with a hash table, as symbol resolution works differently on OS X).
Requires/includes #1704.

Shared library support for OS X

---

gen/tocall.cpp
tests/codegen/fence_pragma.d

Think `std::atomic_signal_fence` [1], but for D.
I tried implementing this as an extra and optional argument for `LDC_fence` but then discovered the hard way that it would break the bootstrap cycle.
[1] http://en.cppreference.com/w/cpp/atomic/atomic_signal_fence

Implement single-thread fences via the LDC_fence pragma.

---

ddmd/globals.d
ddmd/globals.h
ddmd/mars.d
driver/cl_options.cpp
driver/ldmd.cpp
driver/linker.cpp

Let LDC treat relative output paths as relative to the current working directory again (as it always used to until a few weeks ago). It's more intuitive and avoids breaking build systems/scripts using LDC directly.
Only LDMD continues to prepend the -od directory to the relative output path, for DMD compatibility.
Fixes issue #1819.

Create static libs in -od directory for LDMD only

---

gen/toir.cpp

Fixes issue #1822.
`DtoResolveFunction()` explicitly excludes body-less abstract functions from being automatically declared. If we want to emit linking errors like DMD, we need a LL function for the call (we previously hadn't for abstract functions, so it was null and LDC crashed). Thus make sure the function is resolved and declared by invoking `DtoDeclareFunction()`.

Produce linking errors when calling abstract functions

---

driver/targetmachine.cpp
gen/functions.cpp
tests/codegen/attr_targetoptions.d
tests/codegen/attr_targetoptions_fp.d

Fix issue #1860
UseSoftFloat was removed from the TargetOptions in LLVM3.7. It's replacement (I believe) is the "+soft-float" target feature (in the target feature string). Inside LLVM, the "use-soft-float" attribute is upgraded to the "+soft-float" feature, so we can do that ourselves when creating the target machine.
(note that at the point where we add the attributes to the function, we have no information whether our TargetMachine was created with FloatABI:SoftFP or not)

Set `+soft-float` feature instead of `use-soft-float` attribute.

---

driver/codegenerator.cpp
gen/declarations.cpp
gen/modules.cpp
tests/codegen/inputs/module_ctor.d
tests/codegen/llvm_used_1.d

Before, when compiling multiple D modules into one LLVM module, we would emit llvm.used multiple times. All except the first would actually be recognized as llvm.used (the others would be renamed to llvm.used.* which is not recognized by LLVM).
This fixes that.
(For testing, I used the testcase that would start bugging for ThinLTO. I used the OS X triple and moduleinfo stuff, because I tried but did not find another way to get things to be added to llvm.used. Symbols referenced in inline asm are not added to llvm.used, surprisingly, but LLVM parses the assembly to find such references I think, so not a bug?)

Only emit llvm.used _once_ in an LLVM module

---

.travis.yml

Master now has funny build errors when LDC is built with dmd 2.072.0:
```
[  9%] Generating bin/ldc2
[  9%] Built target ldc2
...
[ 13%] Generating src/core/atomic-debug.o
object.Error@src/rt/minfo.d(356): Cyclic dependency between module ddmd.traits and ddmd.cond
ddmd.traits* ->
ddmd.attrib ->
ddmd.cond* ->
ddmd.expression ->
ddmd.traits*
make[2]: *** [runtime/src/core/atomic-debug.o] Error 1
make[1]: *** [runtime/CMakeFiles/druntime-ldc-debug.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 13%] [ 13%] Generating std/array.o
Generating std/ascii.o
[ 13%] object.Error@src/rt/minfo.d(356): Cyclic dependency between module ddmd.traits and ddmd.cond
ddmd.traits* ->
ddmd.attrib ->
ddmd.cond* ->
ddmd.expression ->
ddmd.traits*
```

Does DMD 2.072.0 miscompile LDC?

---

driver/cl_options.cpp
driver/cl_options.h
gen/functions.cpp
gen/runtime.cpp
gen/runtime.h
gen/statements.cpp
tests/codegen/instrumentation.d

Implement -finstrument-functions.

---

gen/logger.cpp
gen/logger.d
gen/logger.h

This adds the D counterpart of logger.{h,cpp}.
(Not currently used in D source, but I am already using it in my ccaching branch.)

Add code for logging within D code.

---

driver/toobj.cpp
driver/toobj.h
tests/codegen/gh1843.d

Use the output filename (-of or inferred) directly if a single file is emitted per compiled module.
Fixes issue #1843.

Don't necessarily enforce file extension of .bc, .ll, .s files

---

driver/cl_options.cpp
gen/dibuilder.cpp
gen/dibuilder.h
tests/debuginfo/gline_tables_only.d
tests/debuginfo/gline_tables_only2.d
tests/debuginfo/gline_tables_only3.d

implementation of -gline-tables-only flag per #1844

impl -gline-tables-only

---

driver/linker.cpp

passing /LARGEADDRESSAWARE:NO is a workaround for DWARF debug info, it causes trouble with CodeView debug info.
See https://github.com/ldc-developers/ldc/issues/1876

fix issue 1876: MS file tracker fails to run for executables built with debug info

---

driver/targetmachine.cpp
driver/targetmachine.h
driver/toobj.cpp
gen/optimizer.cpp

* dont optimise SPIR-V as turning GEPs into extracts causes the back end to assert.
* Always use llvm::TargetMachine::CGFT_AssemblyFile for ptx, if we don't
create target machine will return null
* llvm::createSPIRVWriterPass(out)->runOnModule(m) is the way to make
output happen for SPIR-V as there is no target machine for SPIR-V.

[dcompute] backend

---

gen/declarations.cpp
gen/functions.cpp
gen/llvmhelpers.cpp
tests/codegen/export.d
tests/codegen/export_crossModuleInlining.d
tests/codegen/inputs/export2.d

Map `export` visibility to LLVM DLL storage classes

---

gen/functions.cpp
gen/llvmhelpers.cpp
gen/llvmhelpers.h
gen/nested.cpp

The previous check wouldn't check intermediate aggregates for static-ness, that was one problem. The other was the assertion that the outer function can be reached as long as there are no static functions inbetween, which isn't always the case, as issue #1864 clearly shows, which is resolved by this.

Fix check if nested function can access outer function frame

---

gen/classes.cpp
gen/toir.cpp
ir/irclass.cpp
ir/irtypeclass.cpp
ir/irtypeclass.h
tests/codegen/in_place_construct_asm.d
tests/compilable/gh1741.d
tests/compilable/inputs/gh1741b.d

This gets Johan's reduced testcase in issue #1741 to compile on Linux x64, but was actually an experiment I did a couple of weeks ago wrt. issue #662. Not sure if opaqueness here is desirable, as it just hides potential function type mismatches; the primary aim was getting rid of additional semantic analysis for the function types of all virtual functions.

Opaque vtbl

---

.travis.yml

Let's see if this works (so that we can release with LLVM3.9 on OS X).

Travis: use LLVM3.9 on OS X

---

driver/cache.cpp
tests/linking/ir2obj_caching.d
tests/linking/ir2obj_caching_retrieval.d

The current retrieval mechanism (retrieve file from cache upon cache hit) is LLVM `create_link`, which creates a symbolic link on Unix/OSX and creates a hard link on Windows.  When symlinked cache files keep being used without the compiler knowing about it (e.g. they are only used by the linker), the cache pruning algorithm will delete the cached file when it becomes old.
`-cache-retrieval={copy|hardlink|link|symlink}`
This PR implements 4 different cache retrieval methods: copy, symlink, hardlink, "link" (previous behavior). "copy" is the safest, as it will work for all kinds of setups, so I've set that as the default. 
The downside is more disk space usage and longer cache retrieval time, especially for large files. The recommendation is to use "hardlink" when it works for the user's …

Implement different cache recovery mechanisms.

---

ir/irclass.cpp
tests/compilable/gh1906.d
tests/compilable/inputs/gh1906b.d

Fixes regression #1906 introduced by #1891.
Also get rid of another bug wrt. potentially failing `DtoFunctionType()` for abstract functions.

Infer return type of functions for vtbl initializer

---

driver/cl_options.cpp
driver/cl_options.h
driver/main.cpp

This generalizes the piece of code that adds the "enable-color" option, such that it is easier to add other LLVM-clashing options (such as -ffast-math, #1896 ).

Refactor the machinery to add commandline options that clash with LLVM's options [NFC]

---

ddmd/mtype.d
tests/codegen/static_array_huge.d

The limit is a workaround for an optlink bug, thus unimportant for LDC, see
https://issues.dlang.org/show_bug.cgi?id=14859
https://forum.dlang.org/post/lxzyzcatydfkxkoxfccw@forum.dlang.org

Remove the 16MB limit on static array sizes.

---

gen/uda.cpp
tests/codegen/attr_allocsize.d
tests/codegen/attr_allocsize_diag.d

Resolves https://github.com/ldc-developers/ldc/issues/1452
I implemented it "because I can". I think this leads to optimization potential for LLVM (InstCombine?) but I have not tested what kind of code becomes better.
In subsequent work, the attribute should be applied to druntime functions. In the end, I am not sure how much this brings. When we can inline e.g. `_d_allocmemory`, it will be inlined to a `malloc` call (if I'm correct) for which LLVM automatically assumes the `allocsize` attribute...

Implement the @allocSize magic UDA.

---

driver/main.cpp
tests/driver/gh1945.d

Fixes issue #1945 by allowing `-march x86` besides `-march=x86`.

Be more forgiving when pre-parsing target triple for config file lookup

---

driver/main.cpp
tests/driver/gh1941.d
tests/driver/gh1941.rsp

Fix issue #1941 by expanding response files **before** temptatively parsing an explicit `-conf=` and/or target triple for the config file lookup. After injecting the switches from the config file right after argv[0], expand again to catch any response files specified in the config file switches.

Improve support for response files in command line

---

runtime/profile-rt/DefineBuildProfileRT.cmake
runtime/profile-rt/profile-rt-39/GCDAProfiling.c
runtime/profile-rt/profile-rt-39/InstrProfilingFile.c
runtime/profile-rt/profile-rt-39/InstrProfilingInternal.h
runtime/profile-rt/profile-rt-39/InstrProfilingPort.h
runtime/profile-rt/profile-rt-39/InstrProfilingUtil.c
runtime/profile-rt/profile-rt-40/InstrProfiling.c
runtime/profile-rt/profile-rt-40/InstrProfiling.h
runtime/profile-rt/profile-rt-40/InstrProfilingFile.c
runtime/profile-rt/profile-rt-40/InstrProfilingInternal.h
runtime/profile-rt/profile-rt-40/InstrProfilingPort.h
runtime/profile-rt/profile-rt-40/InstrProfilingUtil.c
runtime/profile-rt/profile-rt-40/InstrProfilingValue.c
runtime/profile-rt/profile-rt-40/WindowsMMap.c

Because of https://reviews.llvm.org/D27178 , profile-rt no longer needs ws2_32.lib on Windows (LLVM >= 4.0).
The LLVM 3.9 changes are not so important that they need to be put into the 1.1.0 release.

Update profile-rt for LLVM 3.9 and 4.0.

---

gen/runtime.cpp
tests/codegen/instrumentation.d

Don't know whether this has ever worked, but... according to LLVM spec passing a non-zero argument to `llvm.returnaddress` is likely to be incorrect. More importantly: we need the return address of the current function (level 0), not of the calling function (level 1).
@LemonBoy did you ever test whether `uftrace` gives sane output for LDC programs?

Fix -finstrument-functions. The wrong return address was used.

---

driver/cache.cpp
driver/cache_pruning.d

This PR prevents poisoned cache entries when LDC is aborted during writing to the cache.

Cache: Add files atomically to the cache (copy to temp file + rename)

---

gen/classes.cpp
gen/dibuilder.cpp
gen/functions.cpp
gen/irstate.cpp
gen/irstate.h
gen/llvmhelpers.cpp
gen/moduleinfo.cpp
gen/modules.cpp
gen/rttibuilder.cpp
gen/statements.cpp
gen/toconstelem.cpp
gen/toir.cpp
gen/trycatchfinally.cpp
gen/uda.cpp
ir/irclass.cpp
ir/irfunction.cpp
ir/irfunction.h

These changes are required by my current runtimeCompile work but I think they can be useful by itself. Main idea is to replace direct IrFunction->func usage with getLLFunc in all places where we want to do a call or take function address. So if we need to replace function call with call to another function we only need to hijack getLLFunc. Also a bunch of other small refactorings.

Refactor code to hide direct IrFunction->func usage and add convenient functions

---

tests/codegen/asm_output.d

armv6 instruction set used byRaspberry Pi 1 is a little different than armv7.

Fix codegen/asm_output test for RPi 1 (armv6)

---

circle.yml

LLVM 4.0 was branched off. So now it lives in its own APT repo.

[CircleCI] Add LLVM 4.0 apt repo.

---

runtime/CMakeLists.txt

Fixes the "Policy CMP0058" cmake warning.

[CMake] Change runtimelib dependency to configure_file input file.

---

gen/uda.cpp

With this, you can check enums with Type::tint32, instead of constructing the enum type. For example: `checkStructElems(sle, {Type::tint32})` for this UDA:
```
enum E {a,b,c};
struct exampleUDA
{
E e;
}
```
Needed for e.g. #1993

To check magic LDC UDAs parameter types, convert them to their basetype first.

---

CMakeLists.txt
cmake/Modules/CheckDSourceCompiles.cmake
cmake/Modules/HandleLTOPGOBuildOptions.cmake

[CMake] Add option to build LDC using LTO: `-DLDC_BUILD_WITH_LTO={OFF, ON, FULL, THIN}`.
When `LDC_BUILD_WITH_LTO` is set, the script adds -flto switch for the C++ compiler and D compiler, but only if they can create an executable with it.
Tested on OSX with ThinLTO (both with and without ThinLTO LLVM build). Some extra work is probably needed on Linux. On Windows, it won't do anything as the cmdline flag checks will fail.
On Linux, we should also enable the thinlto cache if possible.
Quick measurements indicate ~3% percent increased performance for `-O0` and `-O3` compilation (with ThinLTO LLVM too). Future step is adding PGO ;-)

[CMake] Add option to build LDC using LTO.

---

gen/llvmhelpers.h
gen/tocall.cpp

By also taking `DValue*` args, not just `Expression*`s.

Prepare DtoCallFunction() for runtime function calls

---

runtime/CMakeLists.txt

Fixes issue #1915. Using exclusively blacklists and no more whitelists (especially for subdirectories) should be way more robust wrt. future restructurings.
I also got rid of obsolete existing blacklist entries and removed a hopefully obsolete workaround wrt. disabling invariants for some parts of druntime.

CMake: Include missing modules in druntime/Phobos

---

gen/dvalue.cpp
gen/tollvm.cpp
gen/tollvm.h

LDC currently assumes that there is only one addrspace, zero.
dcompute requires the use of multiple AS to deal with global/shared
generic pointer. This PR addresses this issue.
There are only two root uses (bar asserts) that I have identified, (there may
be more, but libmir/dcompute build fine with #1786 HEAD~3) which is
generating an invalid  bitcast, because the types are not equal, but
for the purposes of copying do not require, and cannot be done with, a
bitcast.
Most suspicious type comparisons seem to resort to using DtoBitCast. 
Further testing will be required to see if any resulting from 
`gIR->ir->CreateBitCast(...)` are valid in dcompute 
(i.e. not classes,aa,typeinfo etc.)

dcompute: addrspace awareness

---

gen/dcomputetypes.cpp
gen/dcomputetypes.h
ir/irtypestruct.cpp

Transform `ldc.dcomptetypes.Pointer!(uint n,T)` into `{ T
addrspace(gIR->dcomputetarget->mapping[n])* }`

[dcompute] irtypestruct

---

driver/dcomputecodegenerator.cpp
gen/abi-nvptx.cpp
gen/abi-spirv.cpp
gen/asmstmt.cpp
gen/dcomputetargetCUDA.cpp
gen/dcomputetargetOCL.cpp
gen/dcomputetypes.cpp
gen/dibuilder.cpp
gen/irstate.h
gen/recursivevisitor.h
gen/semantic-dcompute.cpp
gen/statements.cpp

Update `ident->string` to `ident-toChars()`
Fix `__dcompute _reflect` code generation
Actually target CUDA
Disable debug info.
17421c4 is NFC, but I could not for the life of me get the insert on line 378 of asmsstmt.cpp to not crash with `set<string>`, however this works and should be of comparable performance.
Don't pass `Pointer!(n,T)` in memory.

[dcompute] compilation and behaviour fixes

---

gen/arrays.cpp
gen/runtime.cpp
tests/codegen/array_equals_memcmp.d

Optimize static array comparisons to a memcmp call for types for which this is valid.

---

CMakeLists.txt
ddmd/cond.d
driver/main.cpp

This PR adds the RISCV32 and RISCV64 version identifiers to ddmd/cond.d as reserved identifiers, and allows selecting these architectures as the target.
LLVM 4.0 has defined the architectures as `llvm::Triple::riscv32` and `llvm::Triple::riscv64`, but does not yet have support for producing binaries for RISC-V. riscv/riscv-llvm has support for producing binaries, but defines 32 bit as `llvm::Triple::riscv` instead. Therefore, a cmake option was added for building with riscv-llvm (`-DRISCV_LLVM_DEV=ON`). The plan is to remove this option once LLVM has full RISC-V support.
The next step is determining the features of the target CPU.

Initial support for targeting RISC-V architectures: defining version identifiers

---

ddmd/aggregate.d
ddmd/target.d
tests/codegen/simd_alignment.d

Fix dlang Issue 17237 - Wrong alignment for 256-bit vectors.
https://forum.dlang.org/post/dehxjddmuyzoyqkbdzwn@forum.dlang.org
https://issues.dlang.org/show_bug.cgi?id=17237

Cherrypick DMD PR #6582.

---

.travis.yml
driver/cl_options.cpp
driver/cl_options.h
driver/ldmd.cpp
driver/linker.cpp
driver/main.cpp
runtime/CMakeLists.txt
runtime/profile-rt/DefineBuildProfileRT.cmake

LDMD: Append default file extension if -of doesn't contain any

---

gen/llvmhelpers.cpp
tests/compilable/gh2033.d

Fixes issue #2033.
See testcase for more details.

Don't crash when trying to repaint static arrays

---

.gitmodules

Switching from `git://` URLs to `https://` should make it easier to avoid some CI-related issues encountered with the LDC snap package:
https://github.com/ldc-developers/ldc2.snap/issues/21#issuecomment-287575769
Note, assuming this is acceptable in the first place, I'd ideally like to make this change also to the 0.17.x series and (if possible) the 1.1.x series.  If that would be OK, which branch(es) should I submit against?

Use https URLs for git submodules

---

gen/abi.h
gen/functions.cpp

Apparently needed for x86_64 in general and NetBSD (possibly other BSD flavours too) based on `clang::ToolChain::IsUnwindTablesDefault()`.
Resolves issue #2048.

Re-add uwtable function attribute on Win64

---

gen/arrays.cpp
tests/codegen/array_equals_memcmp_2.d
tests/codegen/array_equals_memcmp_dyn.d
tests/codegen/array_equals_memcmp_neverinvoke.d

The optimization is to do a length-compare + memcmp-compare for dynamic array comparisons. A continuation of #1719 .
Slice nullptr checks are not needed, because comparing nullptr slices is UB in D. (_I can't find this in the specs. I deduced it from crashing executables when built with DMD, and from GDC's optimized code https://godbolt.org/g/qoNKSJ_)
This also fixes a pessimization where the `memcmp` call would become an `invoke` if the user provides a `memcmp` prototype in the code (the prototype would not carry the `nounwind` function attribute). This is not as rare as it may seem: it may quickly happen when the user imports one of the stdlib modules.
What's left is optimizing comparisons like `int[3] == int[2]`. See https://godbolt.org/g/ZBLkp3.

Implement optimization: compare slices using memcmp if valid

---

.travis.yml
circle.yml
runtime/CMakeLists.txt
runtime/profile-rt/DefineBuildProfileRT.cmake

Via `-DBUILD_SHARED_LIBS=BOTH`, addressing the build part of #1282.

CMake: Build both static and shared sets of stdlibs

---

ddmd/lexer.d
ddmd/root/ctfloat.d
ddmd/root/ctfloat.h
ddmd/root/port.d
gen/ctfloat.cpp

Rendering the parsing consistent across all platforms and resolving stuff like #2046. Visual Studio before 2015 couldn't handle hex literals and had some rounding quirks too.

Let LLVM parse floating-point literals instead of host C runtime

---

CMakeLists.txt
cmake/Modules/GetGitRevisionDescription.cmake

~~**Add IGNORE_GIT_REVISION cmake option to ignore git revision description**~~
~~This option allows users to override the default behaviour of comparing `LDC_VERSION` to the output of `git describe` and preferring the latter in the case of any difference.~~
~~This should obviously be used with caution but allows the user to avoid issues that can arise when e.g. building from a source tarball that has been extracted in a subdirectory of an independent git tree (!).  This is unfortunately a real possibility: apart from folks who use git to version their home directory [1], it's also proven an issue when trying to use source tarballs to build the LDC snap package [2].~~
~~[1]https://stackoverflow.com/questions/21266948/use-git-to-manage-home-directory/42946460~~ …

Add option to avoid recursing in get_git_head_revision cmake function

---

driver/ldmd.cpp
driver/linker.cpp
runtime/CMakeLists.txt

The default MS C runtime library doesn't depend on the `LINK_WITH_MSVCRT` CMake variable anymore.
The user can freely choose among the 4 variants libcmt[d] / msvcrt[d] via -mscrtlib or choose between static/dynamic release variant via -static.
~~As LINK_WITH_MSVCRT defaulted to OFF and -static defaults to false, produced Windows executables/DLLs will now be linked against the runtime DLLs by default (and thus shrink in size).~~ LDC keeps on defaulting to the static release C runtime, so `-static=false` or `-mscrtlib=msvcrt[d]` must be used explicitly in order to link against the runtime DLLs.

Add -mscrtlib cmdline option and support -static on Windows

---

tests/codegen/inlineIR_math.d

I don't know why the original test tests that fused mult-add is not emitted for these pieces, while at the same time specifying "fast" math on the operations.
This should fix the IR test for LLVM 5.0

Fix inlineIR_math.d test.

---

CMakeLists.txt
appveyor.yml

While LDC links binaries against the static Visual C++ runtime libs by default (analogous to the MS compiler), LDC/LDMD and misc. tools themselves were linked against the dynamic runtime, apparently because that's what the CMake C(++) flags default to.
This means that users may have had to install an appropriate Visual C++ runtime before being able to use our binaries, install the 2017 runtime as soon as our release packages are built with VS 2017 etc.
Compiling LLVM via CMake also makes it choose the dynamic runtime by default, so the CMake variable `LLVM_USE_CRT_{RELEASE,DEBUG,...}` (the suffix corresponding to the selected build configuration) must be set to either `MT` or `MTd` when building LLVM, otherwise linking errors result (import symbols...).
Executable size deltas for a …

MSVC hosts: Link LDC executables themselves against static CRT

---

ddmd/root/rmem.d

TypeInfo.init is now @disabled. Retain backwards-compatibility for ltsmaster.
Note: already used by the Travis LLVM 3.5 job.

Fix compilation error with DMD 2.074

---

runtime/CMakeLists.txt

Results in a `make -j3` sequence like this, `phobos2-ldc…-common` being the new dummy custom targets:
```
Line 120: Scanning dependencies of target phobos2-ldc-debug-common
Line 993: Scanning dependencies of target phobos2-ldc-common
Line 1314: [ 60%] Built target phobos2-ldc-debug-common
Line 1396: Scanning dependencies of target phobos2-ldc-debug-shared
Line 1408: Scanning dependencies of target phobos2-ldc-debug
Line 1465: [ 66%] Linking C shared library ../lib/libphobos2-ldc-debug-shared.so
Line 1476: [ 66%] Linking C static library ../lib/libphobos2-ldc-debug.a
Line 1477: [ 74%] Built target phobos2-ldc-debug
Line 1481: [ 82%] Built target phobos2-ldc-debug-shared
Line 1546: [ 84%] Built target phobos2-ldc-common
Line 1547: Scanning dependencies of target phobos2-ldc-shared
Line …
```

CMake: Fix racey Phobos compilation when building static+shared libs

---

.travis.yml

Ever since building both static and shared runtime libs (and static/shared Phobos sharing their object files), the CI systems spuriously failed when generating the libraries, e.g., `std/xml.o: file not recognized: File truncated`.
~~Try writing to a temporary object file and rename it as soon as it is fully written.~~ Switching from make to ninja apparently fixes this problem and also reduces the Travis log verbosity (as Travis supports line-updates, simulating an interactive shell experience, kinda neat).

Travis: Replace make by ninja

---

gen/toconstelem.cpp
tests/codegen/vector_init.d

Previously, we would always try to splat the given expression across the
whole vector. This hasn't been noticed earlier as DMD mostly generates
ArrayInitializers when initializing vectors to array literals (but
notably not when explicitly assigning VectorType.init).
GitHub: Fixes #2101.

toconstelem: Implement array literal VectorExps

---

ddmd/idgen.d
gen/uda.cpp
gen/uda.h

add LDC specific magic UDAs and magic dcompute suff to the pooled ID table.
Make uda.cpp use them.

Pooled IDs

---

ldc2.conf.in
ldc2_install.conf.in
ldc2_phobos.conf.in

The default switches are injected right after argv[0], not appended to the command line.

Fix misleading comment in config file

---

driver/cl_options.cpp
driver/cl_options.h
driver/linker.cpp
tests/linking/linker_switches.d

Implemented as discussed in comments to #2093.
There's `assert(optnum < this->size() && "Invalid option index")` in `cl::list::getPosition`, and `size()` doesn't seem to be present for `opts::linkerSwitches`, so this assert shouldn't compile.
In what circumstances are asserts enabled when building LDC? I've tried both Release and Debug builds and it compiled.

Add switch '-Xcc <ccflag>'. Fix #2093.

---

gen/functions.cpp
ir/irfuncty.h
tests/codegen/varargs.d

Only non-typesafe variadics need to take LLVM varargs

---

gen/attributes.cpp

In preparation for the testing for dcompute I was building against very recent trunk and hit the following.
```
/Users/nicholaswilson/d/ldc/gen/attributes.cpp:94:31: error: no member named 'getNumSlots' in 'llvm::AttributeList'
for (unsigned i = 0; i < os.getNumSlots(); ++i) {
~~ ^
/Users/nicholaswilson/d/ldc/gen/attributes.cpp:95:25: error: no member named 'getSlotIndex' in 'llvm::AttributeList'
unsigned index = os.getSlotIndex(i);
~~ ^
/Users/nicholaswilson/d/ldc/gen/attributes.cpp:96:55: error: no member named 'getSlotAttributes' in 'llvm::AttributeList'; did you mean
'getAttributes'?
set = set.addAttributes(gIR->context(), index, os.getSlotAttributes(i));
^~~~~~~~~~~~~~~~~
getAttributes
/Users/nicholaswilson/d/llvm/include/llvm/IR/Attributes.h:455:16: note: 'getAttributes' declared …
```

Fix compilation with LLVM trunk

---

gen/dibuilder.cpp
gen/dibuilder.h
tests/debuginfo/classtypes_gdb.d
tests/lit.site.cfg.in

Fix the `DIType` produced for static arrays of classes and pointer to classes, and fix the size of class types in `DIBuilder::CreateCompositeType`.
Ex.: `Array!FuncDeclaration` was causing an infinite recursion crash in GDB, because for its « `FuncDeclaration[SMALLARRAYCAP] smallarray` » field `DIBuilder::CreateSArrayType()` had DIBuilder return a value type instead of a reference type for FuncDeclaration. 
---
With these two simple fixes debugging LDC 1.x+Calypso built by LDC went from a painful experience into a smooth one, I've had no other crash/garbage value so far.
(BTW sorry to have put Calypso's development in slumber, it's back at full blast now, and the transition to DDMD isn't going too bad)

Debug info fixes for class types

---

driver/main.cpp
tests/driver/gh2073.d

When creating LLVM's TargetMachine, `llvm::SubtargetFeatures::getFeatureBits()` is called 3 times, and the help is printed 3 times (or even 6 times when specifying both `-mcpu=help -mattr=help`).
So use some new code making sure the help is printed only once and return 0 early without trying to compile anything (and so erroring if no source files have been specified etc.).
Fixes issue #2073.

Print -mcpu=help / -mattr=help output only once

---

gen/inlineir.cpp
gen/mangling.cpp
gen/to_string.h

This PR should enable native compilation on Android.
See https://gist.github.com/joakim-noah/4153662c68fb2ba9592c9cb0d7892624
@joakim-noah

Remove dependence on std::to_string, because it is not available on all systems.

---

gen/optimizer.cpp

This pass was apparently implicit in LLVM < 5.0. Fixes test PGO/indirect_calls.d with LLVM 5.0.

Add indirect call promotion pass when PGO info is available.

---

driver/main.cpp

According gcc/clang warning produced by `merge-2.074`.

Fix potential segfault when formatting error msg

---

CMakeLists.txt
driver/cache.cpp
driver/cl_options_sanitizers.cpp
driver/cl_options_sanitizers.h
driver/linker-gcc.cpp
driver/main.cpp
gen/functions.cpp
gen/optimizer.cpp
gen/optimizer.h
tests/sanitizers/fsanitize_address.d
tests/sanitizers/fsanitize_coverage.d
tests/sanitizers/fsanitize_error_diagnostic.d
tests/sanitizers/fsanitize_fuzzer.d
tests/sanitizers/fsanitize_thread.d

This reworks the sanitizer interface to be identical with Clang's.
`-fsanitize-coverage` is only available from LLVM 4.0.
What's left to do is pass the correct runtime libraries to the linker: I'll update the cmake script to check whether the runtime sanitizer libs of compiler-rt are available somewhere. If so, copy them to LDC. (this should also remove the need to have a copy of profile-rt inside our repo)

Replace `-sanitize` with `-fsanitize` and add `-fsanitize-coverage`.

---

gen/coverage.cpp
tests/codegen/gh2163.d

Coverage analysis isn't enabled for the special `-main` module in codegenModule(), so Module::d_cover_data is null in that case.
Fixes issue #2163.

Fix ICE when using `-main -cov`

---

gen/modules.cpp

dmd moved from [the linked list at `_Dmodule_ref` to a bracketed section a couple years ago](https://github.com/dlang/druntime/commit/e91f59d2175c1056af5d2de59f4fd5dee7a1779d), so I've been reverting that druntime commit for ldc/Android till now.  Turns out I can use this `sectionELF` code just fine, as long as I take out the calls to `_d_dso_registry` and modify druntime to use the slightly different ldc symbols `__start___minfo` and `__stop___minfo`, druntime PR forthcoming.  Confirmed by cross-compiling the stdlib tests from linux/x64 to Android/ARM with ldc master, and running the stdlib and dmd testsuite natively with master and merge-2.074.
I didn't look very closely at `sectionELF` however, just hacked this in, so if David thinks anything else might cause issues, let me know.

Switch Android onto the sectionELF style of module registry, but leave out the unused register_dso and friends

---

gen/optimizer.cpp
tests/codegen/gh2161.d

By letting LLVM set up the inlining params (taking into account `-inline-threshold`) instead of hardcoding them.
The old hardcoded thresholds were identical to the LLVM 3.9 defaults, but they changed in LLVM 4.0:
* optLevel > 2: 275 => 250
* -Os: 75 => 50
* -Oz: 25 => 5

Make inlining threshold customizable via (existing) -inline-threshold

---

.travis.yml
tests/d2/CMakeLists.txt

Increase test coverage by including 32-bit shared libs, which for instance led to ldc-developers/druntime@a3af613.

Set up SemaphoreCI, tweak Travis config, speed up dmd-testsuite

---

gen/nested.cpp

Helps with tracking down the why of GC allocations.

Additional -vv logging in DtoCreateNestedContext.

---

driver/exe_path.cpp

Don't use angled brackets for LLVM includes [NFC]

---

driver/linker-gcc.cpp

This PR is only meant to change Darwin link line with -fsanitize=address. With this PR, I can use addresssanitizer successfully (and easily) on my Mac. 
The PR finds a `libldc_rt.asan_osx_dynamic.dylib` or `libclang_rt.asan_osx_dynamic.dylib` in LDC's lib dir, and falls back to the old behavior (passing `-fsanitize=address` to the linker driver) if nothing is found. So now the user can copy his self-built library to LDC's lib dir and be happy :-)
(the cmake script could copy+rename the library to the lib dir when the library is found in the LLVM binaries)

AddressSanitizer, Darwin: add support for linking with correct library when found in LDC's lib dir.

---

driver/main.cpp
gen/tollvm.cpp
tests/codegen/ptr_16_bit.d

`global.params` doesn't have a flag for the condition of being a 16-bit target. We have two options: 1) add that flag, or 2) compute 16-bitness from the target triple each time `DtoSize_t` is called. Since adding fields to `struct Params` might be disruptive, I opted for the latter. Please say if you prefer the former.
I avoid calling `isArch16Bit` unless the target is not 64-bit, which should be the most common target, and therefore avoid unnecessary work. Having a flag for 16-bitness would be slightly cheapter, but I'm guessing the speed penalty is not noticeable.

Add support for MSP430 / 16-bit targets

---

gen/toir.cpp
tests/codegen/gh1433.d

Slice expressions: load the base's pointer after the bounds expressions have been evaluated, since they may affect the pointer if the base is an lvalue, see issue #1433.
Not sure if this is correct/desirable, see http://forum.dlang.org/thread/blkpasccoceipqvbkyla@forum.dlang.org.

Fix issue #1433

---

.circleci/config.yml
.travis.yml

The workers may have less than 4 GB of memory and some jobs seem to get killed due to this, particularly when building the stdlib test runners.
So try precompiling the shared unittest objects manually with `-j3` too.
If compiled as part of the testrunner tests, ninja apparently defaults to a high number of parallel jobs based on the CPU and not on the available CPU cores for the Docker container.

Travis Linux: Try to work around memory limitations

---

ddmd/expression.d
ddmd/expression.h
ddmd/traits.d

DMD PR https://github.com/dlang/dmd/pull/6949
fix Issue 17545 - [REG2.072] __traits(getAttributes, name) evaluates name to value prematurely
(needed for Weka, so was easy to cherry-pick for us too)

Cherry-pick DMD commit 2e6c7ac3af5ec52aff63a779e781cab1a802dfa5

---

gen/dibuilder.cpp

Instead of `"LDC (http://wiki.dlang.org/LDC)"`, this PR sets the producer string to the full version of LDC, for example:
`"LDC 1.4.0git-c041205-dirty (LLVM 4.0.1svn-r307596)"`
or 
`"LDC 1.4.0 (LLVM 4.0.0)"`
Shall I also add the DMDfe version?

Make the producer name in debuginfo more precise.

---

driver/exe_path.cpp
driver/exe_path.h
driver/linker-gcc.cpp

Only tested on mac with -mtriple=x86_64-pc-linux, which does the correct thing.
As least on Ubuntu, the libs are called: `libclang_rt.asan-x86_64.a` and `libclang_rt.asan-x86_64.so`.
The shared lib support is halfbaked. I put in some code to make it easy for someone to make that work in the future.

Add search logic for AddressSanitizer library on Linuxes.

---

.circleci/config.yml
.travis.yml
appveyor.yml
runtime/CMakeLists.txt
runtime/profile-rt/DefineBuildProfileRT.cmake

Curious about the timings when building all D modules at once in a single command-line (like DMD does), I hacked the CMake script and performed a few tests (Win64, LDC/LLVM with assertions, quad-core CPU without SMT):
```
All at once, phobos2-ldc:        50.4 secs with -j1, ~1 GB RAM
phobos2-ldc-debug:  14.6 secs with -j1
Separately,  phobos2-ldc:       109.5 secs with -j1, 35.1 secs with -j4
phobos2-ldc-debug:  44.8 secs with -j1, 13.1 secs with -j4
```
So saving all the duplicate parsing work does pay off substantially, at the cost of much coarser parallelizability and having to recompile all modules when only a single one changes. Setting the CMake variable `COMPILE_ALL_D_FILES_AT_ONCE=OFF` restores the previous behavior of compiling each module separately.
Building druntime …

CMake: Allow compiling all D modules of a runtime lib at once

---

tests/linking/ir2obj_cache_pruning2.d

I think there is a spurious case where things happen right before / after second elapses. This should fix that.
@kinke Hope this fixes the spurious failures like https://travis-ci.org/ldc-developers/ldc/jobs/258653490#L3431

Make cache pruning test more robust by sleeping longer between invokes.

---

gen/asm-x86.h
gen/asmstmt.cpp
gen/dcompute/targetCUDA.cpp
gen/tocall.cpp

This fixes the warning "default label in switch which covers all enumeration values". We will already get a warning when _not_ all enumeration values are covered.
I think with this PR, all warnings are resolved and we can use `-Werror` on our CI systems.
Let's not debate about this change too long. I looked into disabling the warning for only this piece of code, but it is cumbersome. So let's either apply this change, or remove `-Wcovered-switch-default` from our build flags. Thanks.

Fix a few compiler warnings

---

ddmd/root/ctfloat.d
ddmd/root/ctfloat.h
gen/ctfloat.cpp
gen/target.cpp
gen/tollvm.cpp
tests/codegen/vector_init.d

**Update**:
By letting LLVM truncate compile-time `real_t` values to float/double IR constants. We previously relied on the host, which turns signalling real_t NaNs to quiet float/double NaNs.
Signalling NaNs are characterized by their most-significant mantissa bit being 0 (and at least for D the 2nd-most-significant mantissa bit being set to distinguish them from infinity). The host truncation led to the MSB
getting set while keeping the rest of the mantissa (i.e., both MSBs set).
Here's the resulting bitpattern table in hex:
|           | float  |   double  |          x87 real |
| ------ | ----- | ---------- | --------------- |
| init old |  7f**e**00000   |7ff**c**000000000000  | 7fff**a**000000000000000 |
| init new |  7f**a**00000 |  7ff**4**000000000000 |  7fff**a**000000000000000 | …

Switch to special quiet NaN as init value for all FP types

---

driver/cl_options_sanitizers.cpp
driver/cl_options_sanitizers.h
gen/functions.cpp
tests/sanitizers/fsanitize_blacklist.d
tests/sanitizers/inputs/fsanitize_blacklist.txt
tests/sanitizers/inputs/fsanitize_blacklist2.txt

Having fun with ASan :)
Blacklisting is necessary for some druntime functions, and LLVM/Clang already provides just the right functionality.
Will add the actual needed blacklist in a later PR.

Add the -fsanitize-blacklist option for the sanitizers.

---

ddmd/mtype.d
ddmd/mtype.h
gen/llvmhelpers.cpp
gen/llvmhelpers.h
ir/irtypeaggr.cpp
ir/irtypestruct.cpp
tests/codegen/gh2235.d

Unnaturally aligned aggregates were potentially not marked as packed, leading to LLVM inserting additional padding and screwing up the memory layout.

Fix issue #2235 - IR struct packedness

---

appveyor.yml

I could verify the issue when building with LDC 1.1.0, but not with dmd or LDC 1.3.0, So retrying with the latter.

fix issue 1876 - use LDC 1.3.0 instead of 1.0.0

---

gen/functions.cpp

... by proper function attributes. Clang sets these 2 attributes if frame pointer elimination is to be fully disabled (see [here](https://github.com/llvm-mirror/clang/blob/b3d4dafef1d8deb0e748cc9625ff86c38735ca0d/lib/CodeGen/CGCall.cpp#L1706-L1707)).
[I only came across this by accident.]

Replace hacky disabling of fp-elimination for functions with inline asm

---

driver/linker-gcc.cpp
driver/toobj.cpp
driver/tool.cpp
driver/tool.h
tests/compilable/no-integrated-as.d

And merge the two out-of-sync copies for adding gcc target flags. The flag was omitted for gcc as linker already, but not for gcc as external assembler.

Don't use -m32/-m64 for external ARM assembler

---

CMakeLists.txt

Tested with Visual Studio 2017; works fine, and the `LDCShared` project/lib can still be built, the D files are simply ignored when building it.

CMake: Include D source files in Visual Studio project

---

tests/codegen/attr_weak.d
tests/codegen/discard_value_names_ir2obj_cache.d
tests/codegen/inferred_outputname.d
tests/linking/ir2obj_cache_pruning.d
tests/linking/ir2obj_cache_pruning2.d
tests/linking/ir2obj_caching.d
tests/linking/ir2obj_caching_flags1.d
tests/linking/ir2obj_caching_retrieval.d
tests/tools/ldc_prune_cache_1.d

The %T substitution will be removed from Lit.
Resolves issue #2274

Lit: stop using `%T` and use `%t-dir` instead.

---

CMakeLists.txt
appveyor.yml
cmake/Modules/FindLLVM.cmake
driver/tool.cpp
runtime/CMakeLists.txt

Some LLVM libs were missing from the linker flags for current LLVM 5.0. It was only during troubleshooting that I noticed the MSVC special case in `FindLLVM.cmake`. Getting rid of it entirely made the issues disappear. I checked `llvm-config.exe`, and it's returning appropriate switches for the MS toolchain, no need for special processing.
This apparently also leads to `LLVM_CXXFLAGS` being used for the first time when building with MSVC. These include `/W4`, a level further up from CMake's default `/W3`, so I disabled a few more frequent warnings.
I also had to link in a lib from Microsoft's Debug Info Access SDK manually. As the VS command prompt unfortunately doesn't even include the DIA SDK dir in the `LIBPATH` environment variable, I even had to specify a full path, relying on the …

[MSVC] CMake: Prepare for LLVM 5.0

---

.travis.yml

Installing an official pre-built ninja binary (73KB zipped) instead.

Travis OSX: Save almost 2 minutes (by skipping brew)

---

tests/sanitizers/fuzz_asan.d

This test would sometimes fail, where the fuzzer is not able to find the bug quickly enough.

fuzz_asan.d test: make it easier for fuzzer to find the bug.

---

tests/sanitizers/fuzz_asan.d
tests/sanitizers/fuzz_basic.d
tests/sanitizers/link_fuzzer.d

Don't test fuzzer before LLVM 5.0, because it has known problems.

---

driver/configfile.cpp
driver/configfile.d
driver/configfile.h
driver/main.cpp
ldc2.conf.in
ldc2_install.conf.in
ldc2_phobos.conf.in
tests/driver/inputs/post_switches.conf
tests/driver/post_switches.d
tests/lit.site.cfg.in

For switches to be appended after the user switches (or right before the first `-run` switch).
The sections inherit it (as well as `switches`) from the `default` section if it isn't overridden explicitly.
Fixes issue #2186.

Add `post-switches` to config file sections

---

CMakeLists.txt

So people like me don't waste days staring at linker errors.

[MSVC] Error out if LLVM is built with MD[d]

---

CMakeLists.txt
appveyor.yml

Thanks to @rainers' X-ray capabilities. :)
We still need the [upstream druntime fix](https://github.com/dlang/druntime/pull/1910) to make LDC produce working binaries out of the box.

Work around host compiler issues with VS 2017 Update 15.3+

---

runtime/ldc-build-runtime.d.in

Based on https://github.com/ldc-developers/ldc/issues/2303#issuecomment-327170328.

ldc-build-runtime: Get rid of tar, let Phobos extract ZIP source archive

---

.travis.yml

Travis: Add LLVM 5.0

---

runtime/CMakeLists.txt

CMake: Use LDC as (cross-)archiver for static runtime libs

---

runtime/CMakeLists.txt
runtime/PresetRuntimeConfiguration.cmake
runtime/ldc-build-runtime.d.in

The idea here is to be able to simply specify a dash-separated OS and CPU architecture and our CMake config will try to fill in the rest for you.  Probably best to stick this in another CMake file, where we can have common flags for all the cross-compilation platforms the ldc devs have tried out, ie Linux/PPC, Windows/AArch64, or whatever else.  You can always override `RT_CFLAGS` and `LD_FLAGS` by setting them manually, this logic will simply supply defaults for when the user doesn't.
Android is a little weird because CMake doesn't automatically detect if you're natively compiling on Android, and I can't set `CMAKE_SYSTEM_NAME=Android` because it will try to invoke the cross-compilation NDK toolchain.  Basically, Android native compilation is unsupported by CMake, to the point where it …

Add LDC_TARGET_PRESET CMake variable for runtime, to make cross-compilation easier

---

.circleci/config.yml
.travis.yml
CMakeLists.txt
driver/cache.cpp
driver/cl_options-llvm.cpp
driver/cl_options-llvm.h
driver/cl_options.cpp
driver/cl_options.h
driver/linker-gcc.cpp
driver/main.cpp
driver/targetmachine.cpp
driver/targetmachine.h
gen/dcompute/targetCUDA.cpp
gen/functions.cpp

I.e., [llvm/CodeGen/CommandFlags.h](https://github.com/llvm-mirror/llvm/blob/release_40/include/llvm/CodeGen/CommandFlags.h) which in turn includes [llvm/MC/MCTargetOptionsCommandFlags.h](https://github.com/llvm-mirror/llvm/blob/release_40/include/llvm/MC/MCTargetOptionsCommandFlags.h).
This gets rid of a few duplicates on our side and includes about 35 (depending on LLVM version) new command-line options. LLVM provides a helper function to set up the TargetOptions according to (most of) these options.
Newer LLVM versions may add new options and we'll automatically inherit them, including setting up the TargetOptions accordingly.
I did my best (TM) to remove a few unused/undesirable options and hide all remaining new ones except for `-fp-contract`. The lists will need to be tweaked from …

Use LLVM headers for shared codegen command-line options

---

driver/targetmachine.cpp

Apply #1664 to LTS master too. See https://github.com/ldc-developers/ldc/issues/2341
Modern Linux distributions have their toolchain generate PIC code for
additional security features (like ASLR).
Since there is no (sane) way to detect whether the toolchain defaults to
PIC code, we simply default to PIC code on all Linux
distributions to avoid linking issues on these OSes.
The relocation model can be switched back to non-PIC code manually at
any time.

Default to PIC code on Linux (see #1664)

---

driver/archiver.cpp

It was based on early LLVM 5.0, and there's been one notable change in the meantime, see https://reviews.llvm.org/D33575. I think @joakim-noah mentioned some issues wrt. object names in static libs. **Edit**: And @JohanEngelen something wrt. object names and LTO?

Adapt embedded llvm-ar to LLVM 5.0 final

---

ddmd/mtype.d
ir/irtypeaggr.cpp
tests/codegen/gh2346.d

I probably introduced this regression lately. Back then, I didn't account for container aggregates, which require that the LL struct is packed if the overall D aggregate alignment is lower than a field's natural alignment.

Fix packed struct layout regression (issue #2346)

---

tests/linking/rt_options.d

~~LDC's~~ `pragma(mangle, …)` allows specifying a 'base' mangle for the symbol's linkage. So by using `extern(C) pragma(mangle, …)`, a base C mangle can be specified, without having to take care of a platform-specific prefix.

druntime: Fix mangling issue #1970 for rt.config on Win32 and OSX

---

CMakeLists.txt

Fixes #2337 by not preserving the source file permissions. According to the CMake docs, that's what happens when INSTALLing a file as well.

CMake: Prefer file(COPY) over configure_file(... COPYONLY)

---

runtime/CMakeLists.txt

Building on mingw-w64 fails without it(shouldn't break other builds).

cmake: use -of= instead of -of

---

gen/asm-x86.h

Needed for Win64 with 80-bit reals (i.e., MinGW) here (Win64-specific):
https://github.com/ldc-developers/phobos/blob/882449f7916031667e09fe7a203d305a60898641/std/math.d#L3691

DMD-style inline asm: Add `s` suffix for fild etc. with 16-bit memory operand

---

driver/archiver.cpp

OSX: Use external archiver by default, require `-ar=` for internal one

---

gen/aa.cpp
gen/classes.cpp
gen/declarations.cpp
gen/rttibuilder.cpp
gen/toconstelem.cpp
gen/toir.cpp
gen/typinf.cpp
tests/codegen/static_typeid_gh1540.d

[Derived from [this 2.076 commit](https://github.com/ldc-developers/ldc/pull/2365/commits/b3cfd7afc4c079f95593b6263316f0b074cf2734).]
Improve robustness for TypeInfos of speculative types by only eliding their TypeInfo definition, not the declaration of the LL global altogether.
`DtoTypeInfoOf()` expects the LL global to be created and otherwise fails with an assertion or segfault (e.g., issue #2357). So now only linker errors should result in case the TypeInfo definition is missing.
Also normalize the calls to `DtoTypeInfoOf()` and revise the following pointer bitcasts, as the LL type of forward-declared TypeInfo globals may be opaque.

Backport fix for issue #2357

---

ddmd/target.h

Fixes compile warnings with XCode 9.
`gen/target.cpp:59:18: warning: instantiation of variable 'Target::FPTypeProperties<long double>::nan' required here, but no definition is available [-Wundefined-var-template]`
See https://stackoverflow.com/questions/43439862/c-template-instantiation-of-variable-required-here-but-no-definition-is-ava
No need to upstream because the warning is caused by the LDC-specific modification in the same file.

Provide explicit template instantiation definitions for FPTypeProperties<T> static members

---

gen/moduleinfo.cpp
gen/modules.cpp
ir/irmodule.h
tests/codegen/coverage_cycle_gh2177.d
tests/codegen/inputs/coverage_cycle_input.d

Move the call to the D-style code-coverage constructor (registration of code coverage for the current module) to the "ictor" constructors that are not included in cycle detection.
Resolves issue #2177.
Adding the coverage ctor call to `llvm.global_ctors` does not work, because the call must happen after D runtime's `rt.cover.gdata` has been properly initialized, i.e. after other D constructors in the ModuleInfo ctor list.
The code is intentionally kept somewhat similar to DMD's (variable naming).

Fix bad import cycle error with `-cov`

---

gen/modules.cpp

Instead of the legacy linked list.

MSVC: Emit ModuleInfo references into .minfo section

---

ddmd/target.d
ddmd/target.h
gen/target.cpp

Which is a serious problem if the host real_t is a double and the target `real` features a higher precision (cross-compilation). `Target::RealProperties` are set up for the target's `real`, so max/min_normal/epsilon may over/underflow, and so would `DoubleProperties` if aliased.

Don't let Target::RealProperties alias Target::DoubleProperties

---

driver/main.cpp

Cherry-pick from upstream DMD, https://github.com/dlang/dmd/pull/7132
A low-risk change such that Mir can already start using it. (@9il)

Add "D_betterC" version.

---

driver/linker-gcc.cpp
driver/linker-msvc.cpp
driver/tool.cpp
driver/tool.h

Needed for LTO via external `lld-link.exe` (v5.0+).

Add -linker command-line option

---

.travis.yml
ddmd/builtin.d
ddmd/root/ctfloat.d
ddmd/root/ctfloat.h
tests/compilable/ctfe_math.d

E.g., all LLVM intrinsics currently used in `{core,std}.math`.

Make many std.math functions CTFE-able

---

runtime/ldc-build-runtime.d.in

PR makes two changes to `ldc-build-runtime`:
- Adds a `--resetOnly` option (Issue #2384). This does the `--reset` operation, but doesn't do the build.
- Catches exceptions thrown by `getopt`. This provides nicer error message formatting to the user.
On the latter item: Typical example is passing a command line argument that doesn't exist, like `ldc-build-runtime --version`. The argument doesn't exist, triggering an exception. Because the exception isn't caught, the user see a stack trace. This change displays the error text only, not the stack trace.

ldc-build-runtime: Add --resetOnly command. Catch getopt exceptions.

---

gen/moduleinfo.cpp

Reverts this functional change introduced by ldc-developers/ldc@3f38f971. I overlooked this because
`setLinkage({<linkage>, false}, <symbol>)` does NOT clear the COMDAT if previously set.

Emit ModuleInfos as COMDATs again

---

ir/irtypeclass.cpp
tests/compilable/gh2422.d
tests/compilable/inputs/gh2422a.d

global.errors may be nonzero due to speculative error at this point!
ie. when trying to speculatively make a constant class expression

fix issue 2422 - remove overzealous error check

---

runtime/jit-rt/DefineBuildJitRT.cmake
runtime/jit-rt/cpp-so/compile.cpp
runtime/jit-rt/cpp-so/disassembler.cpp
runtime/jit-rt/cpp-so/disassembler.h
tests/dynamiccompile/asm_output.d
tests/dynamiccompile/dump_handler.d

Debug asm output was disabled previously because`addPassesToEmitFile` asm output was different from actual jit asm. This is attempt to disassemble jit binary instead.

Disassemble resulting jit module and output asm to debug handler

---

gen/declarations.cpp
gen/llvmhelpers.cpp
tests/codegen/export.d

Not just functions. Fixes issue #2437.

Windows: Map `export` to DLL storage classes for data too

---

ddmd/aggregate.h
ddmd/aliasthis.h
ddmd/attrib.h
ddmd/declaration.h
ddmd/dsymbol.h
ddmd/enum.h
ddmd/import.h
ddmd/module.h
ddmd/nspace.h
ddmd/staticassert.h
ddmd/template.h
ddmd/version.h

A number of overrides were actually not overriding (instead hiding the virtual functions).
Fixed upstream in https://github.com/dlang/dmd/pull/7402 and https://github.com/dlang/dmd/pull/7401
Applying early because it can cause hard to find bugs and leads (thankfully) to a compiler warning flood.

Fix C++ header virtual function overrides

---

.travis.yml

The cached directories are apparently created even if the cache download doesn't succeed...

Travis: Account for caching quirk

---

driver/linker-gcc.cpp
runtime/profile-rt/d/ldc/profile.d
tests/PGO/profile_rt_calls.d

I think the extra functionality added into profile-rt (compared with LLVM's profile-rt) is of very little value, and perhaps not worth making our own version of compiler-rt's profile-rt. We could kill all that, and just use LLVM's profile-rt, but for now, I just want to remove the Phobos dependency in non-templated code.
Wit this PR only the templated code in ldc.profile depends on Phobos, so it's possible to link with profile-rt without requiring Phobos.

Remove ldc.profile.getData(string) to remove profile-rt Phobos dependency

---

ddmd/id.d
ddmd/id.h
gen/uda.cpp
tests/codegen/attr_assumeused.d

The attribute adds the symbol to `llvm.used`.
My use case: LTO is nicely aggressive in removing symbols, but some symbols at Weka are not supposed to be removed.

Add the ldc.attributes.assumeUsed attribute corresponding to "attribute((used))” in GNU C

---

driver/cl_options_sanitizers.cpp
tests/linking/ir2obj_caching_flags2.d

The important change is writing the full SanitizerCoverageOptions struct to the hash outputstream, such that options added (or removed) in the future are automatically included in the hash.

Add coverage sanitizer options and include them all in the cache hash.

---

driver/cl_options.cpp
driver/cl_options.h
driver/linker-msvc.cpp
driver/linker.cpp
driver/main.cpp
driver/tool.cpp

-help:
```
Linking options:
-L=<linkerflag>                           - Pass <linkerflag> to the linker
-Xcc=<ccflag>                             - Pass <ccflag> to GCC/Clang for linking
-defaultlib=<lib1,lib2,...>               - Default libraries to link with (overrides previous)
-disable-linker-strip-dead                - Do not try to remove unused symbols during linking
-link-defaultlib-debug                    - Link with debug versions of default libraries
-link-defaultlib-shared                   - Link with shared versions of default libraries
-linker=<lld-link|lld|gold|bfd|...>       - Linker to use
-mscrtlib=<libcmt[d]|msvcrt[d]>           - MS C runtime library to link with
-static                                   - Create a statically linked binary, including all system …
```

Generalize defaultlibs cmdline help category to linking options

---

gen/inlineir.cpp
gen/inlineir.h
gen/pragma.cpp
tests/codegen/inline_ir.d

Add extended version of  `LDC_inline_ir` pragma which allow to add arbitrary code before and after function.

Extend LDC_inline_ir pragma

---

ddmd/globals.d
ddmd/globals.h
driver/cl_options_instrumentation.cpp
driver/cl_options_instrumentation.h
driver/codegenerator.cpp
driver/linker-gcc.cpp
driver/linker-msvc.cpp
driver/main.cpp
gen/funcgenstate.h
gen/functions.cpp
gen/modules.cpp
gen/optimizer.cpp
gen/pgo_ASTbased.cpp
gen/pgo_ASTbased.h
tests/PGO/irbased_indirect_calls.d

First, some refactoring such that the code doesn't assume just one kind of PGO.

Add IR-based PGO

---

gen/dcompute/target.cpp
gen/dcompute/target.h
gen/dcompute/targetCUDA.cpp
gen/dcompute/targetOCL.cpp

Fixes CUDA dcompute compilation with LLVM 6.0.
Why do we have to set the datalayout to something explicit? This breaks every now and then when LLVM changes things, making our datalayout invalid. If there is no good reason for, then we should use LLVM's datalayout. It currently is a maintenance problem.
@thewilsonator The dcompute compilation is still a major hack. Let's work towards making it less so.
For example, LDC's code is referencing gDataLayout throughout the code base, which is invalid when generating dcompute code. We should remove the `gDataLayout` global var, and just use `gTargetMachine->getDataLayout` (or `gIR->module.getDataLayout()` when possible).

DCompute CUDA: Use the datalayout from the targetmachine created by LLVM

---

runtime/CMakeLists.txt
runtime/profile-rt/DefineBuildProfileRT.cmake
runtime/profile-rt/d/ldc/profile.di

This removes all D code from the profile-rt runtime library. The ldc.profile module is no longer compiled and linked into profile-rt. We can now directly use compiler-rt's profile library. But that will happen in another patch.

PGO: Make profile-rt a template-only module.

---

driver/toobj.cpp

Work towards removing the use of global vars, in this case gDataLayout. We have multiple different layouts when compiling both to object code and to dcompute target like CUDA.

Remove one use of gDataLayout.

---

driver/cl_options_instrumentation.cpp
driver/cl_options_instrumentation.h
driver/main.cpp

This removes the dependency on the global parameter / makes the dependency much more explicit.

Explicitly pass triple to option initialization routine. [NFC]

---

CMakeLists.txt
gen/dynamiccompile.cpp
runtime/jit-rt/cpp-so/compile.cpp
runtime/jit-rt/cpp-so/context.h
runtime/jit-rt/cpp/compile.cpp

It is expected dynamic compile api will be stable enough to be able to update jit shared library to newer version without recompiling application (e.g. to take advantage of new instructions or new compiler optimizations). But if we really need to break backward compatibility we should increase api version, so application can detect this.
There are two checks:
* Append api version to jit dll entrypoint name to cause undefined reference error if api version changed.
* Add api version to module jit description struct and check it before compilation
It is possible to support multiple api version by manually providing functions with older api versions and doing conversion for descriptions structs, but for now just abort.

Jit api versioning

---

ddmd/declaration.d
ddmd/declaration.h
ddmd/dsymbolsem.d
gen/classes.cpp
gen/classes.h
gen/toir.cpp
gen/tollvm.cpp
tests/codegen/gh2515.d

The dtors can be checked at compile-time; insert a runtime check for the monitor before finalizing the stack-allocated class object via druntime call.
See issue #2515.

Don't finalize scope objects without dtors and monitor

---

tests/d2/CMakeLists.txt

For less verbose output (hide DFLAGS again) and better upstreamability of the d_do_test patch filtering out redundant permute args.

dmd-testsuite: Pass LDC config flags as REQUIRED_ARGS (not part of DFLAGS)

---

tests/sanitizers/fuzz_asan.d

The test now passes for any input that starts with FUZ and is longer than 3 chars.
This hopefully fixes some spurious test failures, probably caused by the random input growing beyond length=4 too quickly and not finding the "FUZ*" crasher after that (within reasonable time).

Make the fuzz_asan.d test more robust.

---

tests/sanitizers/fuzz_basic.d

When the test fails, it shows the libfuzzer output, so we can see crash details.

Temporarily make fuzz_basic test more verbose to track down spurious failure

---

gen/passes/SimplifyDRuntimeCalls.cpp
gen/tollvm.cpp

http://lists.llvm.org/pipermail/llvm-dev/2018-January/120542.html

[trivial] LLVM7.0: update code to use new API for creating MemCpy intrinsic call.

---

README.md

Removed the d1/ltsmaster branch links, as they are not very useful
(what would a user do on the GitHub page?) and bloat the file when
viewed in a terminal/editor.

README: Small tweaks/clarifications/plain text beautifications

---

driver/toobj.cpp

On the ARM scaleway buildbot, I saw this warning:
```
/var/lib/buildbot/slaves/scaleway/armv7_builder/build/driver/toobj.cpp: In constructor ‘{anonymous}::AssemblyAnnotator::AssemblyAnnotator(const llvm::DataLayout&)’:
/var/lib/buildbot/slaves/scaleway/armv7_builder/build/driver/toobj.cpp:152:56: warning: a temporary bound to ‘{anonymous}::AssemblyAnnotator::DL’ only persists until the constructor exits [-Wextra]
AssemblyAnnotator(const llvm::DataLayout &dl) : DL{dl} {}
```
http://buildbot.ldc-developers.org/builders/armv7_builder/builds/3087/steps/make/logs/stdio
Looks like this gcc bug: https://stackoverflow.com/questions/25561387/spurious-warning-about-binding-temporary-to-reference-member-in-constructor
So let's just use old-style initialization, and we should be good.

Small fix to fix compiler warning (gcc bug?)

---

tests/sanitizers/fuzz_asan.d
tests/sanitizers/fuzz_basic.d

..., because they are not output when the reproducing testcase is too long (> 256 chars).
This should fix the spurious failures https://github.com/ldc-developers/ldc/pull/2556#issuecomment-363888571

Remove checking of fuzz testcase characters

---

gen/functions.cpp
gen/nested.cpp
gen/toir.cpp

And so get rid of all loads too; just use the untouched pointer ~~argument~~ parameter directly.

Don't waste an alloca for the nested context argument

---

gen/toconstelem.cpp

This is an LDC for the in progress dmd fix https://github.com/dlang/dmd/pull/7704
But because I don't know dmd's code base very well I'm fixing it here first because I want it to fix https://github.com/libmir/dcompute/issues/32 and ldc has better diagnostics.
There is something very strange indeed going on with the codegen:
```
10B4C4500 10B4C43F0
40 10B4C4500
bar2
2 3
core.exception.AssertError@./runnable/test17899.d(28): Assertion failure
```

DMD issue 17899

---

gen/toconstelem.cpp

In a less hacky fashion. It also uses the correct dmd-testsuite pointer (current ldc branch head).

 Re-implement module-scope initialized delegates (#2508)

---

gen/abi-aarch64.cpp
gen/abi.h

This is the code from issue #2150. Greatly improves the ABI.

[ltsmaster] AArch64: Structs should not be passed with byval attribute

---

dmd2/root/port.c

I am amazed that no CI environment caught this error.

[ltsmaster] Fix missing space in preprocessor directive.

---

.circleci/config.yml
ldc2.conf.in
runtime/CMakeLists.txt

If I understand the CMake docs correctly, CMake >= 3 defaults to setting the install_name appropriately when installing a shared library target (e.g., for MULTILIB=OFF).
Once again, the 32/64-bit merging step for OSX libraries prevents this automatism, as the merged libs are custom targets, so do it manually in form of a post-build command.

OSX: Set install_name of merged dylibs (issue #2442)

---

gen/arrays.cpp
gen/arrays.h
gen/toir.cpp
tests/codegen/array_catassign_gh2588.d

I.e., this fixes #2588.
To fix the index of the new array element to be assigned to, I went for decrementing the new length instead of saving the old length directly before the druntime call (i.e., after evaluating the rhs expression due to its potential side effects). The IR seems more intuitive to me this way - load both new length+ptr directly after the druntime call and then decrement the length by 1.

Fix cat-assign-element issue if rhs affects the lhs length

---

.travis.yml

Update to LLVM 5.0.1 and add LLVM 3.6.2 (which is still supported
on ltsmaster).

[ltsmaster] Update Travis configuration.

---

gen/trycatchfinally.cpp

The following code currently segfaults:
```d
extern (C++) void throwStdException();
void main() {
import std.stdio : writeln;
try {
throwStdException();
} catch (Throwable t) {
writeln("Caught a Throwable");
}
}
```
```cpp
#include <exception>
void throwStdException() { throw std::exception(); }
```
Because the personality routine in [`druntime/rt/dwarfeh.d`](https://github.com/ldc-developers/druntime/blob/ec48d54d331519f87beb03d82d5c4934eef3f03a/src/rt/dwarfeh.d#L1240) makes the wrong assumption that when it encounters a C++ exception, the catch clauses in the action table that it gets to examine are raw `std::type_info` pointers, which isn't the case if it's a `Throwable` (or derived) catch.
To make it possible for the personality routine to differentiate the two kinds of catch clauses, …

Differentiate C++ catch clauses from D ones with __cpp_type_info_ptr

---

tests/lit.site.cfg.in

Running the lit tests while building ldc 1.8.0-beta1 package with the Nix package manager on Mac OSX results in:
```
797: $ "make" "-f" "/private/tmp/nix-build-ldcBuild-1.8.0-beta1.drv-0/ldc-1.8.0-beta1-src/tests/plugins/addFuncEntryCall/Makefile"
797: # command output:
797: g++ -O3 -I/nix/store/r383pjg0ck57kl3z2afmy9pqkyllxj60-llvm-5.0.1/include -stdlib=libc++ -fPIC -fvisibility-inlines-hidden -std=c++11 -pedantic -O3 -DNDEBUG -fno-exceptions -DLLVM_BUILD_GLOBAL_ISEL -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-rtti -fpic -Wl,-flat_namespace -Wl,-undefined,suppress -shared /private/tmp/nix-build-ldcBuild-1.8.0-beta1.drv-0/ldc-1.8.0-beta1-src/tests/plugins/addFuncEntryCall/addFuncEntryCallPass.cpp -o addFuncEntryCallPass.so
797: 
797: # command stderr:
797: …
```

WIP: Fix addFuncEntryCall lit test run by forwarding CXX variable

---

driver/main.cpp

Enable the `uclibc` in triple, example usage  `arm-linux-uclibc`.
Unfortunately `uclibc` is not supported in the LLVM predefined identifiers, a patch was proposed a while ago but was not accepted, so I used the string version form the triple. I reckon this should be OK for most people using this (a rather small group :) )

Add the `CRuntime_UClibc` version identifier

---

gen/dibuilder.cpp
gen/dibuilder.h
gen/functions.cpp
gen/nested.cpp

A changed condition leads to a missing load.

[ltsmaster] Fix backport of PR #2315.

---

driver/main.cpp
gen/llvmhelpers.cpp
gen/llvmhelpers.h
gen/runtime.cpp

With this pull, only two tests fail from the dmd testsuite on Alpine/x64.  [This one asserts because of some stack trace issue](https://github.com/ldc-developers/dmd-testsuite/blob/ldc/runnable/test17559.d#L48), and [this 32-bit test fails out with a different error than expected](https://github.com/ldc-developers/dmd-testsuite/blob/ldc/fail_compilation/fail80_m32.d) because [this druntime module has not been ported to `X86` yet](https://github.com/ldc-developers/druntime/blob/ldc/src/core/sys/posix/sys/types.d#L642). Neither is a big deal, so unless @yshui wants to handle them, this patch should be enough for the 1.8 release.

Pull in Musl's assert function for betterC mode.
