ldc-developers/ldc

gen/runtime.cpp
This caught my eye while investigating why EH doesn't work on Win64 with current LLVM 3.6 head. It used to work a couple of months ago. This PR doesn't fix the actual problem, it just fixes the LL signature used when invoking the LL ```landingpad``` instruction for Win64 and ARM.
The actual problem seems to be the native exception raised via ```RtlRaiseException()``` in ```ldc.eh2._d_throw_exception()``` ending up unhandled. I got the impression that LLVM is trying to natively support Windows SEH but I have no idea what the status quo is. @redstar Could you possibly have a look at this?
/edit: This may have something to do with it: http://reviews.llvm.org/rL228733
=> Fix forward-declared LL signature of function _d_eh_personality.

gen/toir.cpp
Ignore LL type mismatches between the overall expression and its 2 nested true/false expressions.
This fixes a unittest compile error in ```std.datetime:30975```:
```
sign == 1 ? cast(immutable(TimeZone))UTC()
: cast(immutable(TimeZone))new immutable SimpleTimeZone(Duration.zero);
```
The overall type is ```immutable(TimeZone)```, the true expression's type is ```immutable(TimeZone)``` too, but the false expression's cast is omitted (e2->toChars(): ```new immutable(SimpleTimeZone)(zero(), "")```) and its type is thus ```immutable(SimpleTimeZone)```.
I guess we can perform implicit casts here (if required) as the front-end should have validated the D types already.
=> Don't care about mismatching types in conditional expressions.

driver/toobj.cpp
Outputs debug information as comments in .ll file.
Provided by Trass3r.
=> Add AssemblyAnnotationWriter.

gen/classes.cpp, gen/classes.h
By syncing with DMD's `toobj.c`.
=> Set flag `hasDtor` for ClassInfos, if appropriate.

ir/irtypeaggr.cpp
=> Fix struct alignment padding type selection

ir/irlandingpad.cpp
Instead of on a per-landing-pad basis.
See LLVM commit cc714e2.
=> LLVM 3.7: set personality function on a per-function basis.

dmd2/mtype.c
=> Do not emit large struct initializers as code

ldc2.conf.in, ldc2_install.conf.in, ldc2_phobos.conf.in, runtime/CMakeLists.txt
A work-around for https://github.com/ldc-developers/ldc/issues/442 regarding debug infos.
=> MSVC: pass /LARGEADDRESSAWARE:NO to MS linker.

.travis.yml
Advantages: more CPU, more memory.
Disadvantages: currently not all LLVM versions are available
=> Try the new Travis docker environment

dmd2/root/port.c
My upstream PR https://github.com/D-Programming-Language/dmd/pull/4870 is obsolete for DDMD. It's still useful for VS2015 LDC builds until we support DDMD. It fixes a couple of dmd-testsuite tests checking error msges when parsing invalid floating point literals.
=> Use Visual Studio 2015 C99 conformance in MSVC port.

gen/abi-x86.cpp
OS X varies from IA-32 by returning structs of 1 or 2 bytes in EAX and 4 or 8 bytes in EAX:EDX; other structs still use an sret arg.  The return value also is rewritten as an int type for LLVM to use the correct return registers (this matches clang).
Now the resulting IR for
```d
struct PointF {float a, b;}
extern(C) PointF pfret();
```
Matches clang:
```
declare i64 @pfret()
```
Note - also changed so D static arrays are always returned by sret arg.  It doesn't make sense to return a array by value and generates lots of code for bigger arrays.
Test runnable/cabi1.d checks most struct return types and now passes for OS X 32-bit along with runnable/cppa.d.  I have an additional test which checks all struct bytes sizes from 1-8 which should probably be added to the test suite.
The only …
=> OS X x86 ABI - fix struct return

gen/tocall.cpp
@redstar: This should go into alpha 3 too.
=> Work around instruction dominance issue with struct ctors

gen/statements.cpp
@redstar: This should definitely go into alpha 3 as well.
=> Fix throwing inside catch (should not target later catches of same try)

appveyor.yml
kernel32.lib not found by MS linker during CMake configuration... :/
They've somehow managed to screw up their VM in the 2 weeks I was on vacation.
=> Appveyor troubleshooting

utils/gen_gccbuiltins.cpp
Modifies gen_gccbuiltins.cpp to add the relatively new @nogc to each compiler intrinsic. Also adds 'const' to void* arguments of intrinsics with "IntrRead*Mem" set.
=> Make GCC intrinsics usable with @nogc and const *

gen/arrays.cpp
=> Fix infinite recursion with empty member array default initializers

gen/arrays.cpp, gen/arrays.h, gen/llvmhelpers.cpp
=> Fix misaligned vector variable initializers

gen/toir.cpp
It may be the initialization of the variable's hidden pointer, or the initialization of the pointee.
This fixes bugzilla 14944 for us (tested in `runnable/sctor.d`), see https://github.com/D-Programming-Language/dmd/pull/5013.
=> Watch out for special case when initializing ref variables

driver/configfile.cpp, driver/configfile.h, driver/ldmd.cpp, driver/main.cpp
One more step towards the 0.16 release. :)
Addresses https://github.com/ldc-developers/ldc/issues/879 and https://github.com/ldc-developers/ldc/issues/972.
=> Implement -conf command-line switch for LDC2 and LDMD2

driver/linker.cpp, driver/linker.h, driver/main.cpp
Add missing forward of execution result.
=> issue #1161: return status if lib invocation failed

CMakeLists.txt, driver/codegenerator.cpp, driver/main.cpp, gen/dibuilder.cpp, gen/passes/SimplifyDRuntimeCalls.cpp
My attempts to build LDC against current LLVM master.
Not sure if there is a replacement for initializeIPA.
=> fix build against llvm master (llvm 3.8)

gen/dibuilder.cpp, gen/functions.cpp
=> Emit debug info for ref and out parameters

gen/runtime.cpp, gen/statements.cpp, ir/irfunction.cpp, ir/irfunction.h
Includes https://github.com/ldc-developers/druntime/commit/48ef2d5da97f838a1f51e0db22189f1ffb4267cd.
=> eh: Do not use GC for _d_exception records

.travis.yml, appveyor.yml
And re-arrange order of LLVM IR tests (after dmd-testsuite, before unittests).
=> Fix Travis script

gen/aa.cpp, gen/abi-aarch64.cpp, gen/abi-generic.h, gen/abi-mips64.cpp, gen/abi-ppc64.cpp, gen/abi-win64.cpp, gen/abi-x86-64.cpp, gen/abi.cpp, gen/arrays.cpp, gen/attributes.cpp, gen/attributes.h, gen/dvalue.cpp, gen/functions.cpp, gen/llvmhelpers.cpp, gen/nested.cpp, gen/rttibuilder.cpp, gen/structs.cpp, gen/tocall.cpp, gen/toir.cpp, gen/tollvm.cpp, gen/tollvm.h, tests/ir/align.d, tests/ir/atomicrmw.d
=> Further alignment fixes and some renamings

README.md
We also require the C libconfig now, not the C++ interface.
=> README: Mention binary packages in install section

driver/main.cpp, gen/abi-x86.cpp, gen/dibuilder.cpp, gen/tocall.cpp
This fixes a few compiler warnings, and tries to simplify the structure of a few #if constructs.
=> Fix a few compiler warnings.

gen/functions.cpp, gen/uda.cpp, gen/uda.h, tests/ir/attributes.d
=> Add tests for @ldc.attributes.section and implement it for functions.

gen/module.cpp, gen/runtime.cpp
=> FreeBSD: generate calls to _d_dso_registry (as expected by druntime).

.travis.yml
Also adds support for LLVM 3.9.
=> Travis: Make LLVM 3.8 a required build.

driver/linker.cpp, driver/targetmachine.cpp, gen/target.cpp, gen/tollvm.cpp
Use the same code for FreeBSD, NetBSD, OpenBSD and DragonFly BSD.
=> Add more support for xBSD type OS.

.travis.yml
Dan fixed the issue with #1252.
=> Travis: Release build on OS X is now a required build.

driver/linker.cpp, driver/toobj.cpp
=> Fix error message formatting

appveyor.yml
As requested by @JohanEngelen in the forum. :)
=> AppVeyor: install DMD, update libcurl

gen/toir.cpp
=> package methods are always final

gen/asmstmt.cpp
=> Increment counter for output constraints.

gen/optimizer.cpp
This PR removes the command line option which adds the pass names as additional
command line options. This code prevents compiling for AArch64 (since LLVM 3.7)
and ARM (since LLVM 3.8). Recommendation on LLVM list was to use the PassNameParser
only in test tools but not in a production compiler.
=> Remove PassNameParser (may be breaking some command lines!)

gen/functions.cpp
=> DtoDefineFunction: Avoid assertion after unanalyzed function ICE

dmd2/root/port.c
This is much more easier then defining all those bit patterns.
=> Retrieve all NaN patterns from LLVM.

gen/declarations.cpp, gen/functions.cpp, gen/inlineir.cpp, gen/llvmhelpers.cpp, gen/llvmhelpers.h, gen/module.cpp, gen/passes/StripExternals.cpp, gen/rttibuilder.cpp, gen/tollvm.cpp, gen/tollvm.h, gen/typinf.cpp, ir/irclass.cpp, tests/ir/align.d
This tackles https://github.com/ldc-developers/ldc/issues/1310.
=> Linkage type and COMDAT

circle.yml
Use the new llvm-3.9 packages.
=> Fix Circle-CI build.

gen/statements.cpp
=> Fix string switch table sorting

gen/abi-aarch64.cpp, gen/abi-arm.cpp, gen/abi-x86-64.cpp, gen/abi-x86.cpp, gen/abi.cpp, gen/abi.h, gen/objcgen.cpp, gen/objcgen.h, gen/runtime.cpp, gen/tocall.cpp
Another go at the Objective-C functions.  I think this is close to what could be put into 1.0.0.  Plumbed in support for arm and arm64 too.  Test suite is now enabled for x86 32-bit too.
=> WIP - Cleanup and refactor Objective-C support

gen/aa.cpp, gen/arrays.cpp, gen/llvmhelpers.cpp, gen/llvmhelpers.h, gen/toir.cpp, gen/tollvm.cpp
This fixes issue #894 and includes some refactorings.
=> Optimize array comparisons against null

ddmd/dsymbol.h, ddmd/mtype.h
Unfortunately, cherry-picking these commits from dmd does not work as the ddmd sources are not a fork of dmd.
=> Fix const qualifiers in ddmd C++ headers

driver/main.cpp, gen/coverage.cpp, gen/llvmhelpers.cpp, gen/llvmhelpers.h, gen/ms-cxx-helper.cpp, ir/irtype.cpp
another PR to build with LLVM master, this time also adding our own context.
=> Fix master for recent LLVM master changes

gen/llvmhelpers.h, gen/runtime.cpp, gen/uda.cpp, tests/codegen/attr_llvmattr.d
~~Resolves #1438~~
Partly resolves #1438
=> Add `@ldc.attributes.llvmAttr`

appveyor.yml
This fixes up #1458, sorry for the mess.
=> Fix AppVeyor std.string unit test argument patching

gen/classes.cpp, gen/llvmhelpers.cpp
A simple C++ification of a few loops.
(this relaxes the requirements on the `members` data structure: random indexed access is not needed, just iteration)
=> C++11 a few loops [NFC]

ddmd/mtype.d, gen/nested.cpp, gen/toir.cpp
There were no druntime/Phobos changes between b1 and the final version.
=> Update frontend to the final 2.071 release

driver/linker.cpp, gen/module.cpp
The temporary files created may clash with parallel processes (e.g. in a test suite where LDC is called in parallel with perhaps same input).
These files will be deleted after execution so their name is not relevant. For better linking errors, the new filenames are created by appending random characters to their name.
Note that there is no check whether the random executable file exists (same as for the normal infered executable filename). We don't want to overwrite the user's files, but I think the chances of a user having a file named "infered name + '_ldctemp' + random 8 digit hexadecimal number" are very slim.
For the object files, there is a (naive) existance check.
=> Use random output filenames for `-run`.

appveyor.yml
Please do not merge!
Is this how a phobos PR can be tested on the build servers?
=> trying to figure the failure on AppVeyor for x86

CMakeLists.txt, appveyor.yml, cmake/Modules/FindLLVM.cmake, driver/configfile.cpp, utils/gen_gccbuiltins.cpp
E.g. on my machine LLVM is installed in folder C:\My Program Files\LLVM.
Fixes part of issue #1465. (PR 1466 is required for complete fix.)
=> Fix space handling for different paths.

cmake/Modules/FindDCompiler.cmake
=> [CMake] Allow relative paths for D_COMPILER

appveyor.yml
We are all green on AppVeyor! Let's try to keep it that way. ;)
=> [AppVeyor] Disallow Release build failures.

appveyor.yml
My 1st attempt to create LLVM packages for AppVeyor.
=> [AppVeyor] Update LLVM package

tests/lit.site.cfg.in, utils/FileCheck-3.5.cpp, utils/FileCheck-3.6.cpp, utils/README.md
Attempts to fix lit-based test errors possibly due to a FileCheck bug.
=> [Lit] Give priority to LDC's version of LLVM tools

appveyor.yml, driver/main.cpp, gen/arrays.cpp, gen/toconstelem.cpp, gen/toir.cpp, gen/tollvm.cpp, ir/irclass.cpp, utils/FileCheck-3.9.cpp
new argumets to GlobalValue::setUnnamedAddr
=> fix build against LLVM trunk svn rev 273030

.travis.yml
=> [Travis] Do the LLVM binaries work on Ubuntu 12?

tests/codegen/array_equals_null.d
As requested in https://github.com/ldc-developers/ldc/pull/1393. Let's close https://github.com/ldc-developers/ldc/issues/894 with this.
=> Add IR test for optimized array (in)equality with null

gen/statements.cpp
=> Always create new "after return" block for unreachable code

gen/llvmhelpers.cpp, gen/toir.cpp
A follow-up for https://github.com/ldc-developers/ldc/pull/1586.
=> AssignExp: Refactor direct construction by rhs call via sret

gen/abi-aarch64.cpp, gen/abi-arm.cpp, gen/abi-x86-64.cpp, gen/abi.cpp, gen/abi.h, gen/functions.cpp, gen/tocall.cpp, gen/toir.cpp
I.e., `va_start()`, `va_copy()` and `va_arg()`.
=> Refactor and fix intrinsics for variadic functions

.travis.yml, appveyor.yml, gen/aa.cpp, gen/aa.h, gen/arrays.cpp, gen/dvalue.cpp, gen/dvalue.h, gen/functions.cpp, gen/llvmhelpers.cpp, gen/toir.cpp, tests/codegen/in_place_construct.d
Also for struct literal fields, array literal elements and associative array literal values as well as basic types allocated on the heap.
Touched files were re-clang-formatted, so there are pure formatting fixes too. :/
=> More in-place construction

driver/main.cpp
LLVM's ParseCommandLineOptions() expands response files automatically, but always uses the TokenizeGNUCommandLine tokenizer, which apparently eats backslashes.
The solution is to pre-expand the response files into the arguments vector on the LDC side, and using TokenizeWindowsCommandLine if LDC is built for Windows.
=> Fix issue #1621

.travis.yml
(we are again part of the release notes :-) 👍 )
http://llvm.org/releases/3.8.1/docs/ReleaseNotes.html
=> Tell Travis to use LLVM 3.8.1

gen/llvmhelpers.cpp, tests/codegen/funcliteral_defaultarg_gh1634.d
=> Implement codegen of function literals passed as default argument.

ddmd/declaration.d, ddmd/declaration.h
Cacheing isDataseg gives an overall speed improvement of 10%
I thought it should go into ldc asap.
=> Apply dmd PR #5842

driver/linker.cpp
=> Do the check that gExePath is not a directory (before deleting it) also in release builds

ddmd/statement.d, ddmd/statement.h, gen/statements.cpp
Another PR to remove bodyBB is upcoming, but the latter will include more refactorings because it makes sense to address #1661 first.
=> gen: Do not store CaseStatement index values in AST nodes

runtime/CMakeLists.txt
Based off GitHub pull request #1660, with minor edits.
=> FreeBSD: Fix shared library build, working Hello World

ddmd/root/rmem.d, gen/classes.cpp, gen/passes/GarbageCollect2Stack.cpp, gen/passes/SimplifyDRuntimeCalls.cpp, gen/runtime.cpp
See https://github.com/ldc-developers/druntime/pull/81 and #966. Fixing it in druntime is way simpler. :)
=> Fix issue #966 (initializing class instances twice)

ddmd/module.h, driver/codegenerator.cpp, driver/main.cpp, gen/llvmhelpers.cpp, gen/llvmhelpers.h, gen/module.cpp, gen/moduleinfo.cpp, gen/moduleinfo.h, gen/modules.cpp, gen/modules.h
Some general improvements as a prelude to OS X shared library support.
=> Refactor ModuleInfo registry code, optimize code size

tests/debuginfo/codeview.d
I'm still learning to deal with cdb...
=> make codeview test less brittle

driver/cl_options.cpp, driver/main.cpp, driver/response.cpp, driver/targetmachine.cpp, gen/arrays.cpp, gen/function-inlining.cpp, gen/llvmhelpers.cpp, gen/ms-cxx-helper.cpp, gen/passes/GarbageCollect2Stack.cpp, gen/toconstelem.cpp, gen/trycatchfinally.cpp, gen/uda.cpp, ir/irfuncty.cpp, ir/irmodule.cpp, ir/irmodule.h
=> Small mechanical code quality improvements

gen/dibuilder.cpp
The type of DIFlag parameters changed from unsigned to DIFlags in LLVM 4.0.
=> Fix LLVM 4.0 build.

gen/ms-cxx-helper.cpp, gen/ms-cxx-helper.h, gen/trycatchfinally.cpp
=> Fix linking error when using LLVM < 3.8 and enabled LDC assertions

gen/trycatchfinally.cpp
Running a cleanup with a dummy target BB and later replacing all uses of that dummy with the actual BB is buggy, as the cleanup keeps track of its exit targets (via pointers) which aren't updated.
=> Fix issue #1774

driver/configfile.cpp, gen/cl_helpers.h, gen/llvmhelpers.cpp
adopt to some `const char*` to `llvm::StringRef` changes
=> fix building against recent LLVM 4.0

LICENSE, runtime/profile-rt/README.md, runtime/profile-rt/README.txt, runtime/profile-rt/d/ldc/profile.d
- Relicense profile-rt/d/ldc/profile.d (sole author Johan Engelen).
- Add profile-rt license to LICENSE.
See https://forum.dlang.org/thread/kmkusabahjitopkhtgae@forum.dlang.org
=> Fix profile-rt licensing

gen/dibuilder.cpp, tests/debuginfo/basictypes_cdb.d
That's also what the Microsoft compiler emits for decltype(nullptr).
=> DI: display typeof(null) as void*

driver/ir2obj_cache.cpp, driver/linker.cpp
=> Create output directories recursively

gen/inlineir.cpp, gen/inlineir.h, gen/llvmhelpers.h, gen/naked.cpp, gen/toir.cpp, tests/codegen/in_place_construct_asm.d
=> Fix in-place construction of structs returned by inline assembly

gen/arrays.cpp, gen/arrays.h, tests/codegen/const_struct.d, tests/codegen/in_place_construct.d
Quick and dirty attempt at #506 :)
=> Check StructLiteralExp elements in isConstLiteral.

gen/modules.cpp
I don't have Linux, but tested it on Weka's buildserver. The dot in the section name does not work (`__start_.minfo`), so I renamed the section to `__minfo` (only for ELF).
The previous bracketing of the .minfo section does not work when ThinLTO is employed. It appears that LLVM IR puts no guarantees on bracketing layout of symbols in custom sections, or it is an LLVM bug. Either way, we can rely on linker magic to fix the ThinLTO case.
@klickverbot Looks good?
=> ELF: Use magic linker symbol names for begin/end of .minfo.

gen/runtime.cpp
I hope the revert isn't required anymore due to David's latest OSX work. We'll see.
=> Re-check existing runtime function declarations for matching type

driver/cache.cpp, gen/dibuilder.cpp, gen/llvmhelpers.cpp
This will probably be necessary for CircleCI soon.
=> fix build against current LLVM master @ 9b4e8286785f

gen/uda.cpp
=> Refactoring of UDA code (from dcompute branch) [NFC]

driver/cache.cpp, driver/toobj.cpp, gen/runtime.cpp
llvm/Bitcode/ReaderWriter.h has been split and renamed
=> fix build against LLVM master

gen/arrays.cpp, tests/codegen/const_struct.d
Let's see if the test suite likes this.
=> Consider string literals as constant in isConstLiteral.

gen/modules.cpp
Note: the target branch is `release-1.1.0`.
Follow-up of https://github.com/ldc-developers/ldc/pull/1889 , https://github.com/ldc-developers/ldc/issues/1862
=> Backport #1835.

gen/typinf.cpp
Fields `m_arg{1,2}` are only declared for x86_64 targets, so there was a size mismatch. In the best case, this lead to `m_RTInfo` containing a TypeInfo pointer instead of the `hasPointers` flag in the least significant bit (=> no `hasPointers`). `hasPointers` is also specified in `m_flags` though, so I'm not sure `m_RTInfo` is actually used.
=> Fix TypeInfo_Struct constants for all non-x86_64 64-bit targets

driver/cl_options.cpp, driver/cl_options.h, driver/main.cpp, ir/irfunction.cpp, tests/codegen/ffastmath.d
=> Implement -ffast-math.

cmake/Modules/FindLLVM.cmake
=> CMake: add version check to findLLVM

driver/cl_options.cpp, driver/ldmd.cpp, gen/modules.cpp
=> Sync command-line options and descriptions with DMD

tests/codegen/align.d
@smolt: Continuation of #1966 .
=> Fix alignment test for ARM.

cmake/Modules/FindLLVM.cmake
Hopefully fixing the AppVeyor builds.
=> [ltsmaster] Sync LLVM-related CMake stuff from master

gen/dibuilder.cpp, gen/nested.cpp, tests/compilable/gh1933.d, tests/debuginfo/nested.d, tests/debuginfo/nested_llvm306.d, tests/debuginfo/nested_llvm307.d
=> Put debuginfo on GEP instead of on the alloca with an offset.

runtime/CMakeLists.txt
=> Linux: Always build C parts of standard library as PIC

gen/arrays.cpp, tests/codegen/const_struct.d, tests/codegen/const_struct_export.d
=> Consider pointer literals as constant in isConstLiteral.

driver/main.cpp, gen/semantic-dcompute.cpp, gen/semantic.d, gen/uda.cpp
=> [dcompute] fix semantic.d

driver/ldmd.cpp
It wrongly started with argv[0] (path to ldc2 binary).
Found while using dub, which easily generates command lines > 75K (Windows limit: 32K). Luckily before the first alpha/beta. ;)
=> Fix LDMD regression when generating response file

gen/functions.cpp, runtime/profile-rt/profile-rt-50/InstrProfData.inc, runtime/profile-rt/profile-rt-50/InstrProfilingFile.c, runtime/profile-rt/profile-rt-50/InstrProfilingUtil.c, runtime/profile-rt/profile-rt-50/InstrProfilingUtil.h, runtime/profile-rt/profile-rt-50/InstrProfilingValue.c
The "TODO" comment is very low priority.
=> Fix LLVM 5.0 build and update profile-rt

gen/uda.cpp, tests/codegen/attr_llvmFMF_contract.d
=> Implement @ldc.attributes.llvmFastMathFlag("contract") magic UDA.

ddmd/globals.d, ddmd/globals.h, driver/cl_options.cpp, driver/cl_options.h, driver/codegenerator.cpp, driver/main.cpp, gen/dibuilder.cpp, tests/driver/save_optimization_record.d
=> Implement -fsave-optimization-record

driver/cache.cpp, driver/cl_options.cpp, driver/configfile.cpp, driver/linker.cpp, driver/main.cpp, driver/toobj.cpp, gen/llvmhelpers.cpp, gen/modules.cpp, gen/optimizer.cpp, gen/passes/GarbageCollect2Stack.cpp, gen/pgo.cpp, gen/runtime.cpp, gen/toir.cpp
Except for `-sanitize` to make clear that they cannot be combined.
=> Allow multiple occurrences of all command-line flags

.clang-format, driver/cache.cpp, driver/cl_options.cpp, driver/configfile.cpp, driver/linker.cpp, driver/toobj.cpp, gen/llvmhelpers.cpp, gen/modules.cpp, gen/optimizer.cpp, gen/passes/GarbageCollect2Stack.cpp, gen/pgo.cpp, gen/runtime.cpp, gen/toir.cpp
Should only touch recently changed code to minimize unpleasantness from merge conflicts/….
=> clang-format some code, trivial style changes [nfc]

driver/linker.cpp, gen/functions.cpp, gen/llvmhelpers.cpp, gen/modules.cpp, gen/naked.cpp, gen/statements.cpp, gen/tocall.cpp, gen/toconstelem.cpp, gen/toir.cpp, gen/tollvm.cpp, gen/uda.cpp
Most of those exposed by our CI compilers at least.
=> Fix C++ warnings

gen/dvalue.cpp, gen/tollvm.cpp, tests/codegen/gh2131.d
When optimizing the code, analogous to clang, fixing one aspect of issue #2131.
=> Add range metadata when loading bools

gen/optimizer.cpp
=> Set PassManagerBuilder::PrepareFor(Thin)LTO.

.travis.yml, driver/codegenerator.cpp, runtime/profile-rt/profile-rt-50/InstrProfiling.c, runtime/profile-rt/profile-rt-50/InstrProfilingBuffer.c, runtime/profile-rt/profile-rt-50/InstrProfilingFile.c, runtime/profile-rt/profile-rt-50/InstrProfilingInternal.h, runtime/profile-rt/profile-rt-50/InstrProfilingNameVar.c, runtime/profile-rt/profile-rt-50/InstrProfilingWriter.c, tools/ldc-profdata/llvm-profdata-4.0.cpp, tools/ldc-profdata/llvm-profdata-5.0.cpp
The profile-rt update is a copy from compiler-rt, so nothing to review there.
Only interesting change is in `driver/codegenerator.cpp` (NFC).
=> Update profile-rt and fix LLVM5.0 build

.travis.yml
They're migrating to Trusty implicitly starting with July 18th.
=> Travis: Switch to Trusty

.circleci/config.yml, CMakeLists.txt
Also fixes libLLVMFuzzer -> libFuzzer naming confusion.
=> Add libFuzzer and ASan to CircleCI

driver/linker-gcc.cpp, tests/sanitizers/fuzz_asan.d, tests/sanitizers/fuzz_basic.d, tests/sanitizers/link_fuzzer.d
=> Add automatic libFuzzer linking + fuzz test

appveyor.yml
Incl. support for Android TLS and CodeView D language.
Built with Visual Studio 2017 this time.
=> AppVeyor: Use LDC-LLVM 4.0.1

driver/main.cpp
https://llvm.org/viewvc/llvm-project?view=revision&revision=309286
=> [trivial] LLVM reverted the change that required these version specific changes.

.travis.yml, CMakeLists.txt, appveyor.yml, driver/codegenerator.cpp, driver/configfile.cpp, driver/exe_path.cpp, driver/exe_path.h, driver/ldmd.cpp, driver/main.cpp, driver/toobj.cpp, gen/abi-ppc64le.cpp, gen/asmstmt.cpp, gen/attributes.cpp, gen/attributes.h, gen/cl_helpers.h, gen/dibuilder.cpp, gen/functions.cpp, gen/irstate.h, gen/llvmhelpers.cpp, gen/passes/GarbageCollect2Stack.cpp, gen/runtime.cpp, gen/tocall.cpp, ir/irfunction.cpp, ir/irfuncty.cpp
@redstar I got `ltsmaster` to build with this PR. But there is a debuginfo LLVM assert when building the debug version of Phobos.
=> Update LDC 0.17.x to LLVM 5.0 (2nd try)

runtime/CMakeLists.txt
Based on @joakim-noah's command-line in https://wiki.dlang.org/Building_LDC_runtime_libraries.
=> Improve Android support in runtime CMake script

tests/sanitizers/fuzz_basic.d
Hopefully this fixes the sporadic test failures on CircleCI.
=> fuzz_basic.d: make bad input easier to find for fuzzer

tests/lit.site.cfg.in
=> lit tests: forward "CC" environment variable

gen/dibuilder.cpp, gen/dibuilder.h, gen/functions.cpp, gen/nested.cpp, tests/debuginfo/args_cdb.d, tests/debuginfo/nested_cdb.d, tests/debuginfo/nested_gdb.d
=> Adapt to LLVM 5.0 debuginfo changes & misc. fixes, mainly for Win64

tests/compilable/dcompute.d
And fix some typos.
@thewilsonator
=> [trivial] Fix compilable/dcompute.d such that it actually compiles the code.

driver/ldmd.cpp, driver/tool.cpp, utils/not.cpp
See https://reviews.llvm.org/D37563
=> [trivial] Fix LLVM 6.0 compilation.

gen/nested.cpp, tests/codegen/nested_lazy_gh2302.d
=> Fix storage of captured lazy parameters (depending on ABI)

gen/llvmhelpers.cpp, gen/runtime.cpp
=> Android: Use proper C assert function signature

driver/toobj.cpp
=> IR annotations: Let LLVM print debug locations

.travis.yml, ddmd/cppmangle.d, gen/ms-cxx-helper.cpp, gen/runtime.cpp, gen/target.cpp, gen/trycatchfinally.cpp, runtime/CMakeLists.txt
=> druntime: Use adapted upstream DWARF EH & enable catching C++ exceptions

runtime/profile-rt/DefineBuildProfileRT.cmake, runtime/profile-rt/profile-rt-60/GCDAProfiling.c, runtime/profile-rt/profile-rt-60/InstrProfData.inc, runtime/profile-rt/profile-rt-60/InstrProfiling.c, runtime/profile-rt/profile-rt-60/InstrProfilingFile.c, runtime/profile-rt/profile-rt-60/InstrProfilingInternal.h, runtime/profile-rt/profile-rt-60/InstrProfilingPlatformLinux.c, runtime/profile-rt/profile-rt-60/InstrProfilingPlatformOther.c, runtime/profile-rt/profile-rt-60/InstrProfilingPort.h, runtime/profile-rt/profile-rt-60/InstrProfilingUtil.c, runtime/profile-rt/profile-rt-60/InstrProfilingUtil.h, runtime/profile-rt/profile-rt-60/InstrProfilingValue.c, runtime/profile-rt/profile-rt-60/InstrProfilingWriter.c, runtime/profile-rt/profile-rt-60/WindowsMMap.c
The only interesting thing besides copying the compiler-rt files was the (manual) addition to the CMake file.
=> Update LLVM trunk (6.0) version of profile-rt.

CMakeLists.txt, driver/cl_options.cpp, driver/cl_options.h, driver/cl_options_instrumentation.cpp, driver/cl_options_instrumentation.h, driver/main.cpp, gen/cl_helpers.cpp, gen/cl_helpers.h, gen/runtime.cpp
More refactoring related to instrumentation. This time, it's just moving related instrumentation options into new files for only instrumentation-related options (to prepare the ground for more).
=> Move instrumentation options into their own .h/.cpp files [NFC]

runtime/CMakeLists.txt
This should fix remaining issues with unistd.h.
@dkgroot
=> Fix unistd header inclusion for all builds.

CMakeLists.txt, driver/cl_options_instrumentation.cpp, driver/cl_options_instrumentation.h, gen/modules.cpp, gen/optimizer.cpp, gen/pgo.cpp, gen/pgo.h, runtime/CMakeLists.txt, runtime/profile-rt/DefineBuildProfileRT.cmake, tests/lit.site.cfg.in
It's no longer needed, all our builds have it set to true.
http://forum.dlang.org/post/phtrhzyqtjzwyemwsqur@forum.dlang.org
=> Remove `LDC_WITH_PGO`.

cmake/Modules/FindLLVM.cmake, runtime/jit-rt/DefineBuildJitRT.cmake
This should fix https://github.com/NixOS/nixpkgs/issues/33127
@ThomasMader can you verify that this fixes the issue for NixOS?  (LLVM >= 4.0)
=> CMake: use llvm-config to determine LLVM's cmake directory, if possible.

runtime/jit-rt/DefineBuildJitRT.cmake
Required for qt creator to properly display headers in project tree
=> Small jit-rt cmake fix

runtime/jit-rt/cpp-so/compile.cpp, runtime/jit-rt/cpp-so/disassembler.cpp, runtime/jit-rt/cpp/compile.cpp
* Proper constness
* Moved `createResolver` to separate function
* `enumModules` helper function
* clang-format
=> jit runtime small refactorings

ddmd/builtin.d, tests/compilable/gh2458.d
=> Support llvm_expect() intrinsic during CTFE

driver/linker-gcc.cpp
the refactor part of https://github.com/ldc-developers/ldc/pull/2345
=> Refactor search logic for finding compiler RT libs to not use global triple [NFC]

driver/linker-gcc.cpp
This should help find the compilerRT libs when LDC is installed in the system's usual dirs. With this change, the ASan and libFuzzer libs do not need to be copied as part of building LDC.
With this PR, the path `LDC_LIB_DIR/clang/6.0.0/lib/linux/libclang_rt.asan-x86_64.a` is also searched.
To be honest, I don't know whether this actually works in practice. It all depends where clang would be installed. But I think it doesn't do harm, and should be clear how the logic can be improved by someone who does know.
=> Extend search logic for finding compiler RT libs. (ASan and libFuzzer)

tests/sanitizers/asan_noerror.d
On Linux, I ran into memory leaks reported for such a simple program. It appears to be fixed now (dlang2.078). Fixed in ~~https://github.com/dlang/druntime/pull/1557~~, https://github.com/dlang/druntime/pull/1918, https://github.com/dlang/druntime/pull/1857.
Thanks @MoritzMaxeiner
=> Add a test to verify that a simple program passes ASan without error.

gen/binops.cpp, gen/llvmhelpers.cpp, tests/codegen/gh2537.d
=> Account for AST binop quirks

driver/linker-gcc.cpp, driver/main.cpp
=> Add predefined version CRuntime_Musl

gen/asm-x86.h, tests/semantic/asm_datadefinition_diag.d
See: https://github.com/ldc-developers/ldc/issues/2548
=> Error on data definition directives inside inline asm.

.travis.yml
=> Fix OS X build on Travis.

gen/dynamiccompile.cpp, runtime/jit-rt/cpp-so/disassembler.cpp, runtime/jit-rt/cpp-so/optimizer.cpp, tests/dynamiccompile/jit_module_stripping.d
* Better thunks stripping from jit module.
* Fixes to jit disassembler
* Strip comdats from jit module
=> Small jit fixes

CMakeLists.txt, gen/dynamiccompile.cpp, runtime/jit-rt/cpp-so/compile.cpp, runtime/jit-rt/cpp-so/context.h, runtime/jit-rt/cpp-so/disassembler.cpp, runtime/jit-rt/cpp/compile.cpp, tests/dynamiccompile/asm_output.d, tests/dynamiccompile/global_opt.d, tests/dynamiccompile/jit_module_stripping.d
Also, I am going to drop jit support for pre 5.0 llvm to reduce ifdef clutter.
=> llvm 70 jit fixes

.travis.yml, cmake/Modules/FindLLVM.cmake, driver/cl_options.cpp, driver/ldmd.cpp, driver/main.cpp, driver/toobj.cpp, driver/tool.cpp, gen/dibuilder.cpp, utils/FileCheck-6.0.cpp, utils/not.cpp
Adds the necessary changes to support LLVM 6.
=> [ltsmaster] Add support for LLVM 6

tests/sanitizers/fuzz_mixin.d
Resolves issue #2501 
druntime: https://github.com/ldc-developers/druntime/pull/115
=> Fuzzing: add convenience mixin LibFuzzerEntryPoint.

.travis.yml
=> [ltsmaster] Update to LLVM 6 release version.

README.md
See also: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/ldc/default.nix
CC @ThomasMader
=> Add Nix/NixOS install commands to the install instructions

driver/main.cpp
The default ABI determined in the `createTargetMachine` for the `uclibc` environment and `Linux` `ARM` is `EABI`, uClibc uses `GNUEABI`.
Without the correct ABI, exceptions, array ops and probably others where not working.
Don't know if this is the best way to do it,  but this made druntime test pass with the triple `armv6-hardfloat-linux-uclibc` on actual hardware.
=> Fixup ABI for uClibc

CMakeLists.txt
See:
- https://cmake.org/cmake/help/v3.0/policy/CMP0025.html#policy:CMP0025
- https://stackoverflow.com/a/10055571/3215806
=> [CMake] Future-proof detection of Clang compiler on macOS [NFC]

README.md
Seems to be up-to-date and well maintained: https://chocolatey.org/packages/ldc
(also fixed the formatting in the table while I was at it)
=> Add Chocolately to the install instructions

tests/codegen/asm_output.d
=> Try to test asm output in another way for more platform independence

gen/naked.cpp, tests/codegen/export_naked_gh2648.d
=> [2.079] MSVC: Support exporting naked functions

driver/main.cpp, tests/linking/fullystatic.d
=> Enforce static default libs with cmdline option -static

CMakeLists.txt, cmake/Modules/CheckLinkFlag.cmake
Resolves issue #2638
@redstar Can you test this? (the buildbots are not testing PRs)
=> Fix building on Solaris

driver/main.cpp
Set global.params.isDragonFlyBSD = triple->isOSDragonFly()
=> [Trivial] set global.params.isDragonFlyBSD

gen/asm-x86.h, gen/asmstmt.cpp, tests/codegen/asm_labels.d
=> Fix inline asm label naming issue in overloaded functions

driver/archiver.cpp
It seems to be hitting non-ENOENT when trying to open a non-existent target library, although the error code's message is `No such file or directory`. - Prefer an `exists()` check instead of relying on an exact error code.
=> Fix internal archiver issue for SemaphoreCI

dmd/attrib.d, dmd/attrib.h, dmd/cond.d, dmd/constfold.d, dmd/dinterpret.d, dmd/expression.d, dmd/expression.h, dmd/func.d, dmd/identifier.d, dmd/identifier.h, dmd/lexer.d, dmd/mars.d, dmd/mtype.d, gen/abi-aarch64.cpp, gen/abi-arm.cpp, gen/abi-x86-64.cpp, gen/asm-x86.h
=> Upgrade to upstream `stable`

runtime/jit-rt/cpp-so/compile.cpp, runtime/jit-rt/cpp-so/disassembler.cpp, tests/dynamiccompile/asm_output.d
Should fix `asm_output` issue on arm (#2687 )
=> Jit asm printer fixes and minor cleanups

runtime/jit-rt/cpp-so/compile.cpp, runtime/jit-rt/cpp-so/disassembler.cpp, runtime/jit-rt/cpp-so/jit_context.cpp, runtime/jit-rt/cpp-so/jit_context.h
* MyJIT moved to separate file and renamed
* Some llvm7.0 fixes
=> Jit refactoring

dmd/id.d, dmd/id.h, gen/dynamiccompile.cpp, gen/functions.cpp, gen/uda.cpp, ir/irfunction.cpp, ir/irfunction.h, tests/dynamiccompile/emit.d
Will be useful for `bind`
druntime part: https://github.com/ldc-developers/druntime/pull/144
=> @dynamicCompileEmit attribute

appveyor.yml, ldc2.conf.in, ldc2_install.conf.in, ldc2_phobos.conf.in, runtime/CMakeLists.txt, tests/baremetal/wasm2.d
The first Phobos commit is pending upstream, https://github.com/dlang/phobos/pull/6639.
=> Phobos: Tiny tweaks to make std.{algorithm,range} baremetal-friendly

.circleci/config.yml, appveyor.yml, driver/cl_options_instrumentation.cpp, tests/PGO/irbased_indirect_calls.d
See https://github.com/ldc-developers/llvm/commit/4db8831367f2879f46c245ab046b8205567c164a.
=> Fix IR PGO for Windows (upgrade to LDC-LLVM 6.0.1-3)

gen/dynamiccompile.cpp, runtime/jit-rt/cpp-so/compile.cpp, runtime/jit-rt/cpp-so/context.h, runtime/jit-rt/cpp-so/jit_context.cpp, runtime/jit-rt/cpp/compile.cpp, tests/lit.site.cfg.in
* Some code style fixes
* Pyhon subprocess.call will throw `OSError` if file not present
=> Some code cleanup and lit tests fix

runtime/PresetRuntimeConfiguration.cmake
=> Android: remove C flag and always set llvm triple

dmd/builtin.d, dmd/root/ctfloat.d, dmd/root/ctfloat.h, dmd/root/filename.d
[Branched off LLVM 7 branch, as that one advances druntime & dmd-testsuite already.]
For beta2.
=> Merge upstream stable (0e308f5ac1)

tests/semantic/target_traits.d
(need to fix commit msg when pulling)
=> Fix target_traits.d test: Pentium is a 32bit CPU

gen/dibuilder.cpp, tests/debuginfo/args_cdb.d
Don't declare some special params as DI references, but as DI locals instead.
Also enable some Win32 checks in the args_cdb test, as they are working now with LLVM 7.
=> Debuginfo: Fix Win64 CodeView emission for some by-value params

.circleci/config.yml, shippable.yml
See https://github.com/dlang/installer/pull/282#discussion_r236917052
=> Remove date from nightly upload package to github CI release

.circleci/config.yml, driver/linker-gcc.cpp, shippable.yml, tests/baremetal/lit.local.cfg, tests/baremetal/wasm.d, tests/baremetal/wasm2.d, tests/lit.site.cfg.in
Overridable with `-linker`. See https://forum.dlang.org/post/qruindgwgbtmuccfujnp@forum.dlang.org.
=> Support external wasm-ld linker for WebAssembly targets

gen/llvmhelpers.cpp, gen/tollvm.cpp, tests/codegen/vector_intrinsics_gh2962.d
=> Support templated LLVM intrinsics with vector arguments

driver/cache.cpp, driver/cl_options-llvm.cpp, driver/cl_options-llvm.h, gen/functions.cpp, gen/optimizer.cpp, gen/optimizer.h, tests/codegen/attr_targetoptions.d, tests/codegen/exception_stack_trace.d, tests/lit.site.cfg.in, tests/sanitizers/fuzz_asan.d
LLVM 8 has branched, so the usual updating of LLVM pieces is needed.
This also resolves https://github.com/ldc-developers/ldc/issues/2980.
=> Support LLVM 9 (trunk)

.semaphoreci/job1.sh, CMakeLists.txt
=> Use semver-friendly version for untagged builds

runtime/jit-rt/cpp-so/compile.cpp
[little late to the party but I can live with CI builds]
=> Jit: report parseBitcodeFile errors

gen/declarations.cpp, gen/typinf.cpp, ir/iraggr.h, ir/irclass.cpp, tests/codegen/pragma_no_typeinfo.d
It had no effect on codegen whatsoever.
=> Fix pragma(LDC_no_typeinfo) - elide TypeInfo emission

.azure-pipelines/windows.yml
ldc-developers/mingw-w64-libs@8d930c1 (https://github.com/dlang/installer/pull/388) should fix the issues in https://forum.dlang.org/thread/uxmbtqqdomrrsnrssapc@forum.dlang.org.
=> Upgrade bundled mingw-w64-libs (with DLL entry point fix)

dmd/globals.d, dmd/globals.h, driver/main.cpp, gen/llvmhelpers.cpp, gen/llvmhelpers.h, gen/runtime.cpp, tests/linking/betterc.d
=> Fix C assert calls for uClibc

runtime/jit-rt/d/ldc/dynamic_compile.d, tests/dynamiccompile/bind.d
* Fix crash with partial parameters bind and delegates
* Better handling of const parameters
=> Jit bind fixes

gen/target.cpp, tests/baremetal/wasm.d, tests/baremetal/wasm2.d
https://github.com/ldc-developers/ldc/issues/3118
=> return 0 in getCriticalSectionSize for wasm

CMakeLists.txt, cmake/Modules/ExtractDMDSystemLinker.cmake, cmake/Modules/FindDCompiler.cmake
Depends on [this](https://github.com/D-Programming-GDC/gdmd/pull/6) gdmd pull request.
=> Support building with gdmd host compiler

dmd/declaration.d, dmd/declaration.h, dmd/escape.d, dmd/root/file.d, dmd/root/filename.d
A couple more fixes and preparatory work for #3086.
=> Merge upstream stable (75db01db16)

gen/toir.cpp, tests/codegen/vector_init.d
As a follow-up to #3130; the IR was too ugly to be ignored. ;)
=> Improve emission of vector literals

runtime/jit-rt/cpp-so/valueparser.cpp, tests/dynamiccompile/bind_bool.d
=> jit bind: fix bool handling

gen/llvmhelpers.cpp, tests/compilable/gh3162.d
=> Keep lvalue-ness when casting AA to another AA

CMakeLists.txt, cmake/Modules/BuildDExecutable.cmake
=> CMake: Fix regression for make

.travis.yml
It just took them about a month to finally upload a macOS package...
=> Travis: Bump LLVM version for macOS jobs

.travis.yml, gen/binops.cpp, tests/codegen/gh3208.d
=> Fix equality/identity comparisons of vectors with length >= 32

gen/semantic-dcompute.cpp, tests/compilable/dcompute.d
Also fix a deprecation in the test case.
=> Fix ctfe semantic analysis for dcompute

gen/dibuilder.cpp, gen/passes/GarbageCollect2Stack.cpp, gen/tollvm.cpp
Integer Align parameter on functions replaced by a function called MaybeAlign which can be initialized with an integer.
=> Support for LLVM 10 

dmd/mars.d, tests/compilable/gh3243.d, tests/compilable/inputs/bar/bla.di, tests/compilable/inputs/foo/bla.di
=> Fix wrong output file collision errors for .di files

gen/asmstmt.cpp
Just a mini follow-up to #3224.
=> Refactoring: Modernize some legacy asmstmt code

driver/main.cpp, tests/driver/cli_preparsing.d
Fixes #3268 and related issues.
=> Support 2 leading dashes in manual CLI pre-parsing

driver/configfile.cpp, driver/exe_path.cpp, driver/linker-gcc.cpp, driver/linker-msvc.cpp, driver/linker.cpp, driver/main.cpp, driver/targetmachine.cpp, driver/toobj.cpp, gen/ctfloat.cpp, gen/dynamiccompile.cpp, gen/inlineir.cpp, gen/uda.cpp, runtime/jit-rt/cpp-so/compile.cpp
https://github.com/llvm/llvm-project/commit/777180a32b61070a10dd330b4f038bf24e916af1
=> Fix StringRef conversion for LLVM 11 (777180a32b61070a10dd330b4f038bf24e916af1)

README.md
dlang/phobos#7362 and dlang/phobos#7366
=> Phobos: Cherry-pick soft-float improvements

CMakeLists.txt, cmake/Modules/FindMLIR.cmake
This updates will allow LDC to build the code that will allow the support for MLIR
=> MLIR: Updating CMakeLists and adding FindMLIR.cmake

dmd/dsymbolsem.d, ir/irmodule.cpp, tests/codegen/gh3346.d
=> Revert to strong importedModules ModuleInfo refs

CMakeLists.txt, cmake/Modules/FindMLIR.cmake
Fixes https://github.com/ldc-developers/ldc/pull/3312
=> CMake: Fix finding MLIR.

.azure-pipelines/posix.yml, .azure-pipelines/windows.yml, .circleci/config.yml, .cirrus.yml, .travis.yml
=> druntime: Fix llvm_prefetch intrinsic for LLVM 10+

gen/ctfloat.cpp
Supporting more hosts and fixing early stoppers such as issue #3270.
=> Improve detection of host real_t semantics

gen/toir.cpp, tests/codegen/vector_init.d
=> Fix casting (static and dynamic) arrays to vectors

gen/toir.cpp, tests/codegen/checkaction_halt.d
=> Add proper support for -checkaction=halt

dmd/builtin.d, runtime/CMakeLists.txt
Testing https://github.com/ldc-developers/druntime/pull/185.
=> druntime: Revise upstream diff a bit & speed-up core.math.ldexp for x87 real

.azure-pipelines/posix.yml, azure-pipelines.yml, driver/linker-gcc.cpp
Wrt. #3461 and the encountered issue with the rdmd executable.
=> [Android] druntime: Handle TLS init issues

gen/classes.cpp, gen/declarations.cpp, gen/irstate.cpp, gen/irstate.h, gen/llvmhelpers.cpp, gen/toconstelem.cpp, gen/typinf.cpp, ir/iraggr.cpp, ir/iraggr.h, ir/irclass.cpp, ir/irdsymbol.cpp, ir/irdsymbol.h, ir/irstruct.cpp, ir/irvar.cpp, ir/irvar.h
Some stuff extracted and cleaned up from #3422.
=> Refactoring: Prepare for proper -linkonce-templates

.azure-pipelines/windows.yml
See ldc-developers/mingw-w64-libs@33aa1e8.
=> Windows: Upgrade bundled MinGW-based libs to v8.0.0

gen/dibuilder.cpp, gen/llvmhelpers.cpp, gen/runtime.cpp, gen/tocall.cpp, gen/toconstelem.cpp, gen/tollvm.cpp, gen/trycatchfinally.cpp, ir/iraggr.cpp, ir/irclass.cpp, ir/irstruct.cpp, ir/irtype.cpp, ir/irtype.h, ir/irtypeclass.cpp, ir/irtypefunction.cpp, ir/irtypestruct.cpp
See commit messages for details.
=> Refactoring: Introduce getIrType()

gen/functions.cpp
=> Remove unused function.cpp:binary

gen/modules.cpp, runtime/CMakeLists.txt
Testing https://github.com/ldc-developers/druntime/pull/197.
=> druntime: Switch to rt.sections_elf_shared on Windows too

README.md
Incl. emphasizing that the package managers are community-maintained, I'm tired of reading the same questions again and again.
=> README: Add latest release badge (incl. prereleases) and update notes about prebuilt packages

gen/abi-spirv.cpp, gen/dcompute/abi-rewrites.h
I'll add tests for these in the next PR that will add support for OpenCL images.
=> [dcompute] fix some ABI issues

gen/toconstelem.cpp
Fixes #3836 by fixing an oversight in 598b615e77.
=> Fix regression in recent toConstElem refactoring

gen/functions.cpp
As cloning a function with debuginfos has always been problematic, and I haven't found a suitable workaround for new assertions with LLVM 13, without resorting to even blunter instruments like suppressing debuginfos for weak-any functions and MSVC targets.
=> Try a blunter, clone-less approach for MSVC weak-any emulation

gen/toconstelem.cpp, gen/toir.cpp, ir/iraggr.cpp, ir/irtypeaggr.cpp, tests/compilable/union_voidinit.d
As the frontend has been more strict for some time.
=> Simplify selection of IR fields for unions

gen/dibuilder.cpp
As clang doesn't seem to either. This *might* fix #3864.
=> DI: Don't emit explicit alignment for pointer types

driver/linker-msvc.cpp, gen/llvmhelpers.cpp, tests/codegen/dllimport_gh3916.d, tests/codegen/dllimport_gh3926.d
=> Windows: Revert to previous define-on-declare solution for -dllimport=defaultLibsOnly

driver/timetrace.d
=> -ftime-trace: JSON-escape filenames

.azure-pipelines/1-posix-setup.yml, .azure-pipelines/android-llvm-config.in, .travis.yml, CHANGELOG.md, azure-pipelines.yml
This reverts commit 12b94f2f8d8c70a10775a0f2599df2740c839eff.
=> Azure/Travis CI: Bump LDC-LLVM to v14.0.0

gen/passes/DLLImportRelocation.cpp, gen/passes/GarbageCollect2Stack.cpp, gen/passes/SimplifyDRuntimeCalls.cpp, gen/passes/StripExternals.cpp
Will do the other passes in this PR when this is green.
After this will do new pass implementation for our passes.
=> Factor out legacy implementation details from GC2Stack

ir/irclass.cpp
=> [rm-getPointeeType] global variable for interface initZ

gen/naked.cpp
Changed in https://github.com/llvm/llvm-project/commit/00797b88e0113aeea03045b18b3f63332f850dfe
=> `InlineAsm::Verify` -> `InlineAsm::verify`

gen/classes.cpp
This logic should be merged with toir.cpp:visit(TypeidExp *e) in https://github.com/ldc-developers/ldc/pull/4086
=> Use typed gep in `classes.cpp`

gen/optimizer.cpp
This is to allow the corresponding functions for the new pass manager to use the old names.
This is related to https://github.com/ldc-developers/ldc/issues/3961
=> Renamed pass functions in gen/optimizer.cpp by prepending legacy.

gen/asm-gcc.cpp
Reverts ldc-developers/ldc#4122
=> Revert "Supply indirect types of gcc asm inputs too"

gen/asm-gcc.cpp, gen/irstate.cpp, gen/naked.cpp
Reverts ldc-developers/ldc#4120
=> Revert "Provide indirect types to `createInlineAsmCall` from `naked.cpp`"

gen/dvalue.cpp, gen/dvalue.h, gen/llvmhelpers.cpp, gen/toir.cpp
(temporarily default to `--opaque-pointer` on for testing)
=> Remove final use of getPointerElementType

gen/optimizer.cpp
This is related to https://github.com/ldc-developers/ldc/issues/3961
Starting to produce optimization pipeline using the new pass manager for LLVM15.
=> New passmanager clean

runtime/druntime/src/ldc/libfuzzer.di
=> Remove Phobos dependency from druntime's ldc/libfuzzer.d

packaging/README.txt
=> README.txt: Clarify there's no way around MSVC++ toolchain for static linking

CHANGELOG.md, gen/binops.cpp, gen/binops.h, gen/toconstelem.cpp, tests/codegen/pointer_offsets_gh4362.d
=> Fix corner cases for pointer offset codegen

tests/codegen/fsplit_stack.d, tests/driver/fwarn-stack-size.d
=> Add testcases that were missing in #4378 and #4379

runtime/druntime/src/rt/config.d
On macOS-arm64, druntime integration test `exceptions` failed when using shared druntime. Sub-test `unknown_gc` failed because the `rt_options` global defined in the executable apparently doesn't override the default global in druntime.
The default global in druntime used to be instantiated, apparently to make linker-level overriding work in most cases. I've firstly tried to do it more elegantly with LDC, using a non-instantiated `@weak` symbol. That brought no regressions, but also didn't fix the macOS-arm64 problem. So I'm additionally trying to load an exported symbol from the *executable* via `dlsym`, which made the test work on macOS-arm64.
Coupled with an explicit `export` visibility, this PR should also allow 'overriding' the special globals on Windows when using the druntime DLL.
=> druntime: Handle special rt_* globals more robustly with *shared* druntime

driver/toobj.cpp, gen/optimizer.cpp, gen/optimizer.h
After comparing with [clang/lib/CodeGen/BackendUtil.cpp (v15)](https://github.com/llvm/llvm-project/blob/8dfdcc7b7bf66834a761bd8de445840ef68e4d1a/clang/lib/CodeGen/BackendUtil.cpp#L703-L1015).
=> Slightly revise new LLVM pass manager setup

utils/CMakeLists.txt, utils/split-file.cpp
See https://llvm.org/docs/TestingGuide.html#extra-files
=> Add split-file utility for testing.

.circleci/config.yml, .cirrus.yml, .github/actions/1-setup/action.yml, .github/actions/helper-build-ldc/action.yml, .github/workflows/supported_llvm_versions.yml, CMakeLists.txt, runtime/CMakeLists.txt
See https://github.com/symmetryinvestments/ninja/releases/tag/v1.11.1-sym1.
=> CI: Switch to custom ninja, trying to schedule `ldc2.o` compilation early

gen/declarations.cpp
It should fix #4459 
I have issues building ldc on my PC, so i don't know how to test this change other than submit a PR
=> Do not prefix static libs from pragma(lib) with  `-l`

runtime/druntime/src/core/internal/array/comparison.d
See https://github.com/dlang/dmd/pull/15407.
E.g., `std.typecons.Tuple!float` is a type with `opCmp` returning a `float` (a NaN if any element is NaN...). Comparing arrays of such elements hasn't worked in D v2.103 and earlier. Since v2.104, `__traits(compiles, a < b)` newly succeeds, but the runtime template lowering fails to compile. The lowering implementation was fixed by the cherry-picked commit in v2.105.
```D
import std.typecons : Tuple;
alias T = Tuple!float;
static assert(__traits(compiles, (T[] a, T[] b) => a < b)); // succeeds since v2.104
auto foo(T[] a, T[] b) { return a < b; } // only really compiles since v2.105
```
Cherry-picking this makes trait & runtime behavior consistent again.
=> Cherry-pick druntime fix for array comparisons with floating-point opCmp

gen/tollvm.cpp, tests/codegen/importc_static.i, tests/lit.site.cfg.in
=> ImportC: Fix `static` linkage

runtime/druntime/src/core/thread/fiber.d
=> Unconditionally define m_allowMigration field in Fiber

.github/actions/7-package/action.yml, .github/actions/merge-macos/action.yml, .github/actions/merge-windows/action.yml, .github/actions/upload-to-github/action.yml
see https://github.com/actions/toolkit/tree/main/packages/artifact#v2---whats-new
=> GHA: Switch to new artifacts API

runtime/druntime/src/rt/sections_elf_shared.d
This PR closes #4547 by re-implementing _dyld_get_image_slide.
=> Add Darwin scanSegments without private API

.github/actions/5-install/action.yml
Fixes #4565 
(got broken by #4548 )
=> Include libLTO.dylib in release packages

.github/actions/5a-ios/action.yml, .github/actions/merge-macos/action.yml, .github/workflows/main.yml
=> CI: Use `-simulator` suffix for x86_64 iOS triple

driver/main.cpp, tests/codegen/wasm_emscripten.d
fixes https://github.com/ldc-developers/ldc/issues/4670
=> Add support for triple wasm32-unknown-emscripten

.circleci/config.yml, .cirrus.yml, .github/actions/1-setup/action.yml, .github/workflows/supported_llvm_versions.yml, tests/debuginfo/classtypes_gdb.d, tests/debuginfo/nested_gdb.d, tests/debuginfo/print_gdb.d, tests/lit.site.cfg.in
=> lit tests: Drop support for gdb < 8 and dependency on distutils pip package

driver/configfile.d
This cleans up previous PR #4812 as requested by @JohanEngelen.
https://github.com/ldc-developers/ldc/pull/4812#pullrequestreview-2530899681
=> Clean up placeholder work

gen/llvmhelpers.cpp, tests/sanitizers/asan_gh4816.d
=> Fix ASan for zero-sized variables passed as function argument.

runtime/druntime/src/core/thread/fiber.d
extracted from https://github.com/ldc-developers/ldc/pull/4835
=> restore version LDC_Windows after refactoring
